### ISSUE TITLE
Add syslog support to configure-bosh

### ISSUE THREAD

**Issue by theozaurus** [pivotal-cf/om#105]
Hi,
In recent versions of Ops Manager the BOSH director tile support Syslog. However, om does not surface these options. It would be great if the `configure-bosh` action had a `--syslog-configuration` option.
Thanks,
Theo

**Comment by camattin** [comment]
We would also love to see this feature added.

**Comment by kenchenpcf** [comment]
You can use `configure-director`. It has a `syslog-configuration` option. See here: https://github.com/pivotal-cf/om/blob/master/commands/configure_director.go#L24

**Comment by theozaurus** [comment]
Great thanks
