### ISSUE TITLE
`om curl` writes an error to stdout for a non-2XX response

### ISSUE THREAD

**Issue by davewalter** [pivotal-cf/om#112]
If Ops Manager responds with a 4XX or 5XX response code, `om` outputs a message to tell you that the server responded with an error:
```
could not execute "curl": server responded with an error
```
This causes problems if you try to pipe the output to jq. We feel that this error should be printed to stderr instead of stdout.

**Comment by madamkiwi** [comment]
Fixed in master. Thanks for reporting
