### ISSUE TITLE
Unable to re-upload stemcells

### ISSUE THREAD

**Issue by rcw5** [pivotal-cf/om#115]
`om upload-stemcell` has a short circuit where it won't reupload any stemcells that exist in Operations Manager (as listed in the output of `/api/v0/diagnostic_report`).

However because Ops Manager doesn't have 'stage stemcell' functionality there are times when re-uploading a stemcell makes sense. We are writing pipelines for PCF deployment and have hit one such situation in the upgrade of an ops manager:

1. Export installation from existing ops manager and re-import into new ops manager
1. Reupload stemcells into the new ops manager
1. "revert staged changes"

**Result** => All tiles in ops manager will go orange because the stemcells are no longer attached to the tiles

Although the stemcell is still listed in the `diagnostic_report` it's not tied to the tile and the only solution I can find is to re-upload the stemcell. However it's not possible to do this using `om upload-stemcell` as it will return `stemcell has already been uploaded`. 

I don't want to remove "revert staged changes" from our pipeline as it ensures that only the state being set by our scripts is applied to the foundation.

I can see two potential solutions to this problem:

1. Add a -force flag to `upload-stemcell` which will skip the diagnostic report check and always upload the file
1. Extend `om curl` to support uploading binary data, so I could use curl to hit to the `/api/v0/stemcells` endpoint

I'd be happy to send a PR for either of these but don't want to take one route if there is a preference for another.

**Comment by ryanmoran** [comment]
@rcw5 we would welcome a PR for a `--force` flag.

I think it could look something like this:
```
om \
  --target pcf.example.com \
  --username username \
  --password password \
    upload-stemcell \
      --stemcell /path/to/stemcell.tgz \
      --force
```

**Comment by acrmp** [comment]
Thanks for the PR @rcw5!
