### ISSUE TITLE
Feature request: Add a --format flag for choosing output format

### ISSUE THREAD

**Issue by olle-brkt** [pivotal-cf/om#118]
It would be great if there was an option for changing the output, just like [pivnet-cli](https://github.com/pivotal-cf/pivnet-cli) has:
`--format=[table|json|yaml] Format to print as (default: table)`

This would be very helpful for parsing output from for example `deployed-products`.

See example of how pivnet-cli does it:
```
olle | ~/work/pcf | master
 ► pivnet r -p elastic-runtime -r 1.11.0
+------+---------+--------------------------------+--------------------------+--------------+---------------+
|  ID  | VERSION |          DESCRIPTION           |        UPDATED AT        | AVAILABILITY | RELEASE TYPE  |
+------+---------+--------------------------------+--------------------------+--------------+---------------+
| 5804 | 1.11.0  | Please refer to the release    | 2017-11-01T17:33:00.869Z | All Users    | Minor Release |
|      |         | notes                          |                          |              |               |
+------+---------+--------------------------------+--------------------------+--------------+---------------+
olle | ~/work/pcf | master
 ► pivnet r -p elastic-runtime -r 1.11.0 --format json
{"id":5804,"availability":"All Users","eula":{"slug":"pivotal_software_eula","id":120,"name":"Pivotal Software EULA","_links":{}},"release_date":"2017-06-15","release_type":"Minor Release","version":"1.11.0","_links":{"product_files":{"href":"https://network.pivotal.io/api/v2/products/elastic-runtime/releases/5804/product_files"},"eula_acceptance":{"href":"https://network.pivotal.io/api/v2/products/elastic-runtime/releases/5804/eula_acceptance"}},"description":"Please refer to the release notes","release_notes_url":"https://docs.pivotal.io/pivotalcf/1-11/pcf-release-notes/runtime-rn.html","eccn":"5D002","license_exception":"TSU","end_of_support_date":"2018-03-31","updated_at":"2017-11-01T17:33:00.869Z"}
```

**Comment by olle-brkt** [comment]
Oops, I did search before but missed this. https://github.com/pivotal-cf/om/issues/77 sorry!

Might be a duplicate, but I do think this would be a nice addition to avoid having to use om curl.

Not only do you have to keep track of the API endpoints, you also have to remove the headers so you can't directly transform the output into a json :)

**Comment by rizwanreza** [comment]
We have scheduled a feature story in our backlog to work on this for all commands in om. This should be landing in a future release soon.

I am going to close this issue, feel free to reopen if there's anything else you want to talk about.

**Comment by ryanmoran** [comment]
Feature Story: https://www.pivotaltracker.com/story/show/152703695

**Comment by olle-brkt** [comment]
Thanks! Looking forward to it

**Comment by olle-brkt** [comment]
saw that this was added - along with enforcing credentials to be environment variables. both are great additions - good job!
