### ISSUE TITLE
net/http: request canceled (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by johnlonganecker** [pivotal-cf/om#120]
3.33 GiB / 8.99 GiB [===============>--------------------------]  37.06% 50m55s could not execute "upload-stemcell": failed to upload stemcell: could not make api request to stemcells endpoint: Post https://<opsman>/api/v0/stemcells: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

This fails after trying to upload a custom windows stemcell after about 30minutes. Any ideas? does OM have some builtin timeout or do we need to modify nginx on opsman? Thanks!

**Comment by zachgersh** [comment]
@johnlonganecker - this flag defaults to 30 minutes (1800 seconds) `--request-timeout`

Might want to modify that due to how big your stemcell is.

**Comment by johnlonganecker** [comment]
Duh! should have looked for a flag like that. Thanks! I will run it and close this if it succeeds.
