### ISSUE TITLE
om deployed-status returns empty stats even the product is existing 

### ISSUE THREAD

**Issue by steven-zou** [pivotal-cf/om#123]
./om -t https://30.0.0.5 -u admin -p '*********' -k curl --path /api/v0/deployed/products/:product_id/status

{
  "status": []
}

returned.

Actually the product is there.

**Comment by madamkiwi** [comment]
Hi @steven-zou,

What is the output from running: `om -t https://example.com -u username -p password -k curl --path /api/v0/deployed/products`?

This should display a list of deployed products.

cc @kkallday

**Comment by utako** [comment]
Hi @steven-zou,

I'm going to go ahead and close this issue as we haven't heard from you in a while. Please feel free to reopen this issue when you're able to provide us with the output requested above.

Thanks,
@utako, PCF Releng Team
