### ISSUE TITLE
Properties with `configurable:false` work differently on CLI and on OpsManager UI

### ISSUE THREAD

**Issue by bengtrj** [pivotal-cf/om#126]
There are two settings for a `property_blueprint` as far as `configurable` goes:
* `true`
* `false` (the same as just don't include that key)

## Actual Behavior

Our problem is with `false`. The observed behavior is that we can set it on our tile through the opsmanager UI, but not through the OM CLI. However, the OM CLI exits 0, so it is silently failing to change the value of the `configurable: false` field. The UI successfully changes the value and does not display any error messages.

## Expected Behavior
1. Can't set any value to the configuration either on CLI or OpsManager UI or OpsManager API.
1. The OM CLI should exit with a non-zero status code. If the information didn't get set, then this shouldn't appear to succeed because it makes it hard to debug.
1. The OpsManager docs claim that if `configurable` is not set to true, the field will not show in the UI. This is not true; the field shows up in the UI AND is configurable. See https://docs.pivotal.io/tiledev/1-12/product-template-reference.html : 
>configurable
>No property will be viewable in a form if unless configurable is set to true. Rather than giving the
>user the ability to enter a value, the value is generated by Ops Manager.

**Comment by ryanmoran** [comment]
@bengtrj we will take a look at this, but its most likely an issue with the underlying OpsMan API. The API just returns `200 OK` for a large number of requests, including some that you would expect to receive something like a `422`, like this one.

**Comment by kenchenpcf** [comment]
This seems like an underlying Ops Man API issue. cc @sadvani @melmatsuo
