### ISSUE TITLE
configure-product properties before networking causes failure

### ISSUE THREAD

**Issue by aegershman** [pivotal-cf/om#130]
If you're configuring a product-- in my case, a PCF tile to opsman-- before the `networks_and_azs` has been configured, it's possible for the `properties` step to fail because the existence of certain properties keys could be dependent on the `networks_and_azs` block being configured beforehand.

I believe the problem is here: https://github.com/pivotal-cf/om/blob/master/commands/configure_product.go#L75-L87

This could be mitigated by either configuring the products' `networks_and_azs` as a separate `./om` call from configuring the products' `properties`, or by putting the configuration of the `properties` block **after** configuring `networks_and_azs` and `resources`.

**Comment by ryanmoran** [comment]
Merged https://github.com/pivotal-cf/om/pull/129, new release coming as soon as it passes through our pipelines.
