### ISSUE TITLE
Windows executable missing .exe file extension

### ISSUE THREAD

**Issue by sneal** [pivotal-cf/om#131]
The [published release binary on Windows](https://github.com/pivotal-cf/om/releases/download/0.29.0/om-windows) should have a `.exe` file extension.

`om-windows` => `om-windows.exe`

This avoid confusion by some Windows user's who don't realize they need to add the file extension.

**Comment by evanfarrar** [comment]
👍  I just realized this was a thing on BBL and came here to see if OM had the same issue: https://www.pivotaltracker.com/story/show/155055940

**Comment by evanfarrar** [comment]
Particularly in Powershell, it seems, this is hard to figure out why it is opening your program in IE instead of running it

**Comment by mcwumbly** [comment]
latest releases now have that `.exe` goodness
