### ISSUE TITLE
om client wait indefinitely when there is no route to target endpoint

### ISSUE THREAD

**Issue by hegderaj** [pivotal-cf/om#132]
When IP without route to is used as target in om client, om client will wait indefinitely. When creating OAuth token from UAA, it is continuously retrying to get the token, since 'dial tcp xxx.xxx.xx.xx: i/o timeout' is treated as temporary error. This causing om client to wait indefinitely. 

om -t xxx.xxx.xx.xx -r 20 -k -u username -p password

os: ubuntu 16.04
om version: 0.33.0

**Comment by hegderaj** [comment]
Raised PR for the above issue.

**Comment by kkallday** [comment]
Merged #133.
