### ISSUE TITLE
Add Variable for target

### ISSUE THREAD

**Issue by cxhercules** [pivotal-cf/om#137]
Like many of the other tools we using in this eco system it would be great to be able to specify target/URL of system we are trying to access. Use case is customer with many foundations and accessing them from jumpbox. Using something like direnv, or other automation to set environment. 

Something like the variable for username and password here:
https://github.com/pivotal-cf/om/blob/a006538ab52ec8b7950fa7c47662ed2e916ebc8e/acceptance/env_var_creds_test.go#L15

We should be able to set like so in environment:
```
export OM_TARGET="https://something.io/"
```

**Comment by mcwumbly** [comment]
hey @cxhercules - I see your point about this being consistent with other tools in the ecosystem and how it could help in the scenario you mentioned. Thanks for providing that context.

The only risk I see with letting this kind of state sit in your environment is accidentally executing something on the wrong ops man.

I do want to discuss this a bit with the team first to see whether there have been any prior discussions about adding this feature that we should be aware of first.

**Comment by mcwumbly** [comment]
@kkallday [PR'd this recently](https://github.com/pivotal-cf/om/pull/179) and it's now included in release `0.38.0`
