### ISSUE TITLE
Support template values in the config file for configure-product

### ISSUE THREAD

**Issue by mcwumbly** [pivotal-cf/om#140]
The `configure-product` command now has a `--config` flag which uses [a single, flat `yml` file](https://github.com/pivotal-cf/om/tree/master/docs/configure-product#configuring-via-file) for configuring a product tile.

It would be nice if this supported template variables along the lines of what Concourse and BOSH do.  This would allow 

For example, Concourse supports templated variables that can be supplied like this:

```bash
$ fly set-pipeline --help
...
[set-pipeline command options]
...
      -v, --var=[NAME=STRING]       Specify a string value to set for a variable in the pipeline
      -y, --yaml-var=[NAME=YAML]    Specify a YAML value to set for a variable in the pipeline
      -l, --load-vars-from=         Variable flag that can be used for filling in template values in configuration from a YAML file
```

Where BOSH has similar features:

```bash
$ bosh interpolate --help
...
[interpolate command options]
      -v, --var=VAR=VALUE        Set variable
          --var-file=VAR=PATH    Set variable to file contents
      -l, --vars-file=PATH       Load variables from a YAML file
          --vars-env=PREFIX      Load variables from environment variables (e.g.: 'MY' to load MY_var=value)
          --vars-store=PATH      Load/save variables from/to a YAML file
```

Having the ability to specify template variables in om's config file would allow a more standardized way to pass in things that currently come from terraform outputs in many people's workflows, for example.

What do other folks think? Is this something that would be useful?  If we do something like this, what syntax would be preferred for the variables within the template YML files?  Which method of passing vars would be most useful to have first (command line flags, environment variables, a separate file, etc.)?

**Comment by jtarchie** [comment]
What is the reason to support variables? For concourse and bosh the abstraction of variables is so that a YAML file can be reused for different deployments, respectively.

**Comment by mcwumbly** [comment]
@jtarchie there are two main motivations for this in my mind:

1. separating secrets from the config template
2. decoupling the config template from the source of the values that often populate it (like terraform outputs).

I think (2) is actually the primary thing I had in mind when writing this.

It would allow you to have do something like that following (pseudo):

```sh
terraform apply
terraform output -json | yj -r > tf-outputs.yml
om configure-product -c config.yml -l tf-outputs.yml
```

If the name of a terroform output changed from `foo` to `bar`, then I would just update by `config.yml` template to use that name instead:

```diff
 some-property:
-  some-key: ((foo))
+  some-key: ((bar))
```

**Comment by jtarchie** [comment]
Implementing the diff of a configuration is hard. As comparing the YAML payload to that was is extracted from the OpsMan API may not converge.

For example,

1. credentials are exported as `***`
2. some GETs don't exist for the POSTs

**Comment by mcwumbly** [comment]
Hmm... diffing configurations isn't in scope for this as far as I'm concerned... (If you mentioned it because of the diff in my previous comment, that was just there to illustrate the change that I as a human would make to my file if necessary.)

**Comment by mcwumbly** [comment]
closing this since we have an initial implementation for the `--vars-file` flag now. let's open new, more specific issue for further refinements
