### ISSUE TITLE
Acceptance tests do not test real world data

### ISSUE THREAD

**Issue by fredwangwang** [pivotal-cf/om#143]
When using `om` to `configure-director`, we used the documentation as a reference, and this was incorrect. Could `om` add end-to-end tests to validate suggested data?

**Comment by kenchenpcf** [comment]
@fredwangwang Can you tell us a bit more about where you're seeing the incorrect documentation? Is this for a specific infrastructure?

**Comment by fredwangwang** [comment]
As the `configure-director` method is really a wrapper for an api endpoint of opsman, the method implementation itself has no problem. However, because of the json payload format mismatch between your doc and opsman's doc, we were unable to configure the director correctly. A suggestion would be pointing your doc to opsman's doc and we can find the payload format there, or just keeping the doc up-to-date with opsman's. But it's your choice.

**Comment by heycait** [comment]
It looks like our README refers users to OpsMan docs and does say that some commands accept JSON and should refer to the OpsMan docs. 

Regarding the acceptance tests using fake data, our goal isn't to specify and test actual data. It's would be difficult for us to constantly update our acceptance tests if OpsMan changes what they require. 

We're going to close this issue. If this doesn't address the issue, feel free to reopen this issue.

**Comment by mcwumbly** [comment]
I think we do cover this to some degree in our `om` CI pipeline as well:
https://releng.ci.cf-app.com/teams/main/pipelines/om

One thing we could (should?) consider doing in the future is bringing the om CI configuration into the om repo and/or extracting some of the pieces into standalone tests here.
