### ISSUE TITLE
Known issue: `om staged-config` returns a 404 for credentials nested under selectors

### ISSUE THREAD

**Issue by ljfranklin** [pivotal-cf/om#145]
This is due to a bug in OpsMgr where the `/credentials` endpoint does not include credentials that are nested under selectors like radio buttons: https://www.pivotaltracker.com/n/projects/803319/stories/156902569. When the OpsMgr bug is fixed, the command should work as expected.

**Comment by mcwumbly** [comment]
@ljfranklin it looks like the Ops Manager bug has been fixed. Let's take another look at this and validate things are good on our end.

**Comment by ljfranklin** [comment]
Ran `om staged-config --product-name cf --include-credentials` against an OpsMgr 2.2 environment and it seems to work as expected now. For example I can see the secret value of `.properties.system_blobstore.external_azure.access_key` which is nested under a radio button. Closing this out.
