### ISSUE TITLE
`configure-director` command requires a more for idempotency invocations

### ISSUE THREAD

**Issue by jtarchie** [pivotal-cf/om#147]
We are working on a script that calls `configure-director` every with the same argument values.
We've after the initial invocation, that errors (from OpsMan API) occur.
These errors are related to the fact that some endpoints can be set after a director has been deployed.

For example, the `--network-assignment` argument, returns an error of:

```json
{"errors":["You cannot change the network or availability zone configuration once you have deployed"]}
```

Feature Request: When `configure-director` is called multiple times with the same argument values, it Just Works™, and moves along.

**Comment by ljfranklin** [comment]
Fixed in https://github.com/pivotal-cf/om/pull/148
