### ISSUE TITLE
Automatically update command documentation

### ISSUE THREAD

**Issue by mcwumbly** [pivotal-cf/om#150]
Currently, the main README lists all of the commands and is auto-updated.

But the `docs/commands/*` docs are not auto-updated and many commands are not documented.  It would be nice to improve the automation to keep these docs up to date.

**Comment by nbconklin** [comment]
@iplay88keys wrote a test to ensure that the ReadMe is updated and includes all the commands. We'll continue to iterate on this to create more robust documentation. Closing this for now. We've created stories in our backlog to broaden om documentation.
