### ISSUE TITLE
Cutting a new release soon?

### ISSUE THREAD

**Issue by aegershman** [pivotal-cf/om#158]
Hey there,

I'm trying to selectively upload/deploy stemcells.

I need the "support floating flag when uploading a stemcell" feature added in this commit: https://github.com/pivotal-cf/om/commit/16d387b8beb661f20fc5cd5d8af5ff878b597282 (Without this, when I run `upload-stemcell`, the stemcell is automatically applied to all the corresponding products, which I do not want)

Do you have an idea of when the next om release might be cut with this feature included? In the mean time I can build from source, but I don't want to build from source for production use. Apologies, I don't mean to sound pushy or anything, just figured I'd ask

Thank you!

**Comment by mcwumbly** [comment]
@aegershman - thanks for bringing this up. we've been trying to cut releases _pretty_ frequently, but there isn't a "standard" cycle time at this time. 

We'll likely cut a new release sometime within the next week.

**Comment by aegershman** [comment]
Thank you! I appreciate it.
