### ISSUE TITLE
Any official Docker image release?

### ISSUE THREAD

**Issue by aegershman** [pivotal-cf/om#161]
I know the [pcf-pipelines project](https://github.com/pivotal-cf/pcf-pipelines/blob/master/tasks/deploy-opsman-vm/task.yml#L21) has tasks which use a docker image called [pcfnorm/rootfs](https://hub.docker.com/r/pcfnorm/rootfs/tags/), but even the latest version of this image only comes with `om 0.34`.

No big deal if not, but is there an "official" docker image which has the latest version of `om` on it?

Thanks for your time, I appreciate it.

**Comment by heycait** [comment]
Hey @aegershman! We don't have an official Docker image. Currently we have a large Docker image that contains everything we need in CI. 

We're going to discuss this as a team and see if this is something we want to support. We'll get back to you. 

cc @davewalter

**Comment by aegershman** [comment]
No big deal if not. My use case is using `om` with platform-related Concourse tasks. Maybe I can go pester the `pcf-pipelines` team to see if they'll support a docker image with the latest version 😀

Thanks for your consideration

**Comment by joshzarrabi** [comment]
Hi @aegershman, we do not have any plans at the moment to support an official `om` docker image, one pattern you could follow is to consume the github release as a resource to all of the tasks that need it instead of baking it into the image itself.
