### ISSUE TITLE
`om stage-product` should be able to take a tile path

### ISSUE THREAD

**Issue by jtarchie** [pivotal-cf/om#162]
We briefly discussed this [on slack](https://pivotal.slack.com/archives/C5V956L13/p1526056587000276?thread_ts=1526055938.000214&cid=C5V956L13). In short, we'd like to be able to say `om stage-product --product-file /path/to/tile.pivotal` instead of specifying `--name` and `--version`.

This helps us avoid having to re-specify information the system already knows when using this command in CI, and other times users use this right after `upload-product`.

Signed-off by @anEXPer

**Comment by mcwumbly** [comment]
I'm a bit on the fence about this interface, and wondering if we could do something a little different that achieves the same goal.  For example, a command that prints the metadata for a tile which could be piped to `stage-product`.  Or maybe we're missing an flag on `upload-product` that attempts to stage it immediately...

**Comment by jtarchie** [comment]
Why on the fence?

**Comment by mcwumbly** [comment]
UX-wise, my gut feel is that it seems odd to refer to a file on my local filesystem when I'm talking about a product that is in OM's list of available products

**Comment by davewalter** [comment]
To me, it feels like the "feature" we are missing is the ability to omit the version from this request. In the Ops Manager UI, users don't get the choice of which version they want to stage; Ops Manager chooses the semantically latest version and that is what the user is presented with.

I know that that would still mean that you have to specify the product that you want to stage, which still ties your tooling to the specific product being staged, which is less than ideal. An alternative is to add `om stage-all-available-products` that would retrieve the list from the Ops Manager API and iterate through it.

**Comment by mcwumbly** [comment]
@jtarchie for your use case, would this idea from @davewalter meet your needs?

> To me, it feels like the "feature" we are missing is the ability to omit the version from this request. In the Ops Manager UI, users don't get the choice of which version they want to stage; Ops Manager chooses the semantically latest version and that is what the user is presented with.

I think I like that best so far, personally.

**Comment by jtarchie** [comment]
@mcwumbly, I'd rather explicitness on this, for our use case. The idea is that a client can specify a product version to stage. Just in case someone has done something from the UI. There is a config file that should be the source of truth of what product version to use. In the case of a pipeline, the `.pivotal` that they are uploading would be the source of truth for that version number.

**Comment by anEXPer** [comment]
`--stage` on the upload would also do it for us, I think. It's my favorite of the suggestions so far.

**Comment by davewalter** [comment]
@anEXPer We can discuss in IPM, or you can submit a PR if you need this quickly.

**Comment by anEXPer** [comment]
I think we'd be happy with the separate metadata command @aegershman has sketched out, which we can use to get values to pass to `stage-product`. I'm closing this in favor of https://github.com/pivotal-cf/om/issues/231.
