### ISSUE TITLE
Enable simple use of Concourse inputs for `om` creds

### ISSUE THREAD

**Issue by anEXPer** [pivotal-cf/om#163]
I know we've had some slack discussion of this, and I'd like to get us on the same page.

We (the team known as NORM for reasons that I assume seemed sufficient at the time to the people naming it) are working to make it easy and repeatable to deploy Ops Manager with automation. Our approach so far has been to wrap calls to `om` in an executable of our own.

This is turning out to be a comparatively expensive approach, and I'd like to revisit our reasons for it.

A major factor is that we're interested in making invocations of `om` in CI and dojo environments as simple as possible.

When using Ops Manager in CI, we'd like to consume auth as an input. There are a variety of reasons that this makes sense for us. So, our wrapper currently uses a `--auth-file` argument. It takes the bit of yaml in that file and then shells out to `om` with the `--target`, `--user`, and `--password` flags set appropriately.

It would be much better for us, and eliminate tons of code, if `om --auth-file` was directly supported.

My understanding of how this has cashed out in previous discussions is that y'all are reluctant to add a feature that encourages users to put credentials on disk, backed by a general customer mandate to avoid writing creds to disk.

I am unaware of any model by which creds can be made available as an input in Concourse without hitting the disk. Inputs in Concourse are made available on the file system, case closed.

Not using inputs is also an option, of course - we could require that credentials be set as parameters in the Concourse Tasks, using `om`'s existing support for env vars. However, this increases the complexity of using the Concourse tasks and requires credentials to be controlled by setting the pipeline, rather than by updating a resource. Similarly, we could add a bit of code in front of our invocations of `om` to export said env vars with values from a file. Again, though, this adds complexity to our tooling - we're also trying to make the Concourse tasks so bone simple that they're an effective model for those trying to use `om` in other CI systems.

So. Would y'all take a PR to add this, and if not, why not? If nothing else, I'm hoping we can get to a persistent/reference-able articulation of the positions on the table here.

**Comment by anEXPer** [comment]
Thanks for the responses, @zachgersh. I'm trying to have a legible conversation about the trade-offs here, so I'm going to try and structure some of the back-and-forth here. My overall theme is "it's good to support and afford not writing the creds to the disk, but creds will be on disk sometimes and it's wrong to make that so painful."

## "Use Credhub"
On the topic of Credhub, and I hope to not litigate this much, _it is not available in all contexts._ Especially not in the context of bootstraps and dojos, both of which are core for us. I'm going to discuss everything else assuming that while Credhub (and LastPass, and Vault) are good options much of the time, it's also necessary to provide good solutions in their absence. I'll stipulate that it's important for any such solution to afford easy transition to using a credential management system.

**Credhub does not work for our first targeted context.**

## "Use Resources"
There's two ways to use resources to solve this problem. The first is to have a resource that consumes the credential to accomplish work. This requires that resource consume its variables at `set-pipeline` time. (Please remember we're assuming the absence of Credhub or a similar service.)

The second is to have a resource fetch the credentials to be made available to a task. This allows creds to be updated without reconfiguring the pipeline. _The resource interface is the filesystem._ Credentials made available to tasks as resources are written to disk, where the task must read them. This is a feature we find important, especially in the presence of processes (again, please remember, not including in this specific case external credential management services) that may automatically generate, update, or rotate credentials.

**Using Concourse Resources to handle credentials requires we either accept the pipeline must be set with each change, or requires writing them to disk.**

## "Use env vars"
There's two ways to use Env Vars to solve this problem in Concourse. One is to set the env vars as params on the task. This requires the pipeline be updated in order to change credentials. The second is to have some extra complexity that reads variables into the environment out of a file from an input. This could be shell, or it could be a binary the sole purpose of which is to work around a tool that's made painful choices.

**Env vars as a solution either require us to accept the pipeline must be set with each change, or requires writing them to disk.**

## Some Final Notes
- every time I say that the pipeline must be updated when credentials are, please recall that the most likely thing that will happen here is that a user will write the creds to their own disk and then load them with `-l`. While they can of course use `-v`, that becomes onerous very quickly as the number of creds grow, and actively works against the goal of easy-to-describe-and-repeat workflows for the purpose of dojos and bootstrapping systems.
- similarly, a problem we've become very familiar with is that with productized CI, the parameters become an interface surface. Anywhere we can avoid having a giant list of parameters, that's a substantial win from the perspective of trying to support a legible CI approach as a product consumed outside the company.
- we have considered what we are doing. We understand and agree with a preference to enable stronger and more audit-able patterns. We would be fine with setting an env-var that's sufficiently discouraging like `ENABLE_CREDENTIALS_FROM_DISK_AGAINST_THE_WISHES_OF_THE_BEST_PRACTICE_LORDS=true`
to enable this feature.
- We are writing a tool to work around this because of its importance to our user's experience. We are qualified to make determinations about our users needs. Having a separate tool to handle reading a file is friction in the long-play of having `om` be the Schelling point around which users, internal and external, align to manage Ops Manager with automation.

**Comment by anEXPer** [comment]
user/pass. We have a future story for saml support.

Here's the tool. We're also using it to prototype other things we'd like in OM, and to manage some VM creation: https://github.com/pivotal-cf/pcf-installer

My desire to come back and litigate this again came out of two days of banging our heads against figuring out how to generically wrap calls to `om` so that we can give target and auth arguments from files. We got there, but it made me decide talking about this again was probably worth the engineering and product time from all involved.

**Comment by mcwumbly** [comment]
Thanks @anEXPer.

Given the current state of the world, why not just have the `yml` file in your tool be something the "just uses env vars" to set those values on your environment and then have your tasks directly call `om`?

maybe there are a few flags like `--skip-ssl-validation` and `--target` that we could take as env vars as well to help with that workflow?

**Comment by anEXPer** [comment]
Thanks for having a look.

Using env vars for the call is a possible improvement for our current solution. Indeed, it's the approach I personally would have taken, as it mostly closely mimics what I'd do in the shell, presented with this problem.

The two flags you mention would be necessary additions to the set of env vars, and are probably a good idea regardless.

I regret the existence of our current solution, and would prefer not to spend too much effort discussing it. In addition to all the points I've already laid out, I'll add this:

## "Just wrap existing features"
Indeed, this is what we've chosen to do. A credible alternative is to fork the upstream recalcitrant.

There is a strong reason not to do this, and it's not maintenance, etc, at least not directly. _Our environment contains several fragmented and failed attempts to solve this problem._ "Pipelines for Ops Manager" is something lots of people are throwing lots of time at, and solutions and approaches have evolved over time. This is evidence that any given effort is at least somewhat likely to fail or be deprecated - the ecosystem is difficult, and I absolutely do not hold NORM as an exception to the factors that make it so. The risk mitigation is to push every possible improvement into a focal point (or "[Schelling Point](https://en.wikipedia.org/wiki/Focal_point_(game_theory))"), so that other fractured efforts, past, current and future, also stand to benefit, even if we ourselves don't crack it. `om` is my bet. Forking `om` would add confusion and illegibility to our efforts, and reduce the chance that this problem gets enduringly solved within our broader system.

This compelling reason to avoid forks is _also_ the reason to avoid wrappers, but at least wrappers can make it very explicit what we are working around, and give us a place we can control from which to iterate on the problem, and offer some proof-of-work to demonstrate that we're invested in the problem without contributing as much to the incoherence of the space.

We want very simple, communicable, CI-system-portable patterns for initial automation of PCF environments. We want to solve this for onboarding, etc, but we also want to get to - and as a company, existentially require - continuous delivery to the data center. Getting to the latter requires cracking the former. Cracking the bootstapping problem is easier to the extent that simple, editable files and simple, visible commands do the work while people are becoming familiar with the system and are at a minimum level of general sophistication, conceptual understanding, and tooling access.

**Wrappers and workarounds make problems solvable in software into people/coordination/communication problems, in an environment where that class of problems have been the specific reason for several failed efforts. Direct use and improvement of a visible tool makes long-term success more likely.**

**Comment by ljfranklin** [comment]
Agreed that ensuring creds are never written to disk is difficult / maybe impossible due to how concourse tasks and resource work. My opinion is that we should encourage users of our tools to use credentials stores like Credhub rather than checking secrets into Git repos. It's unfortunate that your users can't use Credhub, but I don't think that should change our position.

If we were to add support for environment variables for a few additional flags (e.g. `OM_SKIP_SSL_VALIDATION`), you could write a small bash helper function:

```
source ./helpers.sh
set_om_target "environment/config.json"
...
set_om_target() {
  export OM_USERNAME="$( jq -r .username $1 )"
  ...
}
```

I understand you would rather not have to do this, but would this be an acceptable middle ground? Long-term an `om` concourse resource would be ideal but I don't know when we'll find the time to prioritize that...

**Comment by mcwumbly** [comment]
another idea: what if we added support for something like:

`OM_CONFIG='{ "some": {"structured": "data", "for": "configuration", "and": "authentication"}}'`

**Comment by anEXPer** [comment]
Please take a step back and think "why am I working so hard to not allow people to read creds from disk, where they are definitely going to be, in the face of so many reasonable arguments and customer needs?"

`bosh create-env` uses creds on disk. GCP cred downloads put creds on disk. Setting concourse pipelines with `-l` has creds on disk. "It is unfortunate that users have this problem, but I don't think we should change" is just... not an acceptable answer from a product perspective. Pure adherence to a dubious "best practice" is not a higher good than making the onramp to automated Ops Man management smooth - _especially given that this is the onramp that can then take users towards stronger security practices._

We want to do what's right.  
If it doesn't work, it's not the right thing.  
If it's not kind, it doesn't work.  

The structured data thing still requires us to do some incantation to export the structured data to an environment variable. I want to give bare `om` commands to people and have them work. The goal is to empower users to have direct fluency in the tools. Razor-sharp legibility! Ownership-grade understanding of their own automation! The harder we can pound that down to _one_ layer of abstraction, the better off we are in terms of enabling our customers.

**Comment by mcwumbly** [comment]
@anEXPer brought a quote from [this article that's been going around recently](https://peter.bourgon.org/go-for-industrial-programming/) to our attention:

> And config files are great for declaring verbose configs, as well as being the most secure way to get secrets into a program. (Flags can be inspected by other users of the system, and env vars can easily be set and forgotten.)

**Comment by mcwumbly** [comment]
@anEXPer, duly noted re: the comment above, but I'd still like to move forward with phase 1 first, personally:

> Let's introduce environment variables for any flags that are missing them as an initial solution to this problem.

Doesn't look like we've done that yet for `OM_TARGET` or `OM_SKIP_SSL_VALIDATION`:

```
Usage: om [options] <command> [<args>]
  --client-id, -c            string  Client ID for the Ops Manager VM (not required for unauthenticated commands, $OM_CLIENT_ID)
  --client-secret, -s        string  Client Secret for the Ops Manager VM (not required for unauthenticated commands, $OM_CLIENT_SECRET)
  --connect-timeout, -o      int     timeout in seconds to make TCP connections (default: 5)
  --format, -f               string  Format to print as (options: table,json) (default: table)
  --help, -h                 bool    prints this usage information (default: false)
  --password, -p             string  admin password for the Ops Manager VM (not required for unauthenticated commands, $OM_PASSWORD)
  --request-timeout, -r      int     timeout in seconds for HTTP requests to Ops Manager (default: 1800)
  --skip-ssl-validation, -k  bool    skip ssl certificate validation during http requests (default: false)
  --target, -t               string  location of the Ops Manager VM
  --trace, -tr               bool    prints HTTP requests and response payloads
  --username, -u             string  admin username for the Ops Manager VM (not required for unauthenticated commands, $OM_USERNAME)
  --version, -v              bool    prints the om release version (default: false)
```

**Comment by calebwashburn** [comment]
@mcwumbly Adding comments from slack thread.  The ask her is about having a common user experience using the `installer` as we are leveraging templated yml file for ways to pass all information into `om`.  With this design we have authorization and target information in the configuration file `auth.yml`.  There have been scenarios where using environment variable and changing contexts where you accidentally can target the wrong environment when we have engineers managing multiple environments.  Ideally this will primarily be ran in a containerized environment where these this isn't as much of a issue but wanting to make sure this is not a requirement.  So less about a debate of which mode is more secure but more about a common UX.  Also, the other scenario we have seen is where pairing with and using flags to set these values on cli(s) the information is commonly shared on the screen or if `bash -x` is enabled they are in logs of tools like concourse.  So there are scenarios where env vars/flags have potential to leak credentials vs files that need to be accessed and queried.  At end feels like there are compelling reasons to do both so would like to propose we enable the added of an auth file flag like what is proposed above but also allow for overriding the value that are provided by the flags/environment variable to allow for both options to be be leveraged and let the consumer determine which approach meets their ux/security needs.

**Comment by calebwashburn** [comment]
I like the idea of an `.omconfig` of whatever we name the file that can set the following: 
- opsman host name (the target)
- opsman user id / pwd or opsman clientId / secret
- skip ssl validation 
- connect timeout
- format of payload
- request timeout
- trace

So basically allow setting up all the `pre-command` options in this file that is in the current working directory but then flag / env variables would override these if specified.

**Comment by mcwumbly** [comment]
could consider also later adding an `om config` command to view / mutate the config (a la `git config`). and that command could redact creds by default.

**Comment by nbconklin** [comment]
Our teams recently had a conversation about this. To summarize:

- we've agreed to use om directly in our concourse tasks, rather than wrap the om commands (for the things that are om's job)
- in order to do the above, om will optionally take environment files (so that om knows which OpsMan to talk to)
- there will likely be additional things that we need to do in om, but this will handle the majority of the use cases at the moment. 

We just submitted a [new issue](https://github.com/pivotal-cf/om/issues/204) to address this. Happy to close this current issue.

**Comment by mcwumbly** [comment]
closing this issue in favor of the new one. thanks @nbconklin !

**Comment by mcwumbly** [comment]
For what it's worth, [this thread](https://lists.cloudfoundry.org/g/cf-dev/message/8169) caught my eye today.  I think it's fine to continue with adding support via a file given the current state of the world, but I did think it was worth sharing here.
