### ISSUE TITLE
`upload-stemcell` error should include hint about file name format

### ISSUE THREAD

**Issue by jtarchie** [pivotal-cf/om#164]
OpsManager requires that the stemcell be uploaded with the filename as seen from Pivnet or bosh.io For example, `bosh-stemcell-3586.7-google-kvm-ubuntu-trusty-go_agent.tgz`.

When using the stemcell resource for concourse, the file is renamed to `stemcell.tgz`. When trying to upload the file, an error occurs from the OpsManager API.

```json
{"errors":["File is invalid"]}
```

Can we make `om` validate the filename is in the correct filename format? Also, there maybe discussion with the OpsMan team to remove this requirement.

**Comment by mcwumbly** [comment]
> Also, there maybe discussion with the OpsMan team to remove this requirement.

We've raised this issue with Ops Man before, but not clear when that will change, given their priorities.  But given that's what we'd like to see ultimately, I think could consider making an improvement here that offered that _hint_ when we get this error (rather than adding the problematic file-based validation into om as well).

For example, we could propagate an error to the user that would say something like:

```
{"errors":["File is invalid"]}

Hint: Perhaps the filename format does not match Ops Manager's expectations?
```

**Comment by davewalter** [comment]
I would be concerned about additional output affecting a user's ability to consume the JSON response programatically. Given the recent discussions around having Ops Manager validate the contents of the stemcell instead of the filename, do we still need to address this in `om`?

**Comment by jtarchie** [comment]
It could be logged to stderr, which does affect being able to parse as STDIN into something like `jq`.

**Comment by fredwangwang** [comment]
Ops Manager will be pulling in a new version of BOSH which will fix this issue: https://github.com/cloudfoundry/bosh-cli/pull/471

As no one else has had this problem, we are going to close. If this comes up in the future, we will consider giving a better error message for older OpsMan compatability
