### ISSUE TITLE
Unable to pipe output from curl command.

### ISSUE THREAD

**Issue by danhigham** [pivotal-cf/om#17]
Can you add a flag to suppress the HTTP output from the curl command. This will enable users to pipe the output to a tool for formatting and processing JSON, such as `jq`.

**Comment by ryanmoran** [comment]
@danhigham The curl response body should be coming back on stdout, and the response headers should be on stderr. You should be able to use `om curl | jq` just fine. Can you provide an example of something that isn't working for you?

**Comment by danhigham** [comment]
Ah, right. I stand corrected. I will close this issue :-)
