### ISSUE TITLE
Bug: `configure-director with az config can be re-run` doesn't work for vsphere

### ISSUE THREAD

**Issue by fredwangwang** [pivotal-cf/om#170]
In the commit abd244d14fd9c808da0d4c360d959175addb7c10, story [#155239461], it added the logic to fetch guid from the api endpoint to avoid the opsman recreating the azs. The logic works for all iaas except `vsphere`. As vSphere has an additional `cluster guid`(see example below):
```
{
  "guid": "existing-az-guid",
  "name": "AZ1",
  "clusters": [
    {
      "guid": "existing-cluster-guid",
      "cluster": "pizza-boxes",
      "resource_pool": "maraudon"
    },
    {
      "cluster": "marinara",
      "resource_pool": "maraudon"
    }
  ]
}
```

The logic added doesn't automatically add the guid for the cluster, breaking the idempotency.

Fix: add the logic to append cluster guid to the payload.

**Comment by fredwangwang** [comment]
@mcwumbly We will start to work on this issue.

**Comment by heycait** [comment]
Thanks for the status @fredwangwang it was about to come up on the backlog.

**Comment by heycait** [comment]
merged in https://github.com/pivotal-cf/om/commit/3dd94a63dadeccad1294665405f037d6f51c0919

**Comment by fredwangwang** [comment]
@heycait The PR #177 was about removing `guid` from `staged-director-config`, so the returned payload doesn't contain any visual noise that means nothing to the end user.

This issue is about adding `cluster guid` to the payload for `configure-director` command. Which is different.

**Comment by madamkiwi** [comment]
Thanks for bringing this to our attention, Huan.  We will reopen this so that it can be addressed.

**Comment by mcwumbly** [comment]
closed via https://github.com/pivotal-cf/om/pull/185
