### ISSUE TITLE
Can we remove `iaas_configuration_guid` from `staged-director-config`?

### ISSUE THREAD

**Issue by mcwumbly** [pivotal-cf/om#190]
In https://github.com/pivotal-cf/om/pull/182, we added back `iaas_configuration_guid` to the output of  `staged-director-config` under the assumption that it will be necessary to support the new multi-CPI features in OM.  But now we are wondering if that is really necessary. Could we instead fetch this information on demand the same way we are doing for networks and availability zones?

We need to verify with the OM team what is safe to assume. For example, can you have availability zones with the same name on two different `iaas_configurations`? If not, we may be able to remove these guids. If so, we likely have to keep them...

Use reference:
http://docs.pivotal.io/pivotalcf/2-2/opsman-api/#fetching-iaas-configurations

**Comment by kcboyle** [comment]
This appears to cause issues when using the top-level key: `iaas-configurations`.

if using `staged-director-config`, we cannot set `configure-director` if using `iaas-configurations` due to this issue.

**Comment by nbconklin** [comment]
@mcwumbly I'm going to close this conversation as we have #377 now. Thank you!
