### ISSUE TITLE
configure-authentication should pick up $OM_USERNAME and $OM_PASSWORD environment variables

### ISSUE THREAD

**Issue by joshzarrabi** [pivotal-cf/om#193]
`om configure-authentication` requires a `username` and `password`, but does not honor what is the environment variables. This would make scripting easier as you would never have to print your username and password to the screen to set up an opsman.

**Comment by genevieve** [comment]
Are you sure those environment variables aren't supported?
https://github.com/pivotal-cf/om/blob/master/main.go#L41
https://github.com/pivotal-cf/om/blob/master/main.go#L47

**Comment by joshzarrabi** [comment]
@genevieve Those are the global variables which don't have any meaning until you configure your opsman auth. I think that the [command specific variables](https://github.com/pivotal-cf/om/blob/master/commands/configure_authentication.go#L21-L22) for `configure-authentication` should pick up these same environment variables, so that when you are scripting for the entire life of an opsman you can use the same environment variables.

**Comment by joshzarrabi** [comment]
Looks good, thank you @genevieve @mcwumbly !
