### ISSUE TITLE
polling interval with import and export installation does not seem to be applied

### ISSUE THREAD

**Issue by jtarchie** [pivotal-cf/om#194]
As per a conversation on slack, we validated that the polling interval that can be specified for the `import-installation` and `export-installation` commands is not being applied anywhere.

This issue captures that the polling interval should be used when polling an external endpoint for a resource.

The output should look like:

```
33s elapsed, waiting for response from Ops Manager...
34s elapsed, waiting for response from Ops Manager...
35s elapsed, waiting for response from Ops Manager...
```

**Comment by mcwumbly** [comment]
Nice find!

**Comment by fredwangwang** [comment]
We repurposed the `polling-interval` for the import installation command to wait for a response from OpsManager while it waits for nginx to come up. If we want the behaviour described, we'll need a need a new polling interval when we implement

**Comment by fredwangwang** [comment]
Also removed the `polling-interval` for `export-installation`. 
It made sense when opsman returns installation which included tiles as well, but now its several hundreds of kilobytes that doesn't really matter.
if this is necessary, we should reopen this issue.
