### ISSUE TITLE
--format=json does not work for `staged-config` 

### ISSUE THREAD

**Issue by chinangela** [pivotal-cf/om#198]
**Issue**
`om staged-config` does not return a json output even if the `--format=json` flag is set

**To reproduce run**
```
om --format=json --target=pcf.hemet.cf-app.com --username=pivotalcf --password=<redacted> -k staged-config --product-name=pivotal-container-service
```

**Expected Result**
The config output in json

**Actual Result**
```
product-properties:
  .pivotal-container-service.pks_tls:
    value:
      cert_pem: "-----BEGIN CERTIFICATE-----
contents
-----END CERTIFICATE-----\r\n"
      private_key_pem: '***'
  .properties.cloud_provider:
    value: GCP
  .properties.cloud_provider.gcp.master_service_account:
    value: hemet-master-serviceaccount@cf-pks-golf.iam.gserviceaccount.com
  .properties.cloud_provider.gcp.network:
    value: hemet-pcf-network
  .properties.cloud_provider.gcp.project_id:
    value: cf-pks-golf
  .properties.cloud_provider.gcp.worker_service_account:
    value: hemet-worker-serviceaccount@cf-pks-golf.iam.gserviceaccount.com
  .properties.cloud_provider.vsphere.vcenter_master_creds:
    value:
      password: '***'
  .properties.network_selector:
    value: flannel
  .properties.network_selector.nsx.nat_mode:
    value: true
...
```

**Comment by zachgersh** [comment]
sadly - it's not wired up as an option to `staged_config`. Potential for a PR here!

**Comment by chendrix** [comment]
We actually do not want to have this be respected.

We are standardizing on only ever providing & accepting "Ops Manager Configuration Files" in yml format.

There is a need here to clarify what the `--format` flag does (and what it impacts), but I think the correct approach is to remove it from being a global flag.

**Comment by mcwumbly** [comment]
> I think the correct approach is to remove it from being a global flag.

Opening a separate issue for that.

**Comment by chendrix** [comment]
Great. And here is a link to the "Only ever provide these in YML format" issue, (which is weirdly in ops-manifest issues):

https://github.com/pivotal-cf/ops-manifest/issues/5
