### ISSUE TITLE
om import-installation not waiting for uaa to start?

### ISSUE THREAD

**Issue by craigbookwalter** [pivotal-cf/om#20]
Hi, getting the logs below running import-installation and apply-changes one after another in a Concourse job. I never got this doing the equivalent from a Python script, so I'm assuming there's something om isn't waiting for to call the import finished.

```
./om -k -t <url> import-installation -dp <pp> -i installation.zip
processing installation
beginning installation import to Ops Manager
 55.15 KB / 55.15 KB [======================================================] 100.00% 1s
3s elapsed, waiting for response from Ops Manager...
finished import
+ ./om -k -t <url> -u <user> -p <p> apply-changes
attempting to apply changes to the targeted Ops Manager
could not execute "apply-changes": installation failed to trigger: could not make api request to installations endpoint: token could not be retrieved from target url: oauth2: cannot fetch token: 502 Bad Gateway
Response: <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.4.6 (Ubuntu)</center>
</body>
</html>
```

**Comment by ryanmoran** [comment]
@craigbookwalter you have found something we haven't gotten to yet. You need to unlock the installation after importing it. You can get aroung this right now by using the following command:
```
om -k -t <url> -u <username> -p <password> curl -p "/api/v0/unlock" \ 
    -x "PUT" \
    -d '{"passphrase": "example-passphrase"}'
```

We will be looking to add a feature to support this natively in `om` soon.

**Comment by ryanmoran** [comment]
@craigbookwalter I initially responded without reading the issue very closely. You are right. We need to add a check after the installation is imported to wait for the decryption to complete and the UAA to become available. Thanks for the report.
