### ISSUE TITLE
Add flag to consume environment files

### ISSUE THREAD

**Issue by nbconklin** [pivotal-cf/om#204]
In order to achieve the outcome of consuming om directly in the concourse tasks (as outlined [here](https://github.com/pivotal-cf/om/issues/163)), we will need to add a flag to consume environment yml files. 
These should be able to provide:

- url
- client id or username
- client secret or password
- whether or not to use TLS/skip-ssl-validation

We have a format that we are using already, but we could change it. Currently we're using `--auth-file`, we could do something like `--env-file`.  

Since we are consuming now from the command line, the env vars, and env file, we should decide on a hierarchy schema. 

cc @anEXPer

**Comment by mcwumbly** [comment]
> We have a format that we are using already, but we could change it. Currently we're using `--auth-file`, we could do something like `--env-file`.

It's a bit redundant since it's also used as a _command_ flag in some cases, but I'm somewhat leaning toward `--config`, and opening the door to allowing any of the _options_ to be specified within the file:

```
Usage: om [options] <command> [<args>]
  --client-id, -c, OM_CLIENT_ID          string  Client ID for the Ops Manager VM (not required for unauthenticated commands)
  --client-secret, -s, OM_CLIENT_SECRET  string  Client Secret for the Ops Manager VM (not required for unauthenticated commands)
  --connect-timeout, -o                  int     timeout in seconds to make TCP connections (default: 5)
  --format, -f                           string  Format to print as (options: table,json) (default: table)
  --password, -p, OM_PASSWORD            string  admin password for the Ops Manager VM (not required for unauthenticated commands)
  --request-timeout, -r                  int     timeout in seconds for HTTP requests to Ops Manager (default: 1800)
  --skip-ssl-validation, -k              bool    skip ssl certificate validation during http requests (default: false)
  --target, -t, OM_TARGET                string  location of the Ops Manager VM
  --trace, -tr                           bool    prints HTTP requests and response payloads
  --username, -u, OM_USERNAME            string  admin username for the Ops Manager VM (not required for unauthenticated commands)
```

> Since we are consuming now from the command line, the env vars, and env file, we should decide on a hierarchy schema.

I propose the following hierarchy:

1. `--flags` have the highest precedence
2. `ENV_VARS` take precedence over `--config` values, but are overridden by `--flags`
3. `--config` values have the lowest precedence

**Comment by anEXPer** [comment]
## On Naming
Given how much of `om` is dedicated to setting and retrieving config for various objects, I'm very reluctant to overload the name space. My preference would be to explicitly mirror `bosh`, and have a global `--env`/`-e` flag. I suspect we'll have less heartburn trying to disambiguate the concepts, long term - and less issues around flag ordering when there are multiple `-c` arguments.

## On Format
We currently have a data structure like this for internal auth:

```yaml
opsman_url: opsman.example.com
skip_ssl_validation: true
credentials:
  username: example-username
  password: example-password
decryption_passphrase: example-passphrase
```

and like this if you're using external/SAML auth:

```yaml
opsman_url: opsman.example.com
skip_ssl_validation: true
credentials:
  client_id: example-client-id
  client_secret: example-secret
decryption_passphrase: example-passphrase
```

I don't see any particular problem with using a "flag-name equals yaml key" schema instead; name-spacing `credentials` was driven by an unimportant implementation decision.

## On Preemption
flags > vars > files is traditional/conventional. I had some concerns, but in describing them, I determined I think we should just do what's conventional, here. Bye, three paragraphs of worrying!

**Comment by mcwumbly** [comment]
> My preference would be to explicitly mirror bosh, and have a global `--env`/`-e` flag.

OK, let's go with that.

> I don't see any particular problem with using a "flag-name equals yaml key" schema instead; 

👍  Cool, let's keep it simple and just do that... 

> I think we should just do what's conventional

👍 

adding `pr-welcome` now...

**Comment by nbconklin** [comment]
@mcwumbly yes, we have this issue in our tracker backlog.
