### ISSUE TITLE
create-vm-extension command is not idempotent

### ISSUE THREAD

**Issue by calebwashburn** [pivotal-cf/om#215]
Once you call create-vm-extension with a given name it cannot be called again to update that vm extension.

**Comment by genevieve** [comment]
Hey @calebwashburn!

What sort of updates do you want to make to the vm extension after you've created it?

**Comment by genevieve** [comment]
Ah, I see that if you use PUT instead of POST, you can do both create/update on the same endpoint: http://docs.pivotal.io/pivotalcf/2-2/opsman-api/#updating-or-creating-a-new-vm-extension

**Comment by calebwashburn** [comment]
Yes, this allows us to have this be a step in the pipeline that will ensure that vm_extension(s) exists without having to know current state which makes this more idempotent.

**Comment by calebwashburn** [comment]
This has been merged so closing this issue.
