### ISSUE TITLE
om configure-director --config config.yml should parse vm-extensions

### ISSUE THREAD

**Issue by genevieve** [pivotal-cf/om#224]
## Context

In our AWS environments, we need to create a BOSH [vm_extension](http://bosh.io/docs/cloud-config/#vm-extensions) to attach IAM roles to VMs. Currently we're making separate calls to `om create-vm-extension` in our [CI script](https://github.com/pivotal-cf/pcf-releng-ci/blob/5cec90d92141f5c78262976d6a013a4edb587a6f/tasks/configuration/configure-director/task.sh#L69-L81), but it would be nicer if we could specify a `vm_extensions` key in our director config file and pass that to `om configure-director -c FILE` to have a single declarative file we check into source control.

## A/C

**Given** my director config contains `vm_extensions: [{"name": "blobstore-reader", "cloud_properties": {"iam_instance_profile": "SOME_IAM_PROFILE"}}]`
**When** I run `om configure-director -c CONFIG_FILE`
**Then** My BOSH director now has a blobstore-reader vm_extension in its cloud config

---

**When** I run `om configure-director --vm-extensions '[{"name": "blobstore-reader", "cloud_properties": {"iam_instance_profile": "SOME_IAM_PROFILE"}}]'`
**Then** My BOSH director now has a blobstore-reader vm_extension in its cloud config

**Comment by mcwumbly** [comment]
@calebwashburn just wanted to make sure you saw this since you have opened a couple issues recently related to vm extensions.

**Comment by mcwumbly** [comment]
Cool. @genevieve / @rizwanreza or whomever, if you're planning to pick this up, just drop a note here to let others know first.

**Comment by calebwashburn** [comment]
@genevieve / @rizwanreza - Submitted PR for this

**Comment by fredwangwang** [comment]
merged
