### ISSUE TITLE
JSON format for curl and certificate-authorities commands

### ISSUE THREAD

**Issue by kieron-pivotal** [pivotal-cf/om#228]
In the master branch, we can no longer specify json format for `certificate-authorities` and `curl` commands. This previously worked and is used through our team's CI. Could it be reinstated please?

**Comment by mcwumbly** [comment]
Maybe we missed a couple commands while doing this work here: https://github.com/pivotal-cf/om/issues/210

At first glance, it _looks_ like we did this for `certificate-authorities` here though: https://github.com/pivotal-cf/om/commit/959d1065ed392731a74d9676ef1a80e6b4061f3b

We should definitely look into this and fix it... Adding PR welcome in case someone else can get to it first.

**Comment by genevieve** [comment]
@kieron-pivotal Hey Kieron, could you try moving the `--format=json` flag to _after_ the command instead of before it?

**Comment by kieron-pivotal** [comment]
Hi Genevieve,

Thanks. Putting the flag after certificate-authorities does indeed work.
Not for the curl command though. Are you looking at reimplementing the json
presenter for curl?

**Comment by genevieve** [comment]
I'm not sure if the curl commanded needed the `--format=json` parameter. It looks like it uses the content-type header to determine whether or not to print json - https://github.com/pivotal-cf/om/blob/master/commands/curl.go#L83-L91

**Comment by kieron-pivotal** [comment]
Thanks again. Yes the curl command is fine without the flag.

So, certificate-authorities is fine with -f json after the command, and curl is fine with -f json omitted. That means our problems are fixed.

Thanks for your help.

**Comment by mcwumbly** [comment]
@genevieve sorry I missed that before I brought this to your attention. I didn't check the actual command; I just tried `om certificate-authorities -h` and noticed there was no mention of the format flag. I created a separate issue for that here: https://github.com/pivotal-cf/om/issues/229
