### ISSUE TITLE
Revisiting the "small, sharp tool" design goal

### ISSUE THREAD

**Issue by mcwumbly** [pivotal-cf/om#237]
The current stated [design goals](https://github.com/pivotal-cf/om/blob/master/CONTRIBUTING.md#design-goals) may deserve a review / refresh:

> ## Design Goals
> 
> - a [small sharp tool](https://brandur.org/small-sharp-tools) for fast, reliable interaction with the Operations Manager API via the command line
> - enable humans easily interact with Operations Manager via the command line
> - enable scripts and continuous integration systmes to programmatically interact with Operations Manager
> - single binary that can be run on multiple platforms without additional dependencies
> - a consistent, tested code base that welcomes contributions from the community
> - idempotency for all commands
> 
> Maintaining _complete_ parity with the features that the Operations Manager API
> supports is _not_ an explicit design goal, but we welcome any ideas for new
> features that may become feasible as new features are made available in the API.

In particular, is `om` still a "small, sharp, tool"? It seems to have evolved to be more than that recently, and perhaps we should capture that more explicitly.

However / in addition, there _are_ a few other tools out there that consume `om` as a _library_ rather than a CLI. Some examples of this include [omen](https://github.com/pivotal-cloudops/omen) and [aqueduct-courier](https://github.com/pivotal-cf/aqueduct-courier).  Is there a boundary within `om` that best serves that purpose? Should that be called out in the design goals?

**Comment by anEXPer** [comment]
The only thing that stands out to me here as deserving of update is to say "in the command line, and especially in CI systems such as Concourse", honestly.

It _is_ pretty small and sharp comparatively - for instance, this design goal is part of what prevents us trying to put logic for managing the OM manager itself into the tool.

I'm not sure support of `om` as a library is something we should explicitly embrace/suggest, so much as passively enable. For one thing, it suggests we'd need to version both the lib and the cli. Good semver and the tooling to support it is an often-worthwhile engineering investment, but it's also a _substantial_ engineering investment.

**Comment by anEXPer** [comment]
So we're actually coming back to this and thinking shifting the design goals further might be a good idea. In particular, as we're working to understand how best to automate interactions with pivnet, it's increasingly seeming like consumption-side pivnet functionality could be useful. And the value of having the entire IaaS-specific vm-management side of things sequestered in the now-oddly-named `p-automator` is uncertain at best.

As we look at releasing our automation toolkit, 'pcf-automation', we have to decide what level of support, distribution, and official blessing to extend to the underlying tools. Right now, in our alpha, we've constrained things by focusing on the task level. We distribute and support concourse tasks, and an image that can run those concourse tasks. The fact that said image contains two to three Pivotal CLIs (om, credhub, pivnet, p-automator) to accomplish its work isn't that big a deal, though we have to do work with each of them to make them more ci-native in the way we've come to understand is critical to customers - taking configuration from inputs, not pipeline params.

When we end up in the next phase, where we're supporting/distributing the command line tools explicitly, the benefits of having fewer productized CLIs begin to look compelling.

What if all of p-automator's current vm-creation-and-management logic could be a "new ops manager" subcommand to `om`? (The `om nom` joke is great, but seriously, how great would that command be?)

What if the config files for products and ops managers could specify which artifact from pivnet would be used, as well as how it would be configured, and fetching those versions from pivnet didn't require going to a whole other `pivnet` cli with its own idioms? Especially considering that the bulk of the pivnet cli's functionality is only useful to people who _manage_ pivnet products. It would make possible things like a `--from-pivnet` flag on `upload-product`, for instance.

As we've rolled out our current approach, we've gotten feedback that has increased our understanding of how people want these things to fit together, and how people go about using and learning these tools. It's really pushed me towards thinking that pulling these other features into `om`, explicitly expanding its scope to the entire lifecycle-automation problems around Ops Manager, would be a really good solution. And if we can distribute, version, document, and support a smaller number of clis overall for the automation user, that seems like a win.

What do y'all think?

**Comment by mcwumbly** [comment]
> What do y'all think?

It's an interesting idea, but I think it might make sense to at least _consider_ approaching this problem a little differently.  

I can see the value in having a single CLI that meets the needs of the workflows that you want to enable, but perhaps neither `om` nor `pivnet` should simply grow into the CLI, but rather export the necessary library functions for this new uber-CLI to consume to serve those use cases.

The two approaches are not mutually exclusive: certain functionality that begins in the uber-CLI may rightfully be pushed down into any of the component library/CLIs.

Just thinking out loud really...

**Comment by fredwangwang** [comment]
Currently we are taking the approach of using `p-automator` to manage the lifecycle of OpsManager VM itself, but having `om` to take care of other things.

We are planning to add `download-product` into `om`, which allows to download the tiles and corresponding stemcells from pivnet. Clearly it starts to break the philosophy of **small sharp tool**, but on the other hand `om` can handle more stuff related to OpsMan daily operation.

So IMO, although a small, single-responsibility tool is very charming, as it is clear purposed and easily maintainable, it makes sense to make `om` a swiss knife
![71fhju17djl _sl1204_](https://user-images.githubusercontent.com/21690857/47312716-4c184780-d5fa-11e8-9ee2-c20470e27bf0.jpg)

**Comment by mcwumbly** [comment]
> So IMO, although a small, single-responsibility tool is very charming, as it is clear purposed and easily maintainable, it makes sense to make `om` a swiss knife

Perhaps it's worth addressing this question explicitly as well, given recent conversations (from the original post):

> However / in addition, there are a few other tools out there that consume om as a library rather than a CLI. Some examples of this include omen and aqueduct-courier. Is there a boundary within om that best serves that purpose? Should that be called out in the design goals?

I think some consideration should be given to the different (emergent) design pressures that stem from the "om as library" use case vs. the "om as ops manager swiss army knife".

**Comment by kcboyle** [comment]
Is there more we want to discuss here @mcwumbly @anEXPer , or are we good to close this issue for now? (given internal team conversations)?

**Comment by mcwumbly** [comment]
I don't feel strongly about this, as long as y'all feel like the design goals section of CONTRIBUTING.md communicates the intent well enough what you're looking for from contributors.

**Comment by kcboyle** [comment]
@jpmcb and I believe the design goals are sufficient for `om` at the moment. We'll close this issue for now, and reopen, or create a new issue in the future if necessary.
