### ISSUE TITLE
tile-metadata throws EOFs on many tiles

### ISSUE THREAD

**Issue by aegershman** [pivotal-cf/om#239]
`tile-metadata` throws `could not execute "tile-metadata": failed to decode metadata file: EOF` on a number of `*.pivotal` tiles

![screen shot 2018-08-24 at 8 27 03 am](https://user-images.githubusercontent.com/5619476/44587498-bb97c500-a778-11e8-841d-7f094a0af7c5.png)

Tiles where `tile-metadata` has thrown this exact same EOF error:
- pivotal-rabbitmq-service 1.12.8
- p-spring-cloud-services 2.0.1
- p-scheduler-for-pcf 1.2.0
- p-metrics-forwarder 1.11.2
- p-identity 1.7.0
- p-healthwatch 1.3.2
- pcf-metrics 1.4.6

Tiles where `tile-metadata` has worked successfully:
- elastic-runtime 2.2.4
- newrelic-broker 1.12.18
- p-redis 1.13.1
- pivotal-mysql 2.3.1

General notes:
- I'm able to reproduce this on my local machine
- In #234 it's noted that `Will fail if it's not a zip file, or if no metadata file is found.` The tiles downloaded are of `.pivotal` type and do contain metadata files (as far as I can tell).
- I haven't done any digging into _how_ these `.pivotal` tiles are different

Thanks for your consideration!

**Comment by mcwumbly** [comment]
> I haven't done any digging into how these .pivotal tiles are different

Does anything sticks out at you, if you unzip the `.pivotal` files and look in the `metadata/` directory to compare those that are working and those that are not?

**Comment by aegershman** [comment]
I'm going to do some digging this morning, will edit this comment with anything of note

**Comment by aegershman** [comment]
Not entirely sure _why_, but I do know that if you swap out [`metadata/.*`](https://github.com/pivotal-cf/om/blob/master/commands/tile_metadata.go#L44) to `metadata/.*yml`, the `tile-metadata` command works fine [in all use cases I've tested](https://github.com/aegershman/om/releases/tag/0.39.1)

**Comment by chendrix** [comment]
Yep seems reasonable.

**Comment by chendrix** [comment]
So i tried locally, and changing it to `regexp.MatchString("metadata/.+", f.Name)` also seems to work, and so does running a continue if `f.FileInfo().IsDir()`.

So it looks like it may be matching the `metadata/` directory and attempting to parse it.

**Comment by aegershman** [comment]
Fantastic, I appreciate it. I hope you'll consider a `0.39.1` release 😉

Thanks again
