### ISSUE TITLE
om relationship to p-automator (if any?)

### ISSUE THREAD

**Issue by aegershman** [pivotal-cf/om#241]
As an operator trying to keep our PCF automation as clean & powerful as possible, I like to stay up-to-date on the OSS tools available to me.

[That's why the `pivotal-cf/platform-automation` docs repo caught my eye](https://github.com/pivotal-cf/docs-platform-automation/blob/master/command-reference.html.md.erb#L57). I'm noticing the UX workflows for this mystery `p-automator` binary appear very similar to `om` 🤔 I'm assuming there's a close connection?

Perhaps it's top secret and you cannot share, but I would love to hear more about these `cf-platform-automation` && `p-automator` projects.

**Comment by ljfranklin** [comment]
cc @jtarchie @calebwashburn from the pcf-automation team

**Comment by aegershman** [comment]
If necessary, we can close this. Our Pivotal contact is Paul Hopper. We have a meeting setup with the Platform Automation team on Monday, Sept. 10th.

**Comment by jtarchie** [comment]
I'll that will be in the conversation with the team. Please feel free to close this issue.
