### ISSUE TITLE
features for tile-metadata

### ISSUE THREAD

**Issue by fredwangwang** [pivotal-cf/om#243]
Currently `tile-metadata` supports returning product-name and version of the tile, which would be useful in combination with `stage-product` command. There is more information provided in tile metadata that would be useful for other purposes, for example:

1. stemcell information (stemcell_criteria)
  Would be useful to figure out what stemcell is required to download for the given tile

2. dependency information (requires_product_versions)
  p-healthwatch for example, depends on a specific version of cf. Would be useful as well.

It's probably interesting to add those features to tile-metadata as well.

**Comment by kcboyle** [comment]
@fredwangwang feel free to submit a PR for this if it's blocking y'all

**Comment by fredwangwang** [comment]
No, it does not block anything currently, it's something would potentially be useful to someone.

Closing this for now, if someone needs it, feel free to reopen
