### ISSUE TITLE
Add configure-saml-authentication config file support

### ISSUE THREAD

**Issue by kcboyle** [pivotal-cf/om#249]
Story to unwrap configure-saml-authentication

Currently, we have a wrapper around configure-authentication to allow the configurations to be passed in using --config config.yml. Would like to merge that behavior into om.

Proposed changes:
adding a --config flag which takes configuration file for auth.

File format: replicate flat flag structure
example:

idp-metadata
bosh-idp-metadata
rbac-admin-group
rbac-groups-attribute
http-proxy-url:
https-proxy-url:
no-proxy:
decryption-passphrase:

**Comment by fredwangwang** [comment]
Closing this, as the PR is already merged in this commit: https://github.com/pivotal-cf/om/pull/252/commits/c14dc24b30cd319327166e124c8402bcb10698f2
