### ISSUE TITLE
Allow the product_name to be read in from the config file in configure-product

### ISSUE THREAD

**Issue by kcboyle** [pivotal-cf/om#250]
Story to unwrap configure-saml-authentication

Currently, we have a wrapper around configure-product to allow config file to contain the product name using --config config.yml. Would like to merge that behavior into om.

Proposed changes:
add the ability to read the `product-name` from a provided `--config` file if the field is present

Intended behavior:
`--product-name` will always set the product name

configFile.yml:
```
product_name: ((product_name))
```
will set the product name if the flag is not set

**Comment by ljfranklin** [comment]
Just to make sure, the plan is to leave the existing `--product-name` flag as it but make it optional in which case the file passed via `--config` should contain a `product_name` key. Else raise an error. Does that sound right?

Also question about naming consistency. Looks like all our existing config keys use a hyphen: https://github.com/pivotal-cf/om/blob/master/config/config.go. Should `product_name` be changed to `product-name` or should we move more towards underscores to have more idiomatic YAML?

**Comment by fredwangwang** [comment]
Yes. This is exactly what we were thinking. 

And yes, we will name the key `product-name` instead of `product_name` for consistency.

**Comment by jtarchie** [comment]
merged
