### ISSUE TITLE
Extract and share CI

### ISSUE THREAD

**Issue by chendrix** [pivotal-cf/om#255]
The @pcf-platform-automation and @pivotal-cf/pcf-release-engineering teams met up to discuss how we want to share ownership of `om` in the future.

One of the things that needs to happen is to share CI, both the code (pipelines, tasks, docker images) and the CI environment itself.

After discussion, we added a new `om` team to https://releng.ci.cf-app.com and gave access to both teams.

We also came up with a few action items and a few things to explore:

- [x] Move unit testing to `om` team
- [x] Move unit testing code from pcf-releng-ci to a folder in om, e.g. `om/.ci` or `om/ci`
- [x] Explore how to move functional/acceptance testing from each of our current CI
  * Look into local ops managers (PCF Automation Team)
  * Look into toolsmiths GCP pooled environments (PCF Releng)
  * Look into toolsmiths prepared vSphere environments (PCF Releng)

**Comment by chendrix** [comment]
The @pivotal-cf/pcf-release-engineering team looked into using toolsmiths environments, and found this out:

* GCP pooled environments are an option, and we could follow [this doc](https://docs.google.com/document/d/1afCL7hgFeQ61orx6Z5bP49xauE753n5eSZPuO5bWJeY/edit) to get a worker and have access to the concourse resource. **However**, because this pooled environment already comes with an installed OpsManager, we wouldn't be able to test our Ops Manager configuring authentication paths in `om`
* Custom vSphere environment is also an option, we would just ask the toolsmiths team to reserve one for us, and they give us the environment name and subnet to use when creating the environments. The biggest con is that we'd only be testing on vSphere? And that the tooling for deploying ops manager onto vSphere is iffy ([`rake opsmgr:install`](https://github.com/pivotal-cf/opsmgr) or an experimental [`terraforming-vsphere`](https://github.com/pivotal-cf/terraforming-vsphere)?)

**Comment by fredwangwang** [comment]
The @pivotal-cf/pcf-platform-automation team took a brief look at the local Opsman option. In order to do that, we need to have a virtual box setup in the ci worker so that the ci can talk to. And each time we start the ci task a new virtual box installation needs to be done, which feels like overkill. This would also take a very long time.

**Comment by anEXPer** [comment]
> ... the tooling for deploying ops manager onto vSphere is iffy...

Our (alpha) commercial product has a tool for that which works pretty reliably (`p-automator create-vm`).

**Comment by fredwangwang** [comment]
@chendrix 
> GCP pooled environments are an option

as you said if we are using this option we cannot cover configure-authentication. Although that's generally not a problem as we have iaas-specific ci to cover that part everyday, it is bad for visibility for both teams.

> Custom vSphere environment is also an option

this would work for us. using `terraforming-vsphere` to pave the infrastructure together with our tool to create vm would not be that hard to set up. 

> The biggest con is that we'd only be testing on vSphere?

even if we are using GCP, we are only testing one IAAS right? Is there any preference of testing on gcp over vsphere?

> Create a new GCP account that's shared 

also works, I don't think personally I have any preference in between vsphere or shared gcp. The only difference is that we get an env from ask or toolsmith.

**Comment by ljfranklin** [comment]
@fredwangwang general rule of thumb at Pivotal is all new projects use GCP as our vSphere environments are severely limited hardware-wise. Unless we are testing vSphere-specific functionality in the `om` pipeline, we should probably be using GCP. As `om` is just a thin wrapper around the OpsMgr API I don't think we need to concern ourselves with testing multi IaaS in CI.

**Comment by fredwangwang** [comment]
@ljfranklin I didn't know that... seems like gcp would be a better fit then.

**Comment by chendrix** [comment]
We've moved over the unit testing and are trying our hand at moving over the PR testing. It is currently failing, maybe because we cannot use the pullrequest resource with a deploy key?

Still open questions on what to do re acceptance testing.

**Comment by jtarchie** [comment]
I'll look into it. I am fairly sure a deploy key can be used.

**Comment by jtarchie** [comment]
You're absolutely right! The deploy keys are the SSH keys for a specific repo, not an access token for a specific repo. I messed that up, because I totally forgot about it. 😢 

You do need to create an access token.

It needs to have `repo` and `repo:status` permissions. Those are documented there.

Sorry for the delay.
