### ISSUE TITLE
Om should be able to hit the opsman `variables` endpoint. 

### ISSUE THREAD

**Issue by joshzarrabi** [pivotal-cf/om#259]
We want to grab a credhub generated variable from our tile, which we had to do by hitting the following endpoint directly:`api/v0/deployed/products/product-guid/variables?name=our-variable`. We believe that there should be an `om` command to get this for us, something like: `om variable -v our-variable` which will return `some-value`.    

We believe this will be useful in the use case of our tile, which relies on credhub exclusively for credential generation. For example, we generate UAA credentials to log into a concourse instance, but, because we made those bosh variables instead of opsman credentials, we can not easily access them. Our current workflow is either to ssh onto the opsman and use the credhub cli from there, or to use `om curl` to get the product-guid and then `om curl` again to grab the variable. We want to use credhub directly instead of opsman variables because we want to quickly and easily generate a bosh deployable manifest from the tile manifest.

Because there is first class support for this in the opsman api we believe `om` should support it. 

Thank you! --
@ciriarte @joshzarrabi

**Comment by fredwangwang** [comment]
There is an existing command in `om` called `credentials` which basically does the same thing but targets the different endpoint. So follow the pattern of that command is probably a good idea:
```bash
om credentials --help
......
Command Arguments:
  --credential-field, -f      string             single credential field to output
  --credential-reference, -c  string (required)  name of credential reference
  --format, -t                string             Format to print as (options: table,json) (default: table)
  --product-name, -p          string (required)  name of deployed product
```

which can be executed as `om credentials -p product -c some.field -f private_key_pem`

So a similar command for `variables` would be nice.

**Comment by joshzarrabi** [comment]
We will work on a p-r for this, thanks!

**Comment by kcboyle** [comment]
@joshzarrabi how is the PR for this coming? Is this feature still something you would find useful?

**Comment by joshzarrabi** [comment]
Ahh sorry I totally dropped this on the ground. I think `om bosh-env` basically solves this issue anyway.

**Comment by kcboyle** [comment]
@joshzarrabi is it ok to close this issue then? or are you still wanting to solve this in an `om variables` way?

**Comment by joshzarrabi** [comment]
I rolled off of the project that wanted this, @nmahoney-pivotal would this still be useful to get the concourse login creds?

**Comment by nmahoney-pivotal** [comment]
Yeah I think `om bosh-env` works. We'll open another issue/PR if it doesn't cover some use case.

**Comment by kcboyle** [comment]
Good deal. Feel free to open another issue in the future.

**Comment by mcwumbly** [comment]
We have a use case where this feature would be valuable. for installing our product on PKS, we require getting a variable and currently have it documented as such:

```
product_guid="$(om curl --path /api/v0/deployed/products \
  | jq '.[] | select(.type=="pivotal-container-service").guid' -r)"
 
om curl \
  --path /api/v0/deployed/products/$product_guid/variables?name=kubo_odb_ca_2018 \
  | jq -r .kubo_odb_ca_2018.ca > /tmp/kubo_odb_ca.crt
 
om curl \
  --path /api/v0/deployed/products/$product_guid/variables?name=kubo_odb_ca_2018 \
  | jq -r .kubo_odb_ca_2018.private_key > /tmp/kubo_odb_ca.key
```

I believe with this command we could simplify our installation insructions for this step to retrieve the variables with:

```
om variables -p pivotal-container-service \
  -c .kubo_odb_ca_2018 -f ca > /tmp/kubo_odb_ca.crt
om variables -p pivotal-container-service \
  -c .kubo_odb_ca_2018 -f private_key > /tmp/kubo_odb_ca.key

```

Could we re-open this issue?

**Comment by mcwumbly** [comment]
Just learned there's a separate issue that is still open which covers this need: https://github.com/pivotal-cf/om/issues/382 Moving my comment above over there...
