### ISSUE TITLE
Bosh Director AZ configuration for vSphere requires additional fields.

### ISSUE THREAD

**Issue by malston** [pivotal-cf/om#26]
vSphere requires the following fields to be filled in:

availability_zones[availability_zones][][name]
availability_zones[availability_zones][][cluster]
availability_zones[availability_zones][][resource_pool]

Where other IaaS that OM supports only uses the following field for AZ:

availability_zones[availability_zones][][iaas_identifier]

**Comment by ryanmoran** [comment]
This will be resolved in these stories:
- https://www.pivotaltracker.com/story/show/136967791
- https://www.pivotaltracker.com/story/show/136633283
