### ISSUE TITLE
make retries configurable

### ISSUE THREAD

**Issue by jtarchie** [pivotal-cf/om#266]
Retries seem to have solved an issue, as I've not heard about the upload being an issue anymore.

It has also enabled a longer feedback loop.

I'd like to introduce `--retry-count` and `--retry-delay` so these can be tweaked for CI systems.

/cc: @ljfranklin

**Comment by ljfranklin** [comment]
Sounds reasonable, adding the `pr welcome` label

**Comment by mcwumbly** [comment]
just a thought to consider... maybe instead of adding a flag for `--retry-delay` it's all driven by `--retry-count` which could just include some kind of explonential backoff between retries?

**Comment by fredwangwang** [comment]
@ljfranklin since retry client is not working properly, do we want to remove it altogether and consider adding it back later if we really need it?

**Comment by ljfranklin** [comment]
We'll hopefully take another pass at it this week, but if you want to revert that commit now that's fine.

**Comment by fredwangwang** [comment]
Would keep it then

**Comment by fredwangwang** [comment]
retry client removed from the code base, closing
