### ISSUE TITLE
Curl service does not allow clients to close the response body

### ISSUE THREAD

**Issue by zmb3** [pivotal-cf/om#269]
## The Problem

The curl service returns an output struct containing an `io.Reader` which is the HTTP response body.

Since the body is passed as a reader, there is no [easy] way to close it.  It's important to close response bodies in Go for two reasons:

1. If not closed, the file descriptor leaks.
2. The HTTP client cannot reuse the connection for subsequent requests.

This is not a major issue in `om` itself, as most commands make a single API call.  However, there are some commands that make multiple API calls that could reuse the same TLS connection if the API allowed them to do so, and there are some tools which vendor code from `om` that make many calls in the same process.

## Solutions

The simplest solution would be to change the `Body` field of `RequestServiceCurlOutput` to an `io.ReadCloser`, exposing the `Close` method to clients.

A nicer solution might be to remove the body from the curl output entirely, and instead accept it as an interface.  For example:

```
// Curl makes an arbitrary request of the API, and optionally unmarshals the
// response body into result.
func (a Api) Curl(input RequestServiceCurlInput, result interface{}) (RequestServiceCurlOutput, error)
```

With this API, callers don't even need to know that `pkg http` is in use underneath and don't have to worry about the details of closing response bodies.  They can still make use of the response body by either passing in a pointer to a struct to fill out (ie `api.Curl(input, &result)`), or by passing in a `json.RawMessage` to receive the body as a standard `[]byte`.

Happy to throw a PR out there to address this.

**Comment by jtarchie** [comment]
Are you experiencing an issue with this? Or have you seen an error?

**Comment by fredwangwang** [comment]
Hi @zmb3, with this commit 87ce807, do you still experience any issues about `curl`?

**Comment by zmb3** [comment]
That works - though I’d recommend documenting that the caller must close the body because we’ve pushed that responsibility out.

**Comment by jtarchie** [comment]
@zmb3, I don't know if `om` has made an official contract to be a library and a CLI. Its intention has been a CLI for awhile.

Where you are using `om` as a library where _documenting_ this would be obvious?

**Comment by zmb3** [comment]
Ah, in the godoc for `api.Curl`.  Kind of like how Go's http package does:

```
➜ go doc http.Client.Do
func (c *Client) Do(req *Request) (*Response, error)
    Do sends an HTTP request and returns an HTTP response, following policy
    (such as redirects, cookies, auth) as configured on the client.

    ...

    If the returned error is nil, the Response will contain a non-nil Body which
    the user is expected to close. If the Body is not closed, the Client's
    underlying RoundTripper (typically Transport) may not be able to re-use a
    persistent TCP connection to the server for a subsequent "keep-alive"
    request.
```

**Comment by kcboyle** [comment]
Closing this issue due to age and no recent commentation.

If you still feel this is an issue and would like to reopen, please feel free to reopen this issue.
