### ISSUE TITLE
add config file support for upload-product

### ISSUE THREAD

**Issue by fredwangwang** [pivotal-cf/om#270]
related to our unwrapping story: https://www.pivotaltracker.com/story/show/160566798

currently `p-automator upload-product` allows a flag `-c` to accept a file containing optional shasum & version validation. 
There are existing patterns in `om` that we can supply any supported commandline flag through the config file, we would like to extend that behavior to `upload-product` as well.

Sample config file:
```yaml
shasum:
version: 
polling-interval:
product:
```

@mcwumbly Also, I want to discuss the flag name `shasum`. It does not indicate which sha version we are using, probably rename it to sha2 makes more sense?

**Comment by mcwumbly** [comment]
> Also, I want to discuss the flag name shasum. It does not indicate which sha version we are using, probably rename it to sha2 makes more sense?

do we expect that algorithm to change or are multiple algorithms supported? maybe something like this?

```
shasum:
  algorithm:
  value:
```

**Comment by fredwangwang** [comment]
Currently only one sha check is implemented, that is sha256. It is the checksum provided on pivnet, which is also the reason we chose this particular algorithm (so people don't have to calculate them own).
So in regarding multiple algorithms, maybe? I can see a use case for supporting other algorithms (e.g. md5, as it is cheaper), so it's your call.

But for the file structure, I would oppose having a nested object, what about flatten them out? As the config file is just a mirror of the cmd flags. If we add md5 for example, it would like:

```bash
$ om upload-product -h
......
--md5 string optional md5 validation of the file
```

and the config file
```yaml
md5: <checksum here>
```
![screen shot 2018-10-05 at 1 38 42 pm](https://user-images.githubusercontent.com/21690857/46556500-165a2b80-c8a4-11e8-9b63-a5f5884d4ac4.png)

**Comment by mcwumbly** [comment]
in that case I propose we:

1. change the current flag from `--shasum` to `--sha256` and drop the short name.
2. use `sha256:` as the key in the config file.

no better time than now to make breaking changes, imho.

**Comment by fredwangwang** [comment]
doing it!
