### ISSUE TITLE
Error when configuring product collection that does not contain a "name" property

### ISSUE THREAD

**Issue by acrmp** [pivotal-cf/om#274]
As of this commit: https://github.com/pivotal-cf/om/commit/d61ff351a1d662068cdccb7aeaa1659ae0692877

We are now getting the following error:
```
could not execute "configure-product": 
failed to configure product: element map[REDACTED_COLLECTION_PROPERTIES] 
with key name is not a string
```

It seems like the code assumes all collections contain a `name` property blueprint.

CC @jpalermo

**Comment by jtarchie** [comment]
The code added in d61ff351a1d662068cdccb7aeaa1659ae0692877 assumes that collections always have a `name` property. The idea was that `name` could be tied back to the `guid` based on the uniqueness of the element in the collection.

This is bad assumption. As @acrmp experienced.

There are collections that don't have elements with the `name` property and they explode.

We should probably revert this change. And update `stage-config` to include the `guid` property and not [filter it out](https://github.com/pivotal-cf/om/blob/master/configparser/configparser.go#L80-L85).

This means for product configurations, like `p-mysql`, the collections will have to explicitly define `guid` if they need to ensure their continued uniqueness and existence between `configure-product`.

**Comment by kcboyle** [comment]
We've been discussing. The path forward is going to be.

1. Reverting this feature/commit (d61ff35)
2. Document that if a collection requires persistence (such as a Service Plan definition) the `guid` is required or you are going to have a bad day.
3. Return the `guid` always when using `staged-config` for collections. We are going to confirm if other properties get guids, too to decide if there is further action for those `guid`s too.

**Comment by jtarchie** [comment]
@acrmp and @jpalermo, we might have a fix for the issue above on fcdd32e7dfb45dec5219fb8b3404f2246b58cbf7. Are you able to try it out and see if it resolves your issue?

**Comment by kcboyle** [comment]
@acrmp @jpalermo Just doing a gentle nudge/follow-up to test if your issue is fixed. Please let us know!

**Comment by acrmp** [comment]
It seems to have fixed the issue for our usage. Thanks.
