### ISSUE TITLE
`tile-metadata` should probably be `product-metadata`

### ISSUE THREAD

**Issue by anEXPer** [pivotal-cf/om#275]
The `tile-metadata` command is the only place in om we refer to products as tiles. It even takes a `--product-path`!

We should rename it, but this would be a breaking change.

**Comment by patrick-huber-pivotal** [comment]
You could add an alias, and mark it as deprecated then remove it in a future release.

**Comment by kcboyle** [comment]
Thanks for the PR @jghiloni !
