### ISSUE TITLE
go mod

### ISSUE THREAD

**Issue by fredwangwang** [pivotal-cf/om#277]
Do we want to use vgo?

**Comment by patrick-huber-pivotal** [comment]
Looks like you just need to update the go version to 1.11 to take advantage of modules

https://github.com/golang/go/wiki/Modules#quick-start-example


> Go 1.11 includes preliminary support for versioned modules as proposed here. Modules are an experimental opt-in feature in Go 1.11, with the hope of incorporating feedback and finalizing the feature for Go 1.12. Even though the details may change, future releases will support modules defined using **Go 1.11** or **vgo**.

> The recent work by the Go team on versioned modules started outside of the main Go repository with the vgo tool, but on July 12, 2018 support for versioned modules landed in the main repository (announcement thread), and Go 1.11 was released on August 24, 2018.

**Comment by zachgersh** [comment]
cc @jtarchie - we can close this now.
