### ISSUE TITLE
add command `associate-stemcell`

### ISSUE THREAD

**Issue by fredwangwang** [pivotal-cf/om#281]
If `upload-stemcell --floating=false` is used, currently there is no easy way to associate the stemcell with the product.

So it would be nice to have the command `associate-stemcell` added to `om`.

### proposed command & arguments:
```bash
$ om associate-stemcell --help
......
Command Arguments:
--product                     string   product-name to associate
--stemcell                    string   stemcell version to associate
--latest-available-stemcell  bool      using the latest available stemcell, cannot be used together with --stemcell flag
```

usage 1:
```bash
$ om associate-stemcell --product cf --stemcell 3586.48
```

usage 2:
```bash
$ om associate-stemcell --product cf --latest-available-stemcell
```

### How it works internally:
1. It will get the information from `/api/v0/stemcell_assignments`,
sample payload:
```json
{  
   "products":[  
      {  
         "guid":"p-bosh-43f13ae44d5ee47d9255",
         "identifier":"p-bosh",
         "label":"BOSH Director",
         "staged_product_version":"2.2-build.352",
         "deployed_product_version":"2.2-build.352",
         "is_staged_for_deletion":false,
         "staged_stemcell_version":"3586.43",
         "deployed_stemcell_version":"3586.43",
         "available_stemcell_versions":[  
            "3586.48"
         ],
         "required_stemcell_version":"3586.48",
         "required_stemcell_os":"ubuntu-trusty"
      },
      {  
         "guid":"cf-7dd32401fc52ea0c5c2b",
         "identifier":"cf",
         "label":"Pivotal Application Service",
         "staged_product_version":"2.2.8",
         "deployed_product_version":"2.2.8",
         "is_staged_for_deletion":false,
         "staged_stemcell_version":"3586.46",
         "deployed_stemcell_version":"3586.46",
         "available_stemcell_versions":[  
            "3586.46",
            "3586.48"
         ],
         "required_stemcell_version":"3586.46",
         "required_stemcell_os":"ubuntu-trusty"
      }
   ]
}
```

2. try to associate the stemcell with the product using `PATCH /api/v0/stemcell_assignments`, 
sample payload:
```bash
curl "https://example.com/api/v0/stemcell_assignments" \
    -X PATCH \
    -H "Authorization: Bearer UAA_ACCESS_TOKEN" \
    -H "Content-Type: application/json" \
    -d '{
        "products": [
          {
            "guid":"product_template_for-product-1-b53ab52cd2c084ebcf6f",
            "staged_stemcell_version": "1.3"
          }
        ]
      }'
```

**Comment by anEXPer** [comment]
I like the idea, but I've got two ideas for reducing the config complexity:
1. `--stemcell` can take `latest` as an argument. This matches the behavior of bosh manifests and eliminates the need for `--latest-available-stemcell`.
2. `latest` (in either form) is the default behavior. Presumably, if you've uploaded a newer compatible stemcell with `float: false`, and now you're saying "associate a stemcell with this product, please", you usually/always(?) want the most recent compatible stemcell available. And you can still override it by specifying `--stemcell` if you want.

I mildly prefer 2.

**Comment by mcwumbly** [comment]
given the endpoint name
```
curl "https://example.com/api/v0/stemcell_assignments"
```

what do you think about using the command name `assign-stemcell` instead of `associate-stemcell`?

**Comment by fredwangwang** [comment]
nothing particularly, I got the command name from here: http://docs.pivotal.io/pivotalcf/2-2/opsman-api/#associate-stemcells-to-products

**Comment by kcboyle** [comment]
Do we want to care if a product to-be-stemcell-assigned is a new product, existing product, or a product marked for deletion? (put another way, should we fail out fast if you try to associate a stemcell with a product marked for deletion)

Perhaps this is a non-issue, as when you get the response back when the product is staged for deletion, you get:
```
{
      "guid": "p-healthwatch-kjdsrf",
      "identifier": "p-healthwatch",
      "label": "PCF Healthwatch",
      "staged_product_version": null,
      "deployed_product_version": "1.3.2-build.9",
      "is_staged_for_deletion": true,
      "staged_stemcell_version": null,
      "deployed_stemcell_version": "3541.48",
      "available_stemcell_versions": [],
      "required_stemcell_version": null,
      "required_stemcell_os": null
    }
```
The benefit of checking for `is_staged_for_deletion` is that we could have more intelligent error messages. So we'll likely implement that way unless there is someone opposed.

**Comment by kcboyle** [comment]
Closing as this is implemented by the above merge.
