### ISSUE TITLE
feature request - "latest" release option

### ISSUE THREAD

**Issue by drduker** [pivotal-cf/om#284]
It would be nice if pivnet and om-linux command tools had the option to pass “latest” to --product-version or the -r for the release version.  Otherwise we have to search for all versions and head -n1 and then continue.

This would be applied here: 
pivnet release-dependencies -p ${PRODUCT_NAME} -r **latest**

**AND** everywhere else the "release"/"-r" parameter is used.

Current simplest way I know to get the latest version of a tile:
`p=apm;pivnet rs -p $p --format json|jq -r ‘.[]|.version’|head -n 1`

Feature request example would make simplest command be:
` p=apm;pivnet r -r latest -p $p`

**Comment by fredwangwang** [comment]
which om command in particular? 

And for pivnet-cli params, probably it's better to open an issue at pivnet-cli repo to have a broader discussion. We do not maintain pivnet-cli.

**Comment by drduker** [comment]
Ok, but I'm asking for the same type of feature with om.  I didn't open it on pivnet-cli because i think om is the future!

**Comment by fredwangwang** [comment]
..ok, but which command in question?

**Comment by drduker** [comment]
om download-product --stemcell-iaas --download-stemcell <<LATEST>>

is this already the default action?  
It certainly isn't the case with pivnet

**Comment by jtarchie** [comment]
With the `product-version-regex` you can specify `.*`, which will pull down the latest version of the product. `om download-product` uses the same logic for semver sorting that `pivnet-cli` uses.

Closing as we've released this feature now. :-)

**Comment by drduker** [comment]
Sweet!  Thanks!
