### ISSUE TITLE
feature request - om download-product --accept-eula

### ISSUE THREAD

**Issue by drduker** [pivotal-cf/om#285]
Feature request - om download-product --accept-eula
Please add the "--accept-eula" parameter to the download-product options.

pivnet cli has this implemented:
pivnet-cli download-product-files -p "$product_slug" -r $STEMCELL_VERSION -g "*${IAAS}*" --accept-eula

by the way the pivnet-resouce (https://github.com/pivotal-cf/pivnet-resource) never had this option even though it could be scripted manually with pivnet-cli like what is used in pcf-pipelines.

But if you add this feature to om, we will no longer need to use pivnet-resource, just the platform-automation image (rc248+) would be fine.

**Comment by jtarchie** [comment]
@drduker, I believe this feature is only available for Pivotal employees. This is why it was not added initially, as non-Pivotal users would be confused by its usage.

**Comment by aegershman** [comment]
(https://github.com/pivotal-cf/pivnet-resource/issues/74#issuecomment-302082241)

**Comment by jtarchie** [comment]
I'm going to close this based on the verification of the Pivnet team.
