### ISSUE TITLE
Feature Request - om should return error messages when a product manifest cannot be generated

### ISSUE THREAD

**Issue by crhino** [pivotal-cf/om#287]
We ran into a situation where our tile was not fully configured (missing the stemcell version), and had trouble diagnosing the problem using `om staged-manifest -p pivotal-mysql` because it just returned null and exited successfully.

Looking at the OpsMan api `/api/v0/staged/products/pivotal-mysql-307620e03012f3c2619e/manifest`, we saw a much better error message:
```
 {"errors":{"base":["Product configuration is incomplete; cannot generate manifest"]}}
```
but returns a 200 error code for the http request

Ideally, we would see something like:
```
$ om staged-manifest -p pivotal-mysql
error: Product configuration is incomplete; cannot generate manifest
$ echo $?
1
```

**Comment by jtarchie** [comment]
At the moment, those errors are generated by OpsManager. We don't have definitie way of doing the same from `staged-config` command as we'd be require to duplicate the validation login in `om`.

Are you able to document the values that were incorrect? Maybe the `staged-config` just needs to do more work at extracting the config.

**Comment by kcboyle** [comment]
@crhino This change in better error messaging seems like it would be good for the product. Feel free to submit a PR (apologies for the delay)

**Comment by kcboyle** [comment]
@crhino 

We did not implement the change you requested to `staged-manifest`, but we did add a new command for the Ops Manager 2.6+ API (`pre-deploy-check`) that will return an organized list of errors like so if run:
```
go run main.go --env /Users/pivotal/workspace/platform-automation-deployments/platform-automation/gcp/env/env.yml pre-deploy-check
go: finding github.com/cloudfoundry/bosh-cli v5.5.0+incompatible
go: downloading github.com/cloudfoundry/bosh-cli v5.5.0+incompatible
go: extracting github.com/cloudfoundry/bosh-cli v5.5.0+incompatible
Scanning OpsManager now ...

[X] director: p-bosh-41e836276c754094cdb1
    Error: Network is not assigned

    Error: Availability Zone is not assigned

    Error: verifier: AvailabilityZonesVerifier
    Why: IaaS default: Cannot find availability zone 'us-east-1', type: AvailabilityZonesVerifier

[X] product: p-event-alerts-131b5f3d7a54accac935
    Error: Network is not assigned

    Error: Availability Zone is not assigned

    Error: missing stemcell
    Why: Required stemcell OS: ubuntu-xenial version 97.34
    Fix: Download ubuntu-xenial version 97.34 from Pivnet and upload to OpsManager

    Error: property: .properties.mysql.internal.plan_name
    Why: can't be blank

    Error: property: .properties.smtp_selector.enabled.smtp_from
    Why: can't be blank

could not execute "pre-deploy-check": OpsManager is not fully configured
exit status 1
```

Could you explain your use case for `staged-manifest` a little better for the team? We highly encourage using `staged-config` for the manifest in Ops Manager, or `config-template` if you would like to get/edit the configuration before touching your Ops Manager. both commands do not fail when you pull down an config, but `pre-deploy-check` would allow you to see a list of all errors after you have run `configure-product`

However, if neither of these commands work for you, we'd like to understand how you and your team use `staged-manifest`.

**Comment by kcboyle** [comment]
Hi @crhino @sethboyles

Friendly reminder to keep this conversation alive and fresh! ^^

**Comment by kcboyle** [comment]
Hi there! 👋  
It's been a while since we have had any response.
Given that we did add a new command that we _think_ would be a solution, I am going to close this issue. If `pre-deploy-check` or `config-template` doesn't work for you, please let us know and reopen this issue with a little more context and/or a use case for `staged-manifest`
@crhino @sethboyles
