### ISSUE TITLE
Validate that unknown top-level for keys are treated as errors

### ISSUE THREAD

**Issue by fredwangwang** [pivotal-cf/om#288]
Right now, if you pass unknown top level keys, we don't do anything with them, and this causes issues with users who think they have the right keys and do not. 
For Example:
```
iaas_configuration:
  some-key: value
```

would not return an error, but wouldn't configure anything. `om` needs this key to be:
```
iaas-configuration:
  some-key: value
```

The fix for this will strictly enforce top-level OpsManger configuration keys.

**Comment by kcboyle** [comment]
The above commit solves this issue.
