### ISSUE TITLE
`configure-bosh` does not report missing fields

### ISSUE THREAD

**Issue by asehra** [pivotal-cf/om#29]
When configuring bosh, if the payload is incomplete for any section, then `om configure-bosh` completes without error, even though ops manager rejects incomplete payloads. 

Example: Configure OpsMan on AWS with following (incomplete) iaas-config:

```js
// iaas-config.json -> example config without ssh-private-key in payload
{
  "access_key_id": "VALID_AWS_KEY",
  "secret_access_key": "VALID_AWS_SECRET_KEY"
  "vpc_id": "vpc-5678329",
  "security_group": "sg-13975328",
  "key_pair_name": "mykey",
  "region": "eu-west-1",
  "encryption": false
}
```

```bash
$ om -t https://opsman.example.com -u user -p pass -k configure-bosh -i "$(cat iaas-config.json)"
# produces => 
configuring iaas specific options for bosh tile
finished configuring bosh tile
# with exit code 0
```

This might be happening because when Ops Manager does not like the input config, it renders the `/infrastructure/iaas_configuration/edit` page with status code 200, but reports errors as flash messages. `om` sees 200 and assumes everything is OK. This however makes it difficult to use `om` in a script where the outcome of `om configure-bosh` is useful to determine next steps in the script.

**Comment by ryanmoran** [comment]
@asehra we are aware that this is an issue. We are working with the OpsMan team to try to get a response from OpsMan that makes more sense and provides sane responses with inputs are invalid. I am going to close this as it is not really an issue with `om`, but more a problem with OpsMan.
