### ISSUE TITLE
Feature Request: eval "$(om bosh-env)"

### ISSUE THREAD

**Issue by genevieve** [pivotal-cf/om#290]
Hey there! 

I'm working on the setup for a test suite that reminds me of `eval "$(bbl print-env)"` but `eval "$(om bosh-env)"`. 

It would curl for the bosh command line creds, get the bosh ca cert, create a local tmp file for the cert to point BOSH_CA_CERT at, and then export BOSH_ALL_PROXY. It could also just create a config file that you pass to the bosh cli with the `--config` file if it supports bosh_all_proxy.

Is this something you would consider adding to the om cli? 

```go
		// Get $BOSH_CLIENT, $BOSH_CLIENT_SECRET, $BOSH_ENVIRONMENT
		output, err := om.Curl(api.RequestServiceCurlInput{
			Path:   "/api/v0/deployed/director/credentials/bosh_commandline_credentials",
			Method: "GET",
		})
		Expect(err).NotTo(HaveOccurred())

		// Decode the response body
		var creds CredentialOutput
		err = json.NewDecoder(output.Body).Decode(&creds)
		Expect(err).NotTo(HaveOccurred())

		// Export the bosh commandline credentials
		Expect(creds.Credential).To(ContainSubstring("BOSH_ENVIRONMENT=10.0.0.5 bosh"))
		kvs := strings.Split(creds.Credential, " ")
		for _, kv := range kvs {
			if strings.Contains(kv, "=") {
				k := strings.Split(kv, "=")[0]
				v := strings.Split(kv, "=")[1]
				os.Setenv(k, v)
			}
		}

		// Get the bosh ca cert
		output, err = om.Curl(api.RequestServiceCurlInput{Path: "/api/v0/certificate_authorities", Method: "GET"})
		Expect(err).NotTo(HaveOccurred())

		// Decode the response body
		var cas CAOutput
		err = json.NewDecoder(output.Body).Decode(&cas)
		Expect(err).NotTo(HaveOccurred())
		certPem := cas.CertificateAuthorities[0].CertPem

		// Create a tmp file for the bosh ca cert
		caFile, err := ioutil.TempFile("", "bosh-ca-cert")
		Expect(err).NotTo(HaveOccurred())
		_, err = caFile.WriteString(certPem)
		Expect(err).NotTo(HaveOccurred())
		ca := caFile.Name()

		// Export BOSH_ALL_PROXY
		proxy := fmt.Sprintf("ssh+socks5://ubuntu@%s:22?private-key=%s", omTarget, omSSHKey)
		os.Setenv("BOSH_ALL_PROXY", proxy)
```

**Comment by mcwumbly** [comment]
I would use this feature

**Comment by genevieve** [comment]
In bash: https://github.com/pivotal/control-plane/blob/master/set-bosh-proxy-creds.sh

cc @zmb3

**Comment by fredwangwang** [comment]
a question about the `ssh+socks5` format. The given example (and bbl) assumes that there is a ssh_private_key for the opsman. But it is not always the case. For example, opsman vsphere only supports password until 2.2.

Does BOSH support using password instead of the private key to open the tunnel? Something like: `ssh+socks5://ubuntu@opsman.example.com:22?password=super-secure`

**Comment by jtarchie** [comment]
Feature added by PR #292
