### ISSUE TITLE
Consider `om` availability via homebrew package manager

### ISSUE THREAD

**Issue by aegershman** [pivotal-cf/om#293]
In order to make the `om` binary easier to consume, releases could be available for mac users via homebrew package management.

I'm under the impression `om` is already available via `apt-get` thanks to `Starkandwayne` via #96 , so this might be a question better suited for @drnic or someone over at https://github.com/starkandwayne/homebrew-cf ?

**Comment by aegershman** [comment]
: D

Thank you, I appreciate it

**Comment by jtarchie** [comment]
We (Pivotal) might need to have a discussion of the official distribution of `om` as we slowly reach a v1.0.0 consensus. Since the tap is not something we _control_ there might be some hoops.

**Comment by drnic** [comment]
You can borrow/fork the CI pipeline we use now for our om deb & homebrew.


________________________________
