### ISSUE TITLE
om version darwin 0.45.0 release prints "unknown"

### ISSUE THREAD

**Issue by drnic** [pivotal-cf/om#294]
I downloaded `om-darwin` and when running `om version` it prints `unknown`.

**Comment by jtarchie** [comment]
@drnic can you check the `PATH` and `which om`? I just download `om-darwin` locally and it showed the version for 0.45.0 and 0.46.0 respectively.

**Comment by jtarchie** [comment]
Are you still experiencing this error? Please feel free to open it again if you are still experiencing this issue.
