### ISSUE TITLE
feature-request product config - don't export default settings

### ISSUE THREAD

**Issue by drduker** [pivotal-cf/om#296]
om product-config and director-config options export every single option.  

It would be better to have an extra param with the om tool to not export the setting if it is already a default setting.
Default settings shouldn't need to be set.  It would just make the configs that platform-automation uses so much smaller.

**Comment by kcboyle** [comment]
@drduker  what problem are you trying to solve with this feature request? We've found with interactions with customers that they do want to have all values set in their foundations when they pull down the configs. 

We also don't have a way of telling if a value is a default value from the Ops Manager API. We can see that a value is set, but in a tile, Ops Manager treats the "default" like any normal value.

**Comment by aegershman** [comment]
Apologies for the minor hijack, just wanted to comment w/ some thoughts:

- it reduces the clutter in the amount of configuration code that needs to be stored off; if, you're only storing off the deltas from how you diverge from defaults, it reduces noise / cognitive overhead when making changes in your yml config.
- it allows for a tile maintainer to publish a new version of their product with new reasonable defaults, and the stored configuration wouldn't be out of date. It allows for "floating" config values.

of course if opsmgr doesn't have a way of indicating a default value it's not possible, though I could definitely see the value in only exporting config deltas. Again my bad for hijack @drduker just voicing some thoughts

**Comment by kcboyle** [comment]
@drduker @aegershman 
Thinking back on this issue, can you help us out by proposing an interface on what this would look like for `staged-config` and `staged-director-config`? If you could give us a concrete example of what a desired config would look like? We are limited by what the [Ops Manager API](https://docs.pivotal.io/pivotalcf/2-2/opsman-api/#configuring-products) returns, and from a cursory glance, it doesn't appear that the endpoints used by `staged-config` and `staged-director-config` have any knowledge of what is a default and what is required but not defaulted. 

Let's talk through the problem space, and see if we can develop a solution based on the resources available.

**Comment by kcboyle** [comment]
@drduker @aegershman

Can you give us a little more information on this issue? We'd love to address it, but need a couple questions answered first.

**Comment by aegershman** [comment]
/cc @kcboyle

Hm right it appears you'd need to need some way to do a diff against what's supplied as default in a tile & what's "overridden" (configured) by a user. The only way to get those defaults is to look at the `*.pivotal` tile itself... I wonder if this is something which could be [done in the tile-config-generator](https://github.com/pivotalservices/tile-config-generator)?

But ehhh, bleh, meh, honestly I think we can just close this, it's not a priority to me at the moment 👍  unless drduker has any commentary or concerns, otherwise my vote is close this 😉

**Comment by kcboyle** [comment]
Great call on tile-config-generator @aegershman! 

We actually just released a [change](https://github.com/pivotal-cf/om/releases/tag/0.55.0) to `config-template` (experimental) that is a limited feature set from tile-config-generator. The biggest change from TCG is that it will pull down the config from Pivnet every time (though not from an existing Ops Manager). The Pivotal Platform Automation team is also writing [documentation](docs.pivotal.io/platform-automation) for using/setting up this command, but it is currently unreleased, and not yet publicly available (Link is there for future benefit).

`config-template` will actually separate out the default vars from your standard config template (all values are ((parameterized)) in the base template. To find the params that are missing, you can take the base.yml, give the produced vars that config template just gives you, and you will be able to see what's left using `om interpolate`

Does this sound like something that could fit your use case @drduker

**Comment by drduker** [comment]
@kcboyle - That sounds promising.  As long as we have a way to easily separate the values and make the configs as simple as they can be then I'm satisfied.  Not actually working pcf pipelines atm though.  You can close as far as I'm concerned.
