### ISSUE TITLE
I need a full file example, preferably in JSON, for vsphere configure-director

### ISSUE THREAD

**Issue by rlewkowicz** [pivotal-cf/om#297]
Your pipelines repo https://github.com/pivotal-cf/pcf-pipelines has it using flags like:
```
om-darwin \
  --target https://$OPSMAN_DOMAIN_OR_IP_ADDRESS \
  --skip-ssl-validation \
  --username "$OPS_MGR_USR" \
  --password "$OPS_MGR_PWD" \
  configure-director \
  --iaas-configuration "$iaas_configuration" \
  --director-configuration "$director_config" \
  --az-configuration "$az_configuration"
```
Those `.*configuration` flags are gone as of:
0.47.0

```
$ om-darwin --version
0.47.0
```

So then you go look at the read me:
https://github.com/pivotal-cf/om/blob/master/docs/configure-director/vsphere.md

And you have fragments of yml configurations but I'm not sure what the keys are on that. 
```
- name: az-1
  cluster: cluster-1
  resource_pool: pool-1
- name: az-2
  cluster: cluster-2
  resource_pool: pool-2
- name: az-3
  cluster: cluster-3
  resource_pool: pool-3
```
Ideally, it would have a key "availability_zones" because thats whats generated by: OPSMANURL/api/installation_settings from opsman

So in json:
```
"availability_zones" : {
  "name": "AT-2",
  "clusters": [
    {
      "cluster": "CF-Sandbox",
      "resource_pool": "PCF-AT2-AZ1"
    }
  ]
}
```

I need to put all of these in a single file because now all you have is --config

**Comment by rlewkowicz** [comment]
@mcwumbly Any thought on this? (I hope you don't mind the direct ping). I know pipelines is being productized, and we might get in the beta (and or I hear it's GA soon) but is there a plan for configure-director vmware to leave alpha?

**Comment by mcwumbly** [comment]
@rlewkowicz I don't mind the direct ping at all!

That said, at this time, I think someone from the @pcf-platform-automation team may be closer to the problem and better positioned to consider this idea.

**Comment by rlewkowicz** [comment]
Thanks @jtarchie this was exactly what I needed! I'm still fumbling around a bit. We're not able to pursue the reference architecture so I've had to hack at the pipelines to see how things are done and then try to modify them to our needs. So mostly I'm just pulling vars/commands out and trying to adjust them accordingly
