### ISSUE TITLE
Configure LDAP no option to Provision an Admin Client

### ISSUE THREAD

**Issue by johnlonganecker** [pivotal-cf/om#300]
It is great that there is now support for `configure-ldap-authentication` we would like to be able to `provision an admin client in the Bosh UAA` but there is no command argument to let us do this in the om cli.

Am I missing something or does that feature not exist.

Thanks!

**Comment by jtarchie** [comment]
There appears to be an option for LDAP and SAML for that, under `create_bosh_admin_client` in the API docs.

We'll put a story in our backlog for this. PRs welcome on it though.

**Comment by brightzheng100** [comment]
I encountered this issue too.

The workaround was:
1. Switch back to Internal UAA; and
2. Then switch back to LDAP from UI, remember to check that BOX!!

**Comment by kcboyle** [comment]
The box that is selected will allow you to create the UAA client, but there is no way to automated-ly get back the client information from the command line without going through a manual process (yet). In a future release of Ops Manager, the created client credentials are something that will be able to be set, but this is not fully command-line supportable yet. 

The manual process is documented here: https://docs.pivotal.io/pivotalcf/2-4/customizing/opsman-users.html

**Comment by kcboyle** [comment]
@johnlonganecker @brightzheng100 Just a friendly poke/reminder to answer our questions above. We'd be happy to offer checkbox support, but unless it is required to continue the manual steps, we'd prefer to wait until OpsMan allows it to be fully automate-able.

**Comment by brightzheng100** [comment]
Based on my experience, I did the `configure-ldap-authentication` but it didn't get me a way to log into BOSH Director.
So I switched over to Internal UAA and then switched back to LDAP again with that BOX checked -- by doing all these was just to have that UAA client created.
After that it's okay again to use `configure-ldap-authentication` -- which looks like once this UAA client is created, it's okay to do whatever you want automated-ly. @kcboyle

**Comment by kcboyle** [comment]
@brightzheng100 @johnlonganecker if you are doing ldap authentication completely manual (not using `om`), can you login without 
1) creating a UAA user first 
2) without ever checking that box

What does checking the box give you if you configure ldap after already configured using internal UAA (there is also no way to change authentication methods in an automated way, as a "fun" fact.)

If you create the UAA client first, then try `configure-ldap-authentication`, does it matter whether you check the box or not? how is the deployment process different checking/unchecking?

**Comment by kcboyle** [comment]
@brightzheng100 @johnlonganecker Any update on the comment above?

**Comment by johnlonganecker** [comment]
We have put this task on the back burner for now, but we still need it. \We have automated everything using concourse so it would be nice to be able to check that checkbox with the om cli.

**Comment by brightzheng100** [comment]
As it's one-off effort -- we may 1) still do once of that workaround; 2) put some more effort (another task) to create the UAA client before `configure-ldap-authentication`.

But I believe this should be simplified by only calling `configure-ldap-authentication`, for example.

**Comment by kcboyle** [comment]
@brightzheng100 @johnlonganecker A friendly reminder to please respond to the message above. Thank you!

**Comment by RMeharg** [comment]
I am also working with a customer and running into this issue with a slightly different use case.

We are trying to configure SAML with multi-factor authentication out of the box and need the option in the the om CLI to create the bosh admin client and also the option to set the precreated_client_secret for the precreated-client. This will allow us to use the precreated-client to perform additional actions non-interactively without MFA. For now we are using om curl to do this, but would be nice to have this feature so we can use env.yml with configure-ldap-authentication for Pivotals Platform Automation.

**Comment by jtarchie** [comment]
@RMeharg, can you share the `on curl` command you are using?

**Comment by jghiloni** [comment]
I think this is solved by 2a5eb1d ... am I wrong?

**Comment by kcboyle** [comment]
I believe @jghiloni is correct (thanks for looking into that for us). I am going to close this issue. Please reopen if this assumption turns out to be incorrect.
