### ISSUE TITLE
Feature Request - output required-default-configs of a tile/product

### ISSUE THREAD

**Issue by itpick** [pivotal-cf/om#301]
Feature Request - output required default configs of a tile/product for use with using platform-automation to configure that tile/product.
```
om-linux -k --env env.yml staged-config --product-name ${product_slug} --default-required-configs
```
Also, default-configs that are already set when uploading a product would be nice to see as they change in every version of a tile it seems:
```
om-linux -k --env env.yml staged-config --product-name ${product_slug} --default-configs
```

**Comment by kcboyle** [comment]
@drduker we don't quite understand what feature request you are asking for. Can you please give an example of what you see now that is undesirable for your use case, and what you would like to/expect to see?
