### ISSUE TITLE
`resp` can be nil here even when err is not nil.

### ISSUE THREAD

**Issue by flyinprogrammer** [pivotal-cf/om#305]
https://github.com/pivotal-cf/om/blob/d23650eea8c5a947938a88a17a4e9915c29bb0b2/api/diagnostic_service.go#L31

```
om --client-id <id> --client-secret <secret> --target https://<somewhere>/ staged-products
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x6fdef7]

goroutine 1 [running]:
github.com/pivotal-cf/om/api.Api.GetDiagnosticReport(0x7f82b1550040, 0xc000064900, 0x7f82b1550060, 0xc00000a8e0, 0x7f82b1550080, 0xc000085c20, 0x7f82b1550080, 0xc000085bf0, 0x99fb40, 0xc000090730, ...)
	/tmp/build/80754af9/go/src/github.com/pivotal-cf/om/api/diagnostic_service.go:31 +0xe7
github.com/pivotal-cf/om/commands.StagedProducts.Execute(0x9a9180, 0xc000085ce0, 0x9a0600, 0xc000091540, 0x0, 0x0, 0xc00001c0f0, 0x0, 0x0, 0x28, ...)
	/tmp/build/80754af9/go/src/github.com/pivotal-cf/om/commands/staged_products.go:36 +0x19d
github.com/pivotal-cf/om/vendor/github.com/pivotal-cf/jhanda.CommandSet.Execute(0xc000085d10, 0x7fffed97c606, 0xf, 0xc00001c0f0, 0x0, 0x0, 0x7, 0xb)
	/tmp/build/80754af9/go/src/github.com/pivotal-cf/om/vendor/github.com/pivotal-cf/jhanda/command_set.go:25 +0x11c
main.main()
	/tmp/build/80754af9/go/src/github.com/pivotal-cf/om/main.go:194 +0x5015
```

**Comment by crhntr** [comment]
@zachgersh and I came across this panic as well.

There is, from a Go perspective, a standard practice of mutual exclusion between when you get an error and when you get a response from the server (notice how we didn't say successful).

This leads to two problems:

1) The code above, in an error case, is checking that a resp has a StatusCode (which would never actually happen if an error had occurred).
2) The `validateStatus` is producing an error on anything that is non-200 when this is in fact not an error but a valid response from the server that just so happens to be a non-200.

**Comment by fredwangwang** [comment]
This is a bug! Will do a fix for that. But the reason you guys hit this specific is probably something wrong with `--target`
