### ISSUE TITLE
TCP connection timeout

### ISSUE THREAD

**Issue by dfoleypivotal** [pivotal-cf/om#308]
Just recently we updated the GCP Quickstart (https://github.com/cf-platform-eng/gcp-pcf-quickstart) to use OpsMgr 2.3.  Since this change, we are seeing many TCP timeouts like the error below. Did something change or do we need to add better retry logic to the cli?

omg-cli: error: failed running step ApplyChangesPAS, error: installation failed to get logs: could not make api request to installations logs endpoint: token could not be retrieved from target url: Post https://opsman.pcf.dfoleypivotal.com/uaa/oauth/token: read tcp 10.0.1.3:36138->35.227.85.126:443: read: connection reset by peer, try --help
omg-cli: error: failed running step RunOmg, error: running command: Process exited with status 1, try --help

**Comment by jtarchie** [comment]
Hi. This is issues for the om CLI not the omg-cli. Is there anything related that you address to a command being used from om?

**Comment by dfoleypivotal** [comment]
Talking with the Google team they lead me to believe that it was calling om let me do some more digging and see what I can find

**Comment by dfoleypivotal** [comment]
Looking at the omg-cli is using the OM API. Lots of people out due to holidays will continue to look at how it is being used.

import (
	"fmt"

	"omg-cli/opsman"

	"github.com/pivotal-cf/om/api"
)

**Comment by jtarchie** [comment]
I've also just noticed that the error message provided isn't actually a timeout. It is a `connection reset by peer`.

**Comment by kcboyle** [comment]
Hi @dfoleypivotal ! I just wanted to follow up on this issue with you. 

Were you able to get more information on what specifically in `om` was giving y'all an error?

**Comment by kcboyle** [comment]
@dfoleypivotal! Following up with you again. Would you happen to have more information that could help us out more with your issue?

**Comment by dfoleypivotal** [comment]
Behavior has been better but still see errors. I will have some time next week to do more testing and supply you with details. Would think best approach would be to add in retry logic.

**Comment by kcboyle** [comment]
@dfoleypivotal we still need to know _where_ in `om` you're seeing problems. Sure we can add retry logic, but _where_ and _why_ does it happen?

**Comment by kcboyle** [comment]
@dfoleypivotal, a gentle poke to see if this issue is still relevant for you and for your team. If so, could you help us figure out where and why the TCP connection times out?

**Comment by dfoleypivotal** [comment]
@kcboyle Have not been seeing any issues lately. My guess is the problem was network connection on GCP. If it comes up again I will do more digging to find the root cause. Thanks for the help.

**Comment by rkoster** [comment]
Today we encountered this issue again while working on gcp-quickstart. The issue occurred when we started using the `omg-cli remote` command to execute our steps. When invoked directly from our development machine the same commands (`push-tiles` and `deploy`) worked fine.

This lead us to believe that the issue may be caused by the connection between `jumpbox => loadbalancer => opsman-vm`. We tests this hypophysis by updating `/etc/hosts` to point to the internal opsman-ip (so the network path becomes `jupmbox => opsman-vm`).  After this change we did not see the issue again.

Apparently using `internal over external IPs` is a known performance bottleneck: https://cloud.google.com/blog/products/gcp/5-steps-to-better-gcp-network-performance

**Comment by kcboyle** [comment]
Hi @rkoster! 

We are not familiar with the `omg-cli` at all, could you give me a little more info on what `om` commands are being used when you call `omg-cli remote`? Is `om` being used as a library or as a CLI in the `omg-cli` code?

**Comment by rkoster** [comment]
the `omg-cli` is the binary of the gcp-pcf-oneclick project https://github.com/cf-platform-eng/gcp-pcf-quickstart/tree/master/src/omg-cli.
The `remote` command takes the binary and uploads it to the jumpbox and executes the given command from the jumpbox, the reason for it being faster tile up/downloads.

**Comment by kcboyle** [comment]
Thanks for the quick response @rkoster. The `om` team does not maintain that project, have you opened this issue in the `omg-cli` repo? We are happy to try to help, but `om` does not have a `remote` command, and without digging into another team's code, I don't know where to start with the issue you are experiencing in an external library. 

Is the `omg-cli` directly calling `om`? or is it consuming it as a library? can you narrow down, for the team, what command in `om`(not `omg-cli`) is failing?
