### ISSUE TITLE
configure-bosh --network-assignment reports success but fails on OpsMan 1.8.13 on vSphere

### ISSUE THREAD

**Issue by pivotal-todd-ritchie** [pivotal-cf/om#31]
Hi folks,

We're trying to use `om` version 0.15.0 to configure OpsMan 1.8.13.0. Our biggest hurdle right now is we can't assign an az in the director.
 
```
root@b22b378f7cf2:/# om-linux --target https://pcf.$ENV_NAME.cf-app.com -k --username "$DEFAULT_OPSMAN_USERNAME" --password "$DEFAULT_OPSMAN_PASSWORD" configure-bosh --network-assignment '{"singleton_availability_zone":"default-az","network":"default"}'
assigning az and networks for bosh tile
finished configuring bosh tile
```

When we run the above command and observe the UI we see that "singleton availability zone" is blank, but the pane at the side has a checkbox. If we try to install we get a 500 suggesting that the singleton az guid is blank.

Any help appreciated!

Thanks,
Todd & Mark

**Comment by rainmaker** [comment]
Hi @pivotal-todd-ritchie ,

Looks like we were ignoring the az configuration in the case where you pass the `network-assignment` flag and not the `az-configuration` flag as well. But your use-case is totally valid! It's fixed now on master, and should be released soon. Thanks for reporting this!

Raina
