### ISSUE TITLE
Cannot initiate apply-changes after a failed install

### ISSUE THREAD

**Issue by eamonryan** [pivotal-cf/om#32]
When using om to re-try a failed deployment, it believes an install is already running and does not initiate a new one:

```
$ om -k -t $OPSMAN_URI -u $OPSMAN_USERNAME -p $OPSMAN_PASSWORD apply-changes
found already running installation...re-attaching
```

Nothing follows the text above, it just sits there forever until cancelled.

Note: The install was initially started via the opsman GUI, I am not sure if the same behaviour occurs if the failed install was initiated by om.

**Comment by ryanmoran** [comment]
@eamonryan when you curl the `/api/v0/installations` API endpoint, what do you see?

**Comment by eamonryan** [comment]
The output is pretty verbose but I assume you wanted the topmost install:

`
om_curl /api/v0/installations
Status: 200 OK
Cache-Control: max-age=0, private, must-revalidate
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Mon, 16 Jan 2017 20:17:53 GMT
Etag: W/"20cf371cdbddcf79baadd7310fcfcea7"
Server: nginx/1.4.6 (Ubuntu)
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: 097bcf55-90d7-4407-a6c6-53457743e4fb
X-Runtime: 2.159036
X-Xss-Protection: 1; mode=block
{
  "installations": [
    {
      "user_name": "gap",
      "finished_at": "2017-01-16T19:50:50.793Z",
      "started_at": "2017-01-16T19:02:41.308Z",
      "status": "failed",
      "additions": [],
      "deletions": [],
      "updates": [
        {
          "identifier": "newrelic-broker",
          "label": "New Relic Service Broker",
          "product_version": "1.1.0",
          "change_type": "update",
          "guid": "newrelic-broker-8f4a2e824a2f136c6a12"
        },
        {
          "identifier": "p-spring-cloud-services",
          "label": "Spring Cloud Services",
          "product_version": "1.3.2",
          "change_type": "update",
          "guid": "p-spring-cloud-services-556bd21402ad731628e1"
        },
        {
          "identifier": "cf",
          "label": "Pivotal Elastic Runtime",
          "product_version": "1.8.25-build.2",
          "change_type": "update",
          "guid": "cf-a892a42e3c9ea517375e"
        },
        {
          "identifier": "p-redis",
          "label": "Redis",
          "product_version": "1.6.4",
          "change_type": "update",
          "guid": "p-redis-a835e5a9179d81431f26"
        },
        {
          "identifier": "apm",
          "label": "Metrics",
          "product_version": "1.2.4",
          "change_type": "update",
          "guid": "apm-11909b5f9fbfbb80bfc7"
        },
        {
          "identifier": "p-mysql",
          "label": "MySQL",
          "product_version": "1.8.1",
          "change_type": "update",
          "guid": "p-mysql-95f0dbf1badf42e09d74"
        }
      ],
      "id": 138
    },
`

So it looks like from that viewpoint it thinks the install did indeed fail, but we just tried another apply-changes and it's just sitting there.

**Comment by ryanmoran** [comment]
The behavior of "re-attach" in the `apply-changes` command is to scan the list of previously created installations and look for any installation that is in the "running" state. The command will then re-attach to that installation.

Not included in the above output was this installation:
```json
{
      "user_name": "xxx",
      "finished_at": null,
      "started_at": "2016-06-16T17:59:43.820Z",
      "status": "running",
      "additions": [],
      "deletions": [],
      "updates": [],
      "id": 68
    },
```

As can be seen, the installation is still marked as running. This is a bug in the OpsManager and should be addressed there.
