### ISSUE TITLE
Docs for bosh-env describe apply-changes instead

### ISSUE THREAD

**Issue by clhynfield** [pivotal-cf/om#322]
Hi, all. The documentation for the `bosh-env` sub-command appears to be a stale batch of copypasta from the `apply-changes` sub-command. Happy to issue a PR if I get around to it before y’all, just wanted to get an issue open so I don’t forget. 

Thank you!

**Comment by kcboyle** [comment]
Hi! Thanks for opening an issue and apologies for the delay. What changes are you talking about/would want to make in regards to the sub-command?

**Comment by kcboyle** [comment]
could you give a little more info about what documentation is lacking? (where) if it's a quick fix, we could edit it, but if you feel comfortable, please submit a PR @clhynfield

**Comment by kcboyle** [comment]
@clhynfield could you elaborate a little more on which documentation is fishy?

**Comment by clhynfield** [comment]
Just submitted #339, which hopefully does one better than elaborating!

**Comment by kcboyle** [comment]
closing this issue due to the merged PR. Thanks!
