### ISSUE TITLE
Cannot run go get -u github.com/pivotal-cf/om due to undefined variables

### ISSUE THREAD

**Issue by leeloodub** [pivotal-cf/om#326]
When I run

```
go get -u github.com/pivotal-cf/om
```

I get the following error:
```
../../go/src/github.com/pivotal-cf/om/commands/s3_client.go:62:3: undefined: s3.ConfigV2Signing
```

Can you please take a look? Or should we not use `go get` to install om CLI?

**Comment by jtarchie** [comment]
Don't use `go get` to install the CLI. Use the released versions on Github.

The issue that you are experiencing with `go get` is actually related to `go mod`. When you `go get` something, it doesn't read the `go.mod` for the dependencies. I believe this is a _known issue_ within golang.

Going to close as there is nothing we can do to fix this.
