### ISSUE TITLE
go mod and replace directive does not work well when consumed as library 

### ISSUE THREAD

**Issue by ramonskie** [pivotal-cf/om#334]
when we consume `om` in our own go library above version `0.51.0`
go mod will fail. because it won't inherent the replace directive.
which then result in a compile error due to a missing dependency
see line: https://github.com/pivotal-cf/om/blob/master/go.mod#L44

i think this can be solved by
removing the replace directive and use the folowing instead
` go mod edit https://github.com/graymeta/stow@TheCommitHasYouWantToUse`

refrence: https://github.com/golang/go/issues/30354

**Comment by jtarchie** [comment]
I don't believe that would help at all. As upstream dependency's `go.mod` files don't appear to be honored at all.

So if you `go get github.com/pivotal-cf/om`, even though it has a `go.mod` file, the `go get` does nothing with it with you `go.mod` file.

**Comment by jtarchie** [comment]
Why are you inheriting `om` as a dependency, too? At the moment we make no library guarantees about the source code. Just the CLI.

**Comment by ramonskie** [comment]
we are building an easy way to configure opsman+tiles
https://github.com/starkandwayne/om-configurator

**Comment by kcboyle** [comment]
It would really help you (and other `om` consumers out!) if y'all could bug the stow team by giving a shout out to this issue (https://github.com/graymeta/stow/issues/197). If we can get the associated PR accepted, this should solve your problem. As we don't seem to be able to get around the `go.mod` bug (that they don't see as a bug), this seems like a good solution)

**Comment by ramonskie** [comment]
they have merged it.
can you update you `go.mod` as well?

**Comment by kcboyle** [comment]
we can. We are in the middle of fixing the CI at the moment, so feel free to submit a PR, or we should be able to get to it either today, tomorrow, or, at worst, sometime early next week.

**Comment by ramonskie** [comment]
fixed in https://github.com/pivotal-cf/om/commit/be5a7f895fd6e45e0941a102b5bdbf085b0df240#diff-37aff102a57d3d7b797f152915a6dc16
