### ISSUE TITLE
Make --password optional or at least do not require to enter in shell

### ISSUE THREAD

**Issue by janaurka** [pivotal-cf/om#34]
Hey *

This is a feature request.

If I see this correctly, currently it is required to enter the `--password` flag for `authenticated actions` every time `om` is called in plaintext during the `call`.

Could you consider to support one of multiple variants of:

* Allow setting the password using an `env variable` like `OM_PASSWORD`
* Allow setting login credentials in a file like `~/.om/credentials` -> an option `om login` would be cool which could write the file ;-)
* If `--password` is set, but no password entered, ask for it and do not print the output. eg. the `mysql` client works like this.

This tool looks like it could ease up my life quite a bit until we have automated the `om` stuff away, but I really don’t want to spoil the `om` password in my `~/.bash_history`.

cheers

**Comment by craigbookwalter** [comment]
perhaps you know this already, if you're running any command interactively in bash, if you precede the command with a space, it won't be saved in your history ... might help you get by in the meantime.

**Comment by janaurka** [comment]
@craigbookwalter: sure, i can also write a cronjob which checks my bash history and wipes everything which looks like a pw inside. But I’d prefer to have something reliable ;-)

**Comment by zachgersh** [comment]
@janaurka latest release now has this - enjoy.
