### ISSUE TITLE
when using `bosh-env` the `--target` cannot contain a trailing slash

### ISSUE THREAD

**Issue by jtarchie** [pivotal-cf/om#350]
When using `bosh-env`, if the `--target` host has a trailing slash (like when copied from a Location bar) it will fail.

This is because the URLs generated for the SOCKS5 environment variables have something that looks like:

`socks5+ssh://hostname.com/:22`

when they should look like

`socks5+ssh://hostname.com:22`

**Comment by kcboyle** [comment]
This is currently going through acceptance, and will be included in the next release

**Comment by kcboyle** [comment]
Closing this issue. This will be released by EOD today in 1.1.0
