### ISSUE TITLE
configure-authentication returns incorrect message when run immediately after opsman VM deployment

### ISSUE THREAD

**Issue by RoboMWM** [pivotal-cf/om#357]
When running `om configure-authentication` immediately after deploying the opsmanager VM on vSphere, it erraneously reports `configuration previously completed, skipping configuration`, despite the opsmanager authentication not being configured at all. If `om configure-authentication` is run at a later time, authentication configuration succeeds.

https://github.com/pivotal-cf/om/blob/76d70ae40b13aa52d07ebcc2d8461bd46f33e4cc/commands/configure_authentication.go#L53-L55

**Comment by RoboMWM** [comment]
om version is `0.56.0`

**Comment by kcboyle** [comment]
@RoboMWM to clarify, is there a state where you get back an error while configuring authentication if the endpoint is not up, or do we always print out the `configuration previously completed, skipping configuration` regardless of actual status?

**Comment by RoboMWM** [comment]
So, this might've been issue with our environment - we found another ops manager VM (that was inadvertently forgotten about and not removed) running on the same IP and DNS. Will confirm after completing the teardown of the previous deployment.

**Comment by kcboyle** [comment]
Please do keep us updated @RoboMWM!  

If it turns out to be a non-issue, could you close this one? If not, we have it prioritized to look into sometime in the next few weeks.

**Comment by RoboMWM** [comment]
Yup, this was indeed the issue. Whoops.

**Comment by emorenis** [comment]
> @RoboMWM to clarify, is there a state where you get back an error while configuring authentication if the endpoint is not up, or do we always print out the `configuration previously completed, skipping configuration` regardless of actual status?

Hi, We are experiencing exactly the same thing, and there is no error stating that endpoint is not reachable. Can you please advise? Thanks

**Comment by kcboyle** [comment]
Hi @emorenis!  
To verify with you, when you create a new ops manager vm, that has never been configured before, you immediately run `configure-authentication` and do not get an error returned, but the command completes successfully with the error message: "configuration previously completed, skipping configuration"?

**Comment by emorenis** [comment]
Hi, @kcboyle 

Actually, I attempt to run it against already created Opsman VM to change its values from Basic Authentication to LDAP.

**Comment by emorenis** [comment]
> Hi, @kcboyle
> 
> Actually, I attempt to run it against already created Opsman VM to change its values from Basic Authentication to LDAP.

@kcboyle Do you believe om commands are not applicable for this scenario? Thanks

**Comment by kcboyle** [comment]
@emorenis `configure-authentication` is not applicable for the scenario of changing authentication methods. The Ops Manager API does not support doing this automatically (last I checked, I'm happy to be wrong). 

Therefore, `om` cannot support it either. The process of switching forms of auth is entirely manual at the moment 😞

**Comment by emorenis** [comment]
@kcboyle Thank you very much! I really appreciate your response!
