### ISSUE TITLE
Community Feedback Ask - Pending Changes

### ISSUE THREAD

**Issue by kcboyle** [pivotal-cf/om#359]
We're thinking of implementing the Ops Manager `pre-deploy-check` endpoint in `om`(a 2.6+ feature). Our thoughts are to put it into `pending-changes`, which is a different, less complete version of the endpoint. however, `pre-deploy-check` sounds better than `pending-changes`, so we're considering
- making an entirely new `pre-deploy-check` command 
- changing the `pending-changes` command name to `pre-deploy-check`
- just keeping it a part of the `pending-changes` command (with a flag like `--verbose` or something)

Any thoughts from the community on this matter? We'll be starting the work today, under the assumption of keeping these changes at the very least in the `pending_changes_service`, whether they stay there, move to their own, or are renamed.

**Comment by kcboyle** [comment]
There appear to be two endpoints for pre-deploy-check, one for the director, and one for products
`/api/v0/staged/director/pre_deploy_check`
`/api/v0/staged/products/:product_guid/pre_deploy_check`

Perhaps it makes more sense, with this knowledge, to have pre-deploy-check as its own command

**Comment by mcwumbly** [comment]
perhaps it'd make sense to introduce `pre-deploy-check` as it's own _experimental_ command first, and then decide whether it's worth rolling it into an existing command or not once you have some feedback?

in particular, now that we're in semver-land, the experimental flag may be useful as a way to iterate on changes until they are ready to become part of the supported "api".

**Comment by kcboyle** [comment]
We decided to have a new command as suggested @mcwumbly ! Thank you for the response!
