### ISSUE TITLE
add product version to the download-file.json

### ISSUE THREAD

**Issue by vchrisb** [pivotal-cf/om#360]
It would be good to add `product_version` to the `download-file.json` like `stemcell_version`.
e.g.
```
{
  "product_path": "p-healthwatch-1.5.2-build.4.pivotal",
  "product_slug": "p-healthwatch",
  "product_version": "1.5.2",
  "stemcell_path": "light-bosh-stemcell-170.51-google-kvm-ubuntu-xenial-go_agent.tgz",
  "stemcell_version": "170.51"
}
```

**Comment by jtarchie** [comment]
Why is this information useful? What would you use it for?

**Comment by vchrisb** [comment]
I would like to have first a download only pipeline which has a broader glob, like `2.5.*`, in the download-product config files. After downloading and storing the artifacts in s3, at the end of the pipeline all exact versions, like `2.5.3`, are committed to the download-product-s3 config files of the first stage, sandbox. The sandbox pcf deploy pipeline is triggered on that commit and does install/upgrade the known versions. Again at the end of the sandbox pipeline, the exact versions are committed to the download-product-s3 config files of the second stage, dev... and so on.
This allows to track in git the versions deployed and roll a specific set of product versions automatically through multiple stages.
Does that make sense?

**Comment by kcboyle** [comment]
PR welcome, but we do have this prioritized. 

If you would like to start working on it, please tell us, and we'd love to work with you on this. 

To clarify, does this get used by `assign-stemcell` at all or is this strictly to optimize another workflow? 

We had discussed as a team maybe outputting an additional file (not called `assign-stemcell.json` that could have this value (and perhaps other values in the future that might be deemed useful). @vchrisb

**Comment by vchrisb** [comment]
Happy to do a PR, as this should be easy. `DownloadProductOptions` already includes `ProductVersion` in https://github.com/pivotal-cf/om/blob/46ce73cb58cb29472d606b40de89ca771e317656/commands/download_product.go#L48
It would be used to as described in the previous comment and I think `download-file.json` is a good place.

**Comment by kcboyle** [comment]
@vchrisb, sounds like that would be easy enough to pass through. 
My first thought was to grab the product version from the downloaded tile itself, but as that product can be opsman, a tile, a stemcell, or even a terraform template (or more!) that might get complicated really fast, and potentially be unreliable. 

Like I said though, if you have time and want to get it hashed out, feel free, but we do have this coming up in the next couple of weeks in our backlog.

are you thinking `download-file.json` as another outputted file?

**Comment by vchrisb** [comment]
@kcboyle I've done a PR to add the functionality

**Comment by kcboyle** [comment]
PR has been merged
