### ISSUE TITLE
OM fail to download when aws CDN  gives 403

### ISSUE THREAD

**Issue by bottkars** [pivotal-cf/om#365]
We have situations where AWS CDN responds with a 403 / Access Denied  upon download after receiving the download link. this causes OM to go into an ( infinite ?? ) wait.

Response size at this step is 110B  and a non matching she therefore
![image](https://user-images.githubusercontent.com/8255007/57704826-f58c5c80-7662-11e9-98b6-2e222c679d7e.png)

Response from Webrequest using Powershell to the API:
Invoke-WebRequest : AccessDeniedAccess denied
At C:\Users\AzurestackGuy\Documents\WindowsPowerShell\Modules\PIVPosh\0.5\PIVPosh.psm1:87 char:9
+         Invoke-WebRequest -Method $Method -Uri $URI -Headers $Global: ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestComma

**Comment by bottkars** [comment]
0 B / 110 B [--------------------------------------------------]   0.00% 10m14s
could not execute "download-product": could not download product: could not download product file p-spring-cloud-services: Downloader.Get: problem while waiting for chunks to download: failed during retryable request: could not get new download link: could not parse json ["<?xml version=\"1.0\" encoding=\"UTF-8\"?><Error><Code>AccessDenied</Code><Message>Access denied</Message></Error>"]
invalid character '<' looking for beginning of valu

**Comment by kcboyle** [comment]
Hi @bottkars ! We chatted about this a lot in closed channels. To summarize: 
we replicated a 403 locally, and we returned an error right away (we used a real token for a product that we didn't have access to, and a fake token that wouldn't work):
```
$om download-product -t <pivnet-token> --output-directory ./temp-stuff/ --pivnet-product-slug pivotal-ops-manifest --pivnet-file-glob="*" --product-version-regex *
could not execute "download-product": 403 - not allowed to show? this #<Product id: 278, name: "Pivotal Operations Manager Manifest Generation Lib...", logo_url: "", description: "This product packages the current OpsManager manif...", slug: "pivotal-ops-manifest", feature_list: [], docs_url: "", category: "Pivotal Cloud Foundry", s3_directory_id: 400, more_info_url: "", support_forum_url: "", knowledge_base_url: "", created_at: "2019-02-08 21:02:17", updated_at: "2019-05-14 01:11:55", deleted_at: nil, legacy_s3_directory_id: nil, allows_second_eula: false, lifecycle_state: "Beta", support_email: "", partner_sales_email: "", license_url: "", platform_compatibility: [], quickstart: false, mutable: false, sort_type: "custom", installs_on_pks: false>. Errors:
```

We did track down where the error was coming from in go-pivnet.

Our assumption is that go-pivnet is trying to execute the request we give it, and the 10-minute timeout is coming from their end (om actually has a 30-minute timeout for requests)(https://github.com/pivotal-cf/go-pivnet/blob/2172a68c9031bd489bda88e844165195319936a2/download/downloader.go#L132).

Would you be okay with closing this issue?

**Comment by kcboyle** [comment]
Hi @bottkars! 

A reminder to ask if we are okay with closing this issue, or if there is something more you wanted to talk about on this?

**Comment by bottkars** [comment]
Happy to close
