### ISSUE TITLE
Make Pivnet Token optional when using download source s3

### ISSUE THREAD

**Issue by vchrisb** [pivotal-cf/om#371]
Flag `--pivnet-api-token` is currently mandatory even when using `--source s3`
https://github.com/pivotal-cf/om/blob/master/commands/download_product.go#L47

And when using `--source s3`, `om` does not validate if all required parameters for `s3` are present.
E.g. when `--s3-secret-access-key ` is missing following unspecific error is printed:
`could not execute "download-product": Key: 'S3Configuration.RegionName' Error:Field validation for 'RegionName' failed on the 'required' tag`

**Comment by jtarchie** [comment]
This does seem like an issue. Feel free to submit a PR

**Comment by vchrisb** [comment]
@jtarchie kust removing the `required` tag should be sufficient?
The pivnet golang package will handle missing API token:
`could not execute "download-product": could not download product: could not fetch the product files for ops-manager 2.5.4: must supply valid API token`

**Comment by kcboyle** [comment]
@vchrisb 

You would have to remove the `required` tag, but maintain the required behavior if you are using pivnet. So we would expect to see a test that validated all pivnet creds were present is `source` is not defined. This might require some refactoring of other tests (removing pivnet creds from the s3 tests).

**Comment by kcboyle** [comment]
merged pull request #378 to resolve this issue
