### ISSUE TITLE
{"errors":{"base":["undefined method `guid' for nil:NilClass"]}}

### ISSUE THREAD

**Issue by hjaffan** [pivotal-cf/om#374]
I'm running into an issue with the CLI when trying to configure a tile. I am providing these flags. but then the error I receive is regarding 
```
{"errors":{"base":["undefined method `guid' for nil:NilClass"]}}
```
#Flags
```
om --env env/env.yml configure-product --config config/product.yml --vars-file config/product-default-vars.yml --vars-file config/resource-vars.yml --vars-file config/errand-vars.yml --vars-file vars/tiles/a9s-elasticsearch/a9s-elasticsearch.yml --ops-file config/features/backup_config-backup_disabled.yml --ops-file config/network/3-az-configuration.yml
```
# Output
```
configuring product...
setting up network
could not execute "configure-product": failed to configure product: request failed: unexpected response:
HTTP/1.1 500 Internal Server Error
Transfer-Encoding: chunked
Cache-Control: no-cache, no-store
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Thu, 30 May 2019 15:00:57 GMT
Expires: Fri, 01 Jan 1990 00:00:00 GMT
Pragma: no-cache
Server: Ops Manager
Strict-Transport-Security: max-age=15552000; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: 22886955-5b98-4840-84eb-5ee83c032b03
X-Runtime: 0.322035
X-Xss-Protection: 1; mode=block

40
{"errors":{"base":["undefined method `guid' for nil:NilClass"]}}
```

**Comment by jtarchie** [comment]
The error comes from Ops Manager.
The final configuration is missing some value.
The `configure-product` just passes the file to the OpsManager API, without doing any validation, as we don't know the shape of the tile at that runtime.
If we can narrow down what value is set to `null` in the config file we can help OpsManager generate a better error message.

**Comment by hjaffan** [comment]
@jtarchie thank you very much for the information. After doing some debuging, it boiled down to a typo in the name of the network.
I appreciate the quick feedback.

**Comment by jpmcb** [comment]
Circling back around for this; we are synching up with the Ops Manager team and will discuss better error handling for API payloads.
