### ISSUE TITLE
om apply-changes --product-name  apply's all when product not found

### ISSUE THREAD

**Issue by rguilme1** [pivotal-cf/om#381]
Ran om apply-changes --product-name p-windows-runtime command against Ops Manager 2.4.
Instead of returning an error because p-windows-runtime is not staged, it ran a full apply of all products.

Using om 1.1.0 on Ops Manager 2.4.

To Recreate:  om apply-changes --product-name bad-name

**Comment by jtarchie** [comment]
@rguilme1, thanks for reporting this.

We should just have the command if the product does not exist at all.
This would be a great first PR. Would you be able to fix this?

**Comment by kcboyle** [comment]
accepted. Will be in next release
