### ISSUE TITLE
credential-references shows a subset of all possible credentials

### ISSUE THREAD

**Issue by kkallday** [pivotal-cf/om#382]
Hi all,

I noticed some odd behavior today when trying to pull credentials for Pivotal Container Service. When I run `om credential-references` I see the following:
```
+-----------------------------------------------------------------+
|                           CREDENTIALS                           |
+-----------------------------------------------------------------+
| .pivotal-container-service.pks_tls                              |
| .properties.cf_mysql_billing_db_password                        |
| .properties.cf_mysql_mysql_admin_password                       |
| .properties.cf_mysql_mysql_cluster_health_password              |
| .properties.cf_mysql_mysql_galera_healthcheck_db_password       |
| .properties.cf_mysql_mysql_galera_healthcheck_endpoint_password |
| .properties.cf_mysql_pks_db_password                            |
| .properties.cf_mysql_telemetry_db_password                      |
| .properties.cf_mysql_uaa_db_password                            |
| .properties.pks_api_uaa_client                                  |
| .properties.pks_services_admin_uaa_client                       |
| .properties.pks_uaa_management_admin_client                     |
| .properties.uaa_admin_password                                  |
| .properties.uaa_encryption_passphrase                           |
+-----------------------------------------------------------------+
```

However, when I do an `om curl --path /api/v0/deployed/products/<product guid for pks>/variables` to pull all variables I get the following:
```json
{
  "variables": [
    "bosh_dns_health_client_tls",
    "bosh_dns_health_server_tls",
    "bosh_dns_health_tls_ca",
    "dns_api_client_tls",
    "dns_api_server_tls",
    "dns_api_tls_ca",
    "tls_ca",
    "pivotal-container-service-387eb5750da8f106387c/uaa_client_secret",
    "cf_mysql_billing_db_password",
    "cf_mysql_mysql_admin_password",
    "cf_mysql_mysql_cluster_health_password",
    "cf_mysql_mysql_galera_healthcheck_db_password",
    "cf_mysql_mysql_galera_healthcheck_endpoint_password",
    "cf_mysql_pks_db_password",
    "cf_mysql_telemetry_db_password",
    "cf_mysql_uaa_db_password",
    "pivotal-container-service/pks_tls",
    "pks_api_uaa_client",
    "pks_services_admin_uaa_client",
    "pks_uaa_management_admin_client",
    "uaa_admin_password",
    "uaa_encryption_passphrase",
    "galera_server_certificate",
    "kubo_odb_ca",
    "kubo_odb_ca_2018",
    "mysql_server_certificate",
    "odb_broker_basicauth",
    "pks_api_basicauth",
    "pks_api_internal_2018",
    "pxc_galera_ca",
    "pxc_server_ca",
    "telemetry_ca_2018",
    "telemetry_server_tls_2018",
    "uaa_active_pks_saml_key_2018",
    "uaa_jwt_signing_key_1"
  ]
}
```

I was expecting both lists to be identical. The variable I am interested in is [`bosh_odb_ca`](https://github.com/pivotal-cf/p-pks-integrations/blob/7eb28681ee40d9bb78a945c2604655730c9add6a/bosh-variables/odb.yml#L1).

I _think_ the issue is that `om credentials` only prints list of properties that are marked as type `secret`, `password`, etc but the API `/variables` endpoint gives you both variables and properties that are credentials.

**Comment by jtarchie** [comment]
What do you use this command for? It appears that this command and the variables endpoint are two different things.

**Comment by kkallday** [comment]
I'm trying to retrieve the `bosh_odb_ca` secret which is a bosh variable (not a property).

I expected `om credential-references` to retrieve all bosh vars and properties that are marked as credentials - anything that is generated by bosh/opsman and not user-defined. I have to use a curl command with a long path to fetch my credentials instead of using the `om credential-references` command which felt awkward.

Feel free to close this issue if this is expected behavior.

**Comment by jtarchie** [comment]
I don't think there's a bug here.
It is a feature request.
I'm just not completely sure I understand, though.
As I've not had experience with this workflow.

This is a command that has just _been here a long time_, long forgotten who and why...
Can you expand more why you expect the credentials which are properties, would also return these variables, too? If they were combine into a single list, do we some way to identify each's origin? Credentials can be defined, are you expecting to set variables, too?

**Comment by kkallday** [comment]
When we implemented `om credentials-references` it was a way for the user to retrieve credentials that are not user-defined. I believe we were pulling properties that were marked as types that are secrets (`password`, `certificate`, etc). Bosh variables weren't around.

Sounds like you are going to deprecate the command since it's "long forgotten" so I will close this issue.

**Comment by jtarchie** [comment]
Deprecated, not at all.

I just have no frame reference of how/why/when to use it. Didn't even know it existed till you created the issue.

**Comment by evanfarrar** [comment]
I think @kkallday may be trying to construct a product config for a version of his tile (PKS) that does not have a sample product configuration, as it is pre-release. And he would like to so without human intervention, as his goal is automated testing of new properties for the tile. I gather that `om staged-product` now fills that usecase?

**Comment by kkallday** [comment]
@evanfarrar I'm not configuring PKS. I'm trying to pull the Bosh ODB CA (see first post). This is related to the installation of Pivotal Service Mesh. Since `bosh_odb_ca` is a Bosh variable (not a property) it isn't in the cred refs output. My expectation was that the command would show all generated creds.

At the time I worked on the story Bosh vars wasn't around.

**Comment by evanfarrar** [comment]
Interesting. What if Container service _did_ expose this as a property? On PAS tile we have been toying with exposing properties for things that don’t have form fields to support setting them via automation, but I haven’t considered reasons you might want to get tile properties for automation.

**Comment by kkallday** [comment]
That would help. I am not sure of how the decision is made to expose a secret via property vs Bosh variable. Maybe @afong94 can answer this?

**Comment by evanfarrar** [comment]
From what I understand, tile properties are usually only made for the purposes of exposing a form field. But you can make properties without exposing a form field, too, and it would be gettable/settable via OM.

**Comment by kkallday** [comment]
Yeah they could do that. It sounds like this is no longer an om issue since
it doesn't sound like credential references will be changed to return Bosh
variables that are credentials. I'll chat with the PKS folks about
potentially exposing that variable via a hidden property.

**Comment by jtarchie** [comment]
I'm still trying to understand if this is information that should be available programmatically to a user. If so, we could discuss adding it to this command or a new one. If you are finding that you need access to bosh vars to work done, maybe this is a OpsManager feature, too.

**Comment by mcwumbly** [comment]
We have a use case where this feature would be valuable. for installing our product on PKS, we require getting a variable and currently have it documented as such:

```
product_guid="$(om curl --path /api/v0/deployed/products \
  | jq '.[] | select(.type=="pivotal-container-service").guid' -r)"
 
om curl \
  --path /api/v0/deployed/products/$product_guid/variables?name=kubo_odb_ca_2018 \
  | jq -r .kubo_odb_ca_2018.ca > /tmp/kubo_odb_ca.crt
 
om curl \
  --path /api/v0/deployed/products/$product_guid/variables?name=kubo_odb_ca_2018 \
  | jq -r .kubo_odb_ca_2018.private_key > /tmp/kubo_odb_ca.key
```

I believe with this command we could simplify our installation instructions for this step to retrieve the variables with:

```
om variables -p pivotal-container-service \
  -c .kubo_odb_ca_2018 -f ca > /tmp/kubo_odb_ca.crt
om variables -p pivotal-container-service \
  -c .kubo_odb_ca_2018 -f private_key > /tmp/kubo_odb_ca.key

```

**Comment by jaristiz** [comment]
Hi, looks like a PR is not present for this issue, and as we are performing a clean-up of this repository if there are no further discussions on this topic we will close it.
