### ISSUE TITLE
FEATURE REQUEST: Enable support for default values in variables for om interpolate

### ISSUE THREAD

**Issue by dawu415** [pivotal-cf/om#383]
Working with a number of customers for multi foundations, who utilize a templatized product yml file and a parameter file specific to each foundation. It would be clean and convenient to be able to have a template file with a variable and a default value if the variable was not specified.  

In a simplistic example, say we have 3 foundations, `dev`, `perf` and `prod`.  `dev` requires 30 diego cells, `perf` requires 15 diego cells, `prod` requires 15 diego cells.     Each foundation's params file would specify the diego cell instance count.  We have different diego cells in `dev` vs `prod` because `dev` has a lot more test apps.   Assume for some reason we require `perf` and `prod` to have the same diego cell instances since they will need to mirror each other.   

Right now there is a  params file for each foundation which specifies the diego cell instance count.  If the prod diego cell count changes, we will need to update the perf.    While 3 foundations isn't too bad, multiply this by 6 and it becomes a maintenance nightmare. 

Feature request example :
product.yml:
```
diego_cell:
  instances: ((diego_instance_count | 10))
```
where `|` is a delimiter in the variable specifying an `or default` 
 
If our product-params.yml file contains  `diego_instance_count: 20`, then it would then be overriding the template and set the `instances: 20`, otherwise, the value will default to 10.

**Comment by aegershman** [comment]
Just an idea: is it possible that multiple `--vars-file` entries could be used? E.g., like how with the `fly` cli you can specify multiple `--vars` files, where the last file overrides the key config. That way you could have a default `values.yml` file, and under each IaaS / region / env, you could have a `values.yml` that selectively overrides the content? Not sure if this would work in this case, but it's a pattern I use all the time with `fly` and `bosh` and `helm`, and it's pretty dang powerful. What do you think?

**Comment by dawu415** [comment]
Thanks for the suggestion.  I've actually had trouble with that in the past and did try that with `fly`, it could've been an ordering of the var files that I did. We did consider using a defaults file and also ops files too but felt it was too many moving parts and wanted to keep it simple and complete in a single file.

**Comment by jtarchie** [comment]
@dawu415 this functionality that you are referring is built into the OpsManager tile processing.

We should not provide logical operations in the YAML files. Making YAML templating into a programming language is difficult line to cross. We've seen the success and large failures of `spiff` and `spruce` for example. This is also the history of terraform templates, which were data, but now include `if/else` mechanisms.

I'd like to strongly encourage the separation of data and logic. @aegershman recommendation is possible, but you correct that the ordering matters, as the evaluation and merging of params files.

There are other tools that can be used to generate YAML files, too. It doesn't have to be embedding within the document itself. Such as using Ruby or Golang to generate the YAML, as it is Just Data™.  

There is also [ytt](https://get-ytt.io/). It seems like an interesting YAML with logic built into mechanism.

Are you able to try any of these other patterns?

**Comment by dawu415** [comment]
@jtarchie Thanks. Let me have a look at ytt. It might work as a pattern for some customer. For some others, they are air-gapped and enforce a strict security check on getting those binary bits in. The process is months long and complicated... (unless ytt was packaged with platform automation docker image)


As an alternative, would it be possible if there was an override flag with om interpolate e.g. `--override-variable`, where this is specified such that if a yaml key with specified in the params, it would override the key.value in the template.   The simple alternative to this, I suppose, is to embed op commands in the params and use the `--ops-file` flag.  But that could get messy as well.

**Comment by dawu415** [comment]
Ok. Scratch that. We can't mix ops and vars together in a single file - but I guess an ops file could be an override.

**Comment by jtarchie** [comment]
Were you able to figure a workable solution?

**Comment by nbconklin** [comment]
@dawu415 how did this work out for you?

**Comment by dawu415** [comment]
Hi
We just opted to keep it simple for now and not use default values but instead specify it in our params files instead.   I'm happy to close this, otherwise.

**Comment by kcboyle** [comment]
Happy to hear that there is, at the very least, a workaround for this. If the params file causes issues for you in the future, or if you discover a way that we could include the defaults without complex yaml parsing, feel free to reopen/discuss with the team.
