### ISSUE TITLE
Update http proxy settings after configuring auth

### ISSUE THREAD

**Issue by xyloman** [pivotal-cf/om#388]
I might be missing something but ran into a use case where we needed to configure http proxy after setting up auth on our ops manager.  It appears that configuring auth is completely skipped when already configured which appears to mean that http proxy settings are also not updated.

```
+ om --env env/env.yml configure-authentication --config config/auth.yml
configuration previously completed, skipping configuration
```

Based upon this PR I figure the http proxy would be configured for the ops manager but only the first time that auth is configured: https://github.com/pivotal-cf/om/pull/252  After which point the task appears to skip configuring all configuration?  Maybe I am missing something?

**Comment by jtarchie** [comment]
There is a limitation of the OpsManager API, which does not allow reconfiguring of the authentication after initial load -- including `http(s)_proxy` values. We are discussing with the OpsManager team on how to move forward with this.

**Comment by jtarchie** [comment]
There is no way to do this via API for the GUI, at the moment.
I'm going to close this issue, we can revisit it, if/when OpsManager supports reconfiguration or authentication.
If you must to do this on an OpsManager, please contact Pivotal Support as they will be able to assit you further.

**Comment by aegershman** [comment]
Went ahead and opened a pivotal support ticket about the use-case so there's something in the backlog about it: case number 211454
