### ISSUE TITLE
dial tcp: i/o timeout

### ISSUE THREAD

**Issue by pdelagrave** [pivotal-cf/om#39]
The opsmanager host is unavailable for a few second to 1-2 minutes on random occasions. We blame it on "the cloud" right now because there's really nothing pointing to any other problems. We have that problem since we started using OM, at its very initial release.

Our pcf installation pipelines are often failing because OM isn't resilient enough in those situations.

Would it be possible to add an internal retry on those errors? We're working around the problem for apply-changes, where it is very likely to happen because of the long duratinn of the connection but we don't want to generalize that code to all OM usages: https://github.com/pivotal-cf/pcf-a1/blob/terraform2/tasks/scripts/apply_changes.sh

Thanks

Pierre

```
+ om -k -t https://pcf.dev-1-9-azure-clean.iet.to.cf-app.com -u admin -p jejEebRok9 configure-product --product-name p-rabbitmq --product-properties '{
  ".rabbitmq-server.server_admin_credentials": {
    "type": "simple_credentials",
    "value": {
      "identity": "rabbitAdmin",
      "password": "rabbitPassword"
    }
  }
}' --product-resources '{
  "rabbitmq-server": {
    "internet_connected": false
  },
  "rabbitmq-haproxy": {
    "internet_connected": false
  },
  "rabbitmq-broker": {
    "internet_connected": false
  },
  "broker-registrar": {
    "internet_connected": false
  },
  "broker-deregistrar": {
    "internet_connected": false
  }
}'
configuring product...
setting properties
finished setting properties
applying resource configuration for the following jobs:
	broker-deregistrar
	broker-registrar
	rabbitmq-broker
could not execute "configure-product": could not fetch existing job configuration: could not make api request to resource_config endpoint: token could not be retrieved from target url: Post https://pcf.dev-1-9-azure-clean.iet.to.cf-app.com/uaa/oauth/token: dial tcp: i/o timeout
```

**Comment by zachgersh** [comment]
hey @pdelagrave - I looked at the code path around this and I believe we can add the same sort of `Temporary()` error retry logic that we have around streaming the logs. We'd add this around the logic where we grab the oauth token.

**Comment by pdelagrave** [comment]
Hi @zachgersh 
It's worth noting that the timeout can happen for any endpoints on the opsmanager host, not just the oauth token one.

**Comment by zachgersh** [comment]
I considered this as well. We could move the retry on temporary error logic
into or HTTP client. That would resolve this though it will take some
restructuring.

**Comment by totherme** [comment]
We're seeing this on the RMQ tile team too -- would love to know when the issue is resolved.

**Comment by jasper9** [comment]
PEZ Team has started using OM and seeing this too mostly during apply-changes.   For us, a way to reattach to the apply-changes session would great.

**Comment by zachgersh** [comment]
@jasper9 that already exists. The command always attempts a reattach if you run it before trying to start a new apply.

**Comment by jasper9** [comment]
@zachgersh right... but if you run apply-changes after it completes it will start a new one right?

**Comment by zachgersh** [comment]
@jasper9  - correct. You just have to double-check that one isn't running before triggering again. We could always set a flag so that it won't trigger a new one but will connect if running. Let me know if that is a feature you want and we can add a story to our backlog.

@pdelagrave - we've got code in `om` master now that will do retries around getting and token and http `GET` requests. I'd love if we could get some feedback from master pipeline. If you'd like to not rebuild the binary and want to wait for an official release no problem with that either.
