### ISSUE TITLE
`generate-certificate` accepts multiple `-d` flags but only one is used

### ISSUE THREAD

**Issue by eamonryan** [pivotal-cf/om#396]
om version `1.2.0`

If you ask `om` to generate a certificate for you, it will accept the `-d` flag multiple times, implying that it would generate a certificate containing each of the domains passed.

`om generate-certificate -d "domain1.${ROOT_DOMAIN}" -d "domain2.${ROOT_DOMAIN}" -d "domain3.${ROOT_DOMAIN}" > generatedcert.json`

The command succeeds.

However, the generated cert will contain only the last `-d` flag passed:

```
-----BEGIN CERTIFICATE-----
MIIDsDCCApigAwIBAgIVAP08cZc3hUSnHQV2Ojg4ltM5MkwiMA0GCSqGSIb3DQEB
CwUAMB8xCzAJBgNVBAYTAlVTMRAwDgYDVQQKDAdQaXZvdGFsMB4XDTE5MDYyNTE5
NDUyNloXDTIxMDYyNTE5NDUyNlowVjELMAkGA1UEBhMCVVMxEDAOBgNVBAoMB1Bp
dm90YWwxNTAzBgNVBAMMLGRvbWFpbjMuY29udHJvbHBsYW5lLmhhYXMtMjE1LnBl
ei5waXZvdGFsLmlvMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5ZNT
KjpYUkxWVTe2SSZStguM3FrZCnAV+qWRmtVDaooJSTqpvraMo7+6JAvkS52R/U23
zr5aXkoteeh6tkQJmU7yPHrcxJAClCgxKh/ltOwrfIKJt57HkRCRw3XKCL3UfGBE
0V5PxlQn+AohMTbII9Yqh7hGwy5ZHAqtPFeghO5t2gOCxoFWTk+QuXnsc5+PWmRF
8jHd/9uJJIEO7XGHgweDp7F9NDOgXE/rNNZIrecDC5b+eVdFOWBhb0ise3imdqmq
rTFCduF9N5u/ihyHek0iex3zLwzSuFHHJ1wzLxR/Gv645dT+/LepLzPphR/pes21
wyKvZCtNrABhcNEW6QIDAQABo4GrMIGoMB0GA1UdDgQWBBRXHdaZibhueEi/PoR1
68cKrZK5MzAfBgNVHSMEGDAWgBSOuJVl4APftRWZf8UB2Z533NJ3czAdBgNVHSUE
FjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDgYDVR0PAQH/BAQDAgeAMDcGA1UdEQQw
MC6CLGRvbWFpbjMuY29udHJvbHBsYW5lLmhhYXMtMjE1LnBlei5waXZvdGFsLmlv
MA0GCSqGSIb3DQEBCwUAA4IBAQBrV++pAropLaPEHl9t8QoQxgRPUGytnhVeQCY2
plZHs31ljn+eedQ6M24lTTN3OjchYIWk6Ryok9rP1nEE/HHu9qbCMScURmgz54vp
aB0MyHKzlYzg9x77Hudtk1Rkqc+ktuxC4ICIv4LAhzfPN9j20eakMu2+zojcBrQu
OzxOiIrqxQWBj3L27PQ2lChVk/udaMqkdbpcEu5YHT41+uot+r0/wb7pYCCFKu2o
G2zmgHGGUvjaGLJWrmJ5zNPG9OR32Zc1xJZ/v5lL2XyL4W7EeCeaZnUx2oQgZNrr
4CHpStrB0wi081fdfbttiAIjXRIDwmZTKyE99NV8AhOkyGf2
-----END CERTIFICATE-----
```

`$ openssl x509 -in certificate.crt -text -noout`
...
`Subject: C=US, O=Pivotal, CN=domain3.<domain redacted>`

```
X509v3 Subject Alternative Name:
                DNS:domain3.<domain redacted>
```

However, if you do it "properly" e.g.:
`om generate-certificate -d "domain1.${ROOT_DOMAIN},domain2.${ROOT_DOMAIN},domain3.${ROOT_DOMAIN}" > generatedcert2.json`

You get a proper cert with all SANs.

`$ openssl x509 -in cert2.crt -text -noout`

`Subject: C=US, O=Pivotal, CN=domain1.<domain redacted>`

```
X509v3 Subject Alternative Name:
DNS:domain1.<domain redacted>, DNS:domain2.<domain redacted>, DNS:domain3.<domain redacted>
```

It would probably be better to simply fail if multiple `-d` flags are passed to `om generate-certificate` and prompt that only one `-d` should be passed, with comma separated domains if there are multiple.

**Comment by jpmcb** [comment]
Thanks @eamonryan for the issue! Yes, this makes sense to me as well. We should do the following:
1. Fail if multiple `-d` flags are included 
2. Instruct the user to use a comma separated string with the domains desired

Would be a great first issue if someone would like to claim.

**Comment by jghiloni** [comment]
I'm looking into this and made a discovery: there's no way to tell `jhanda` to require exactly one instance of a flag. I propose allowing multiple `-d` flags and joining them all with commas before proceeding. However, I would still allow multiple domains specified in one `-d` instance to contain multiple comma-separated names for backward compatibility.

Thoughts?

**Comment by kcboyle** [comment]
that sounds like a good alternative solution to the problem!

**Comment by kcboyle** [comment]
This will be in the next release of `om`. Thanks for the PR @jghiloni !
