### ISSUE TITLE
om revert-staged-changes will fail in OM 2.5+

### ISSUE THREAD

**Issue by kcboyle** [pivotal-cf/om#399]
This command will silently fail. 

We assume this is due to changes in the OpsMan API. 

Expectation: 
`om revert-staged-changes` should return an error if it fails, OR it should successfully revert changes

This command hits an HTML form, and not the Ops Manager API. It is assumed that the form has changed for newer versions of OpsManager. 

Exploration into how long this has been an issue is necessary, and tests would need to be written to validate that an older form and the newer form both work. Minimum supported version of OM as of July 2019 is 2.3.x

Discussion to deprecate this command, as it is a hack and does not actually talk to the Ops Manager API.

**Comment by davidjahn** [comment]
it appears that `revert-staged-changes` is behaviorally identical to `unstage-product` (which uses the API).... probably the best course of action is to remove this command entirely from `om`

**Comment by jtarchie** [comment]
this will be removed in `om` 3.0
