### ISSUE TITLE
om retry request to ops manager

### ISSUE THREAD

**Issue by xchapter7x** [pivotal-cf/om#40]
was wondering if there is any plan to add retry attempts/interval type of flags to om.

scenario i am looking to handle is, 
__given__ a ops manager has just been spun-up/restarted
__when__ uaa is not yet started or
ops manager service is not yet started or
ops manager vm-instance is not yet booted
__then__ a call to ops manager via om should retry N number of times at an interval of Y
where N and Y are flags to om

my real world implementation of this scenario is, i am running a pipeline which upgrades opsmanager. this is a process of, spin down opsMan VM, deploy new opsMan VM, wait until it is completely started (uaa and ops manager service) and then run a import settings against the api.

i would like a way to poll the state of ops manager or, retry my request until successful within given time or counter contstraints.

let me know your thoughts on this, if it would be better to implement a API status endpoint (ops man team) or have the om tool handle this type of scenario. 

Thanks.

**Comment by zachgersh** [comment]
It may be interesting to add these flags but it sort of removes the simplicity from the tool. Are you scripting this or is it being done via concourse? I would say both can do retries already. Have you tried retrying when you see a failure come back from `om` and did that not work?

**Comment by xchapter7x** [comment]
Good suggestion. I guess I could split out the polling into its own task and leverage concourses `attempts: X`  ... that might get me what I'm looking for.

**Comment by zachgersh** [comment]
If it doesn't or you feel like it is too limiting just come back and let us know (re-open this issue). Once you have a bit more data around what is painful when implementing it outside of `om` then we can try to design a more optimal solution.
