### ISSUE TITLE
"om upload-stemcell --floating false" does not work

### ISSUE THREAD

**Issue by cfryanr** [pivotal-cf/om#402]
Command used:
`om ${om_opts} upload-stemcell --stemcell ${stemcell_file_name} --floating false`

Actual behavior:
Acts as if you had used `--floating=true`

Desired behavior:
Either act as if you had used `--floating=false`, or error out with a nice message because `false` is an unexpected positional argument

Workaround:
Be super careful to use `--floating=false`

**Comment by kcboyle** [comment]
This will be included in the next release. `upload-stemcell` should support
`--floating=true` AND
`--floating true`
