### ISSUE TITLE
Rename executables to be more automation friendly

### ISSUE THREAD

**Issue by nodo** [pivotal-cf/om#407]
Hi there,

At the moment the executable are called `om-ARCH-VERSION`, would it be possible to called them `om-ARCH` only? For instance instead of `om-linux-3.0.0` -> `om-linux`

Our team tries to always keep `om` up-to-date by using a link like this one: https://github.com/pivotal-cf/om/releases/latest/download/om-linux-3.0.0. However, because the assent name contains the version, it doesn't really work.

Would it be a hard thing to change for the next releases?

**Comment by jtarchie** [comment]
@nodo I’m not quite sure why the version number is an issue here. Are you able to clarify why the file cannot be downloaded? The link you provided above has the version number in it.

The version name is ideal to have because if someone downloads it locally they can identify what version they downloaded.

**Comment by nodo** [comment]
We would like to have a link that always points to the latest version (E.g. we would love to have a link like https://github.com/pivotal-cf/om/releases/latest/download/om-linux). 

Since the executable name contains the version, the link: https://github.com/pivotal-cf/om/releases/latest/download/om-linux-VERSION breaks every time  a new version of `om` is released. What we had before was: https://github.com/pivotal-cf/om/releases/latest/download/om-linux-2.0.1 and broke because latest is now https://github.com/pivotal-cf/om/releases/latest/download/om-linux-3.0.0.

I can see from the release history that you used to not put the version in the assets name (see [here](https://github.com/pivotal-cf/om/releases/tag/1.2.0)). Do you think we could go back to that?

**Comment by jtarchie** [comment]
@nodo, we cannot provide that, sorry. It is very intentional to have the version name in the binary.

We can help you find an alternative to do the same thing, though.

```bash
curl https://api.github.com/repos/pivotal-cf/om/releases/latest | jq -r '.assets | map(select(.browser_download_url | contains("linux"))) | first | .browser_download_url'
```

Using Github's API, we can get the latest release, and whittle down to the correct release. That _should_ be deterministic.
