### ISSUE TITLE
om config-template cannot get template from pivnet

### ISSUE THREAD

**Issue by poligraph** [pivotal-cf/om#415]
I am trying to get template for elastic runtime from Pivnet and got error for om-cli 3.1 and 3.0 on MacOS

`./om-darwin-3.0.0 config-template --output-directory cf --pivnet-api-token ${PIVNET_TOKEN} --pivnet-product-slug elastic-runtime --product-version 2.4.13 --product-file-glob cf*.pivotal`

error:
```
could not execute "config-template": error getting metadata for elastic-runtime at version 2.4.13: 

error with New Reader: https://network.pivotal.io/api/v2/products/elastic-runtime/releases/431937/product_files/450768/download does not support byte-ranged requests.
```

`./om-darwin-3.0.0 config-template --output-directory cf --pivnet-api-token ${PIVNET_TOKEN} --pivnet-product-slug elastic-runtime --product-version 2.4.13 --product-file-glob cf*.pivotal`
error:
```
could not execute "config-template": error getting metadata for elastic-runtime at version 2.4.13:

error with New Reader: https://network.pivotal.io/api/v2/products/elastic-runtime/releases/431937/product_files/450768/download does not support byte-ranged requests.
```

**Comment by kcboyle** [comment]
hi @poligraph !

The amazon support ticket came back and they told us they were no longer able to reproduce the issue. Can you confirm if you're able to use `config-template` again on your end?

**Comment by poligraph** [comment]
Hi @kcboyle . I was able to get configs from pivnet. Thanks. Closing issue.
