### ISSUE TITLE
om interpolate.  Error if both stdIn and -c flag are provided 

### ISSUE THREAD

**Issue by calebwashburn** [pivotal-cf/om#418]
If both std input and -c flag are provided it should error to indicate both inputs are provided for template file.

**Comment by kcboyle** [comment]
makes sense to me. happy to accept a PR.

**Comment by jghiloni** [comment]
Proposed solution after speaking with @jtarchie : we're going to do this more like how `bosh` does it. Specifically:

1. If `-c` is passed and is not `-`, it will take precedence and ignore `stdin`
2. If `-c` is passed and is `-`, it will use `stdin`
3. If neither is passed, the existing error will be thrown.

**Comment by jghiloni** [comment]
Do we want to preserve the existing use case where `stdin` is used if present and no `-c` flag is present? I think so, for backward compatibility

**Comment by kcboyle** [comment]
backwards compatibility sounds like the best way to do this. default `stdin` and optional `-c` flag
