### ISSUE TITLE
[Feature Request] Turn on or off errands

### ISSUE THREAD

**Issue by RRRII** [pivotal-cf/om#42]
Looking to see if a feature can be added to be able to turn on or off tile deployment errands.  It seems that when you stage a product to OpsManager, the errands will stay at the last state.  It would be helpful during an automated deploy to be able to make sure the deployment errands are on before applying changes.

**Comment by ryanmoran** [comment]
I have added these stories to our backlog:
- list errands: https://www.pivotaltracker.com/story/show/140880813
- disable errand: https://www.pivotaltracker.com/story/show/140880833
- enable errand: https://www.pivotaltracker.com/story/show/140880911
