### ISSUE TITLE
Host_group is not exported for director

### ISSUE THREAD

**Issue by tonyelmore** [pivotal-cf/om#420]
If AZ definitions contain a host_group, the om staged-director-config does not export the host_group.

**Comment by kcboyle** [comment]
@tonyelmore thanks for the issue! 

Just as a quick verification question, you are using `staged-director-config` on an _already configured_ director, correct?

**Comment by kcboyle** [comment]
@tonyelmore bump on the above please!

**Comment by kcboyle** [comment]
In fixing a different issue, this appears to be resolved in `om` 4.1.0.

Closing this issue. If you find this to be incorrect, please feel free to reopen
