### ISSUE TITLE
om should take advantage of go 1.13 error wrapping

### ISSUE THREAD

**Issue by jtarchie** [pivotal-cf/om#423]
go 1.13 added support similar to error wrapping in https://github.com/pkg/errors
In `om`, where we create wrapped errors like
```
_, err := ioutil.ReadAll(r)
if err != nil {
        return errors.Wrap(err, "read failed")
}
```
we can now return these errors like:
```
_, err := ioutil.ReadAll(r)
if err != nil {
        return fmt.Errorf("read failed: %w", err)
}
```

**Comment by kcboyle** [comment]
Closing this issue, as there are problems with go 1.13
