### ISSUE TITLE
Provide better notification for Apply Changes completion on Ops Manager Console

### ISSUE THREAD

**Issue by shahs16** [pivotal-cf/om#424]
When Ops Manager is running errands that takes long time, it is easy to context switch and forget that there was a change in progress. Provide flash notification for browser tab or a desktop notification when changes are complete - either fail or success instead of only a popup.

**Comment by nbconklin** [comment]
@shahs16 Are you asking for a change in the UI to make this more obvious, or is there something on the command line that we could do? `om` is not owned by the Ops Manager team. We want to make sure that we can point you in the right direction.

**Comment by kcboyle** [comment]
Hi @shahs16! if this is a feature request for Ops Manager, we recommend submitting a [support ticket](https://pivotal.io/support) to get this feature added for consideration in Ops Manager, or talk to your local PA about this (if you have one).
