### ISSUE TITLE
More robust connection loss handling

### ISSUE THREAD

**Issue by erniebilling** [pivotal-cf/om#425]
Some mechanism to retry communications would be helpful making some of our partner integration testing more robust.

It is not possible to programmatically determine if a om command (apply-changes for example) fails because of a valid error in an installed integration or because the network connection has been lost - besides grep'ing the output.

It would be nice to either have a distinct result code indicating a network issue (so our tools can retry,) or a CLI option to increase timeout/retry.

**Comment by jtarchie** [comment]
There is already `—request-timeout` and `—connect-timeout`, have you tried those?

**Comment by erniebilling** [comment]
You're right, seems we had a very old version of om. I'll close. Thanks.
