### ISSUE TITLE
[platform automation] stage/configure/apply without product

### ISSUE THREAD

**Issue by aegershman** [pivotal-cf/om#428]
This applies to [pivotal platform automation](https://docs.pivotal.io/platform-automation/develop/tasks.html#stage-product); I don't want to go through Pivotal support because I hate not being able to reference conversations + comments in it, so I'm dumping these thoughts here & if they suck or you don't want them then here please close this out as soon as possible 😉 

## context

I looked through some of the [Task References](https://docs.pivotal.io/platform-automation/develop/tasks.html#stage-product) and wanted to share what I noticed.

Most tasks such [`stage`](https://docs.pivotal.io/platform-automation/develop/tasks.html#stage-product), [`configure`](https://docs.pivotal.io/platform-automation/develop/tasks.html#configure-product) or [`selective-deploy`](https://docs.pivotal.io/platform-automation/develop/tasks.html#stage-configure-apply) all take in the `product` as an input. This makes sense, because then you can use `om product-metadata` to get the name/version.

## problem

But passing around `*.pivotal` files just for the name/version is time-consuming and stressful on the Concourse environment. It means passing around a 10+gb `cf.pivotal` file just to stage and apply PAS, even though it was already uploaded. Even on good days, passing around big honkin' files to `stage` and triggering `apply` for PAS can take 20-40 minutes just to start the process for the ceremony surrounding extracting the name/version.

The same applies with replicated tiles-- if you're reliant on the product for the name/version, you have to download the isoseg tile, replicate it, and _then_ pass it to stage/assign stemcell/configure/apply (or once you replicate it you store it in s3, but it's still a pain)

The only time you _need_ the product is when uploading it, replicating it, generating configuration from it, or yanking metadata from it. After that, you don't need it-- you just need the _name_ of it.

## proposal... sort of

I'll have to actually implement & try it before suggesting anything that would be part of the platform-automation toolchain, _but_: currently we store the `product-version` and `stemcell-version` as flat files in a config repo. Our stage/configure/apply tasks read from these files and pass their content to `om`.

**What if the `product-name` came from the [`product.yml`](https://docs.pivotal.io/platform-automation/develop/inputs-outputs.html#productyml), and the `product-version` came from a flat file that just had the semver of the product or stemcell in it? (e.g., `2.6.11-build.3` or `315.95.0`, etc.).**

If the product is passed in, it's used for the name/version. If the `product-{name,version}` files get passed in, they're used instead.

## disclaimer / conclusion

We've fallen off the platform-automation mainline train for some of our tasks, so at some point we need to re-familiarize ourselves with the out-of-the-box configuration like [stemcell handling](https://docs.pivotal.io/platform-automation/develop/inputs-outputs.html#download-product-config), downloading products, etc. to see how these can fit together. We'll get around to uplifting all this eventually. I say this because even though I'm making this suggestion, I'm not going to have a ton of time to personally implement it in the next few days/weeks...

**... What I'm saying is this proposal is untested and isn't an immediate priority, but I know it's a problem & I know it's something that can be solved, it's just a matter of finding the perfect pattern that fits within a logical framework of how platform CI/CD should/could be done**

Thoughts and feedback welcome. And obviously feel free to close it whenever, I know it's off-top from `om`, so apologies about that. Thanks for your time 👍

**Comment by kcboyle** [comment]
Expanding on this issue to explore a possible use-case for this change:

Platform Automation tasks that stage a product all take a product file. This is useful for pipeline design/simplicity reasons, but Ops Manager 2.8 has a pre-uploaded-but-not-staged telemetry tile. Since there's no product file necessary for this tile, users have to write a custom task to stage it.

**Comment by kcboyle** [comment]
We made some changes to platform automation to support passing in either a separate file to `stage-configure-apply` with just the name and version, or the `product.yml` used by `configure-product` with the version added. Take a look at what we're thinking for the next release of platform automation. Going to close out this issue! Thanks for being so willing to chat with the team and work with us through this!

https://docs.pivotal.io/platform-automation/develop/release-notes.html#whats-new

**Comment by aegershman** [comment]
Hey @kcboyle okay real quick, sorry to append this to the same github issue I can create another one, but quick idea:

[on tasks such as `apply-changes` there are certain envvars which can be set like this:](https://docs.pivotal.io/platform-automation/develop/tasks.html#stage-configure-apply)

```sh
  ALLOW_PENDING_CHANGES: false
  # - Optional
  # - If false, will fail if there are pending changes in OpsMan

  RECREATE: false
  # - Optional
  # - If true, will recreate the vms for the product
  # - If true, will also recreate the director vm if there are changes

  IGNORE_WARNINGS: false
  # - Optional
  # - If true, will not fail when verifiers have warnings,
  #   it will still fail for any errors.
  # - This is not recommended unless unless the warning failure(s)
  #   are well understood.
```

Those are valuable flags, though they're set as envvars "statically" and can only be changed/set using `fly`, rather than dynamically reading them from a file in git.

Any thoughts on making configuration switches like that available to be set in a file as well? E.g. imagine `features.yml` or `options.yml` or `flags.yml` or `switches.yml` or `command-flags.yml`, I have no idea what to actually call it, but it'd be a file that has those same kinds of flags set via task envvars except parameterized as code, example:


```yml
# flags.yml
recreate: true
allow-pending-changes: false
ignore-warnings: false
```

then have the `flags.yml` be able to be passed in for commands such as `om apply-changes [...] --flags=/some/product/and/foundation/path/here/flags.yml`?

To be honest this is something I was going to do regardless for how we pass `--recreate` now that we're on 2.9.x+, but just hadn't gotten to it or evaluated it yet 😬

Just a thought, I can absolutely create this as a separate issue.

regardless, thanks a ton to you all as well, thanks for your time!

**Comment by kcboyle** [comment]
Hmmmm I can definitely see the use case for the `recreate` and `allow-pending-changes` flags. (though in the case of SCA, `ALLOW_PENDING_CHANGES: true` seems like it would be undesired in the majority of cases)

I have concerns about `ignore-warnings` being a passable flag. We've been very defensive about how you can set that flag (and only recently added it because there are a few warnings in ops man that do not disappear even if you disable the verifier). if we could pass those in via a file, that _would_ be an `om` change though, not just a change to platform automation. 

I'm not sure how I feel about passing in the flags via a `--flags` flag though. for other commands, we got away with it by allowing a config file (or an `--env` file in the case of the global flags). It just feels...strange?..to have a flag for a command called `flags` that accepts a file.

Created a new issue to talk about this further: #494
