### ISSUE TITLE
om configure-product --product-resource fails to disable "internet_connected"

### ISSUE THREAD

**Issue by pdelagrave** [pivotal-cf/om#43]
Disabling internet_connected using OM configure-resource
doesn't works:
```
./om -k -t https://om.com configure-product \
  --product-name cf \
  --product-resources '{"consul_server": {"internet_connected": false}}'
```
Refreshing the UI after executing the command shows negative result.
____

Enabling internet_connected using OM configure-resource
works:
```
./om -k -t https://om.com configure-product \
  --product-name cf  \
  --product-resources '{"consul_server": {"internet_connected": true}}'
```
Refreshing the UI after executing the command shows positive result.
____

Enabling/Disabling internet_connected using OM curl and the OpsMan Api directly
works:
```
om -k -t https://om.com \
  -p /api/v0/staged/products/cf-uuid/jobs/consul_server-uuid/resource_config \
  -x PUT \
  -d '{"instances": "automatic", "instance_type": {"id": "automatic"}, "persistent_disk": { "size_mb": "automatic"}, "internet_connected": true|false}'
```
Refreshing the UI after executing the command shows positive result.

**Comment by ryanmoran** [comment]
@pdelagrave I'm going to close this as it is already something we have a bug for: https://www.pivotaltracker.com/story/show/139760215
