### ISSUE TITLE
could not execute "delete-product": request failed: unexpected response: 

### ISSUE THREAD

**Issue by liyan-su** [pivotal-cf/om#446]
when I run `om -u admin  -p pswd  -k delete-product --product-name container --product-version 1.91`,

it shows me "could not execute "delete-product": request failed: unexpected response 404", and I ask my colleague for help, so does he, I google many relation info, but no find any similar result.

I need to delete one product from my ops-manager, I wonder that this command doesn't work. could you help me?

**Comment by liyan-su** [comment]
could I use the command that is wrong so that not work? or could the command `delete-product` delete a product from the Ops Manager？

**Comment by nbconklin** [comment]
Hi @liyan-su what is the name of the product in OpsManager that you are trying to delete? It looks like the product name could be the issue as I don't see that product name on a product available via PivNet. Also, are you targeting the environment with the `om` command? Either way, we could have a better error message for this. Thanks!

**Comment by liyan-su** [comment]
This product name is just a substituted name I chose. The real product name is hidden by me.
thank you for your reply first, I have solved this problem by command unstage-product , but I think if unstage-product can remove product, delete-product can do this also. In fact delete-product cannot help me remove this product.

**Comment by nbconklin** [comment]
Thanks for following up, glad that you were able to figure this out. We will update the readme to provide a better description of this command's behavior.
