### ISSUE TITLE
om --env apply `https` by default

### ISSUE THREAD

**Issue by Salamandastron1** [pivotal-cf/om#451]
Writing this up mostly so I don't forget.

There are times where an operator would want to have a url not include the `https` and be unsafe. Test environments and whatnot. The `om` cli is able to accept any target string when it is an environment variable, ala `OM_TARGET`.

For some reason though when using 
```
om --env env/env.yml command-blah
```
The target is always pre-pended with _https_. I'd have to follow the chain a little further down to find root cause but I believe one of the imported packages is appending it via a function.

**Comment by jtarchie** [comment]
There is a default because all the http clients require a scheme to be defined. Out of best practices, we chose `https` as the default scheme to use.

You can include your own `http` in the target URL and it will use that.

**Comment by Salamandastron1** [comment]
Thanks @jtarchie, I figured out I am just an idiot so that is why I deleted. Sorry for bothering y'all!
