### ISSUE TITLE
Commands like "Staged-config" could output comment saying which `om` version was used?

### ISSUE THREAD

**Issue by aegershman** [pivotal-cf/om#452]
In order to know which version of `om` was used to generate externalized configuration & be better able to identify outdated generated config / reproduce the generated config, it could be beneficial for any generated config `*.yml` to have a comment in it which says which version of `om` was used to produce it.

Just an idea, feel free to close this whenever. Thanks 👍

**Comment by aegershman** [comment]
ehhhh I don't know how I feel about this on second thought. Feels like it could just clutter the output .yml... Hm. Going to just close, it's really not that big of a deal.

**Comment by jtarchie** [comment]
Comments in golang YAML are also not easy. We'd just be doing `"# om version: x.x.x` + yaml.Marshal`. It feels _weird_.

**Comment by aegershman** [comment]
That makes sense, but gross. Not to mention, it wouldn't provide as much benefit as I felt in that moment. It'd just be clutter that wouldn't actually provide benefit... not to mention x2 the inevitable "can appending/prepending this be toggleable?", so then you'd have a flag for it.

not to mention x3, if you really _really_ wanted to do this, you could always do something like this:

```sh
om staged-config blahblahblah > example.yml
echo "# $(om --version)" >> example.yml
```

This was a bad idea and I will be flogging myself for it. Thanks!
