### ISSUE TITLE
om --env support for traditional sso workflow

### ISSUE THREAD

**Issue by kcboyle** [pivotal-cf/om#459]
currently, `om` bypasses traditional sso by using `client_id` and `client_secret`

However, a user also has to go through this "mechanized" workflow and cannot take advantage of sso when interacting with `om` from the command line. [Concourse](https://concourse-ci.org/) has the ability to redirect to sso when logging in. Is this something `om` could take advantage of?

Can we reasonably support Ops Manager sso using the `om` comand line? What would be the gain for supporting sso on the command line? What is the effort involved in doing so? Is the gain worth the cost?

Split from #385

**Comment by jtarchie** [comment]
I'm not sure that the workflow with OpsManager API supports this.
I'd like to way in from somebody on the OpsManager team.

**Comment by ystros** [comment]
We believe this is possible with SAML / SSO, as it is currently possible with the `uaac` CLI.

1. Setup an Ops Manager configured with SAML and target `uaac` at it.
2. Use `uaac token sso get` command with the default `opsman` client and empty secret. You will be prompted to visit a URL to get a temporary passcode:
![Screen Shot 2020-03-13 at 4 05 51 PM](https://user-images.githubusercontent.com/145077/76665470-32f09d80-6545-11ea-8a7b-4c1c4404e97d.png)
3. That URL will prompt you to login with your SAML / SSO provider:
![Screen Shot 2020-03-13 at 4 06 39 PM](https://user-images.githubusercontent.com/145077/76665415-fc1a8780-6544-11ea-88c5-2bcda2bdd9c9.png)
4. After logging in, UAA will provide you with a temporary passcode:
![Screen Shot 2020-03-13 at 4 06 49 PM](https://user-images.githubusercontent.com/145077/76665433-0e94c100-6545-11ea-89bd-c1a99900a9e3.png)
5. Paste the passcode into the `uaac` prompt, and it will authenticate w/ a token:
![Screen Shot 2020-03-13 at 4 07 08 PM](https://user-images.githubusercontent.com/145077/76665453-1fddcd80-6545-11ea-8a84-495f117521c1.png)

We believe it should be possible for `om` to follow a similar flow. Additionally, you could support user authentication for Ops Manager's using internal auth or LDAP - the corresponding `uaac` command to. get the token would be `uaac token owner get`.

**Comment by kcboyle** [comment]
This workflow might be able to work if we had more of an `om login` workflow, but there are a couple other issues

1. we don't know where to configure sso in the opsman api.
1. work for sso support is going to be non-trivial. We're not sure how to integrate uaac into `om`, or if we need to package it, or how to handle this dependency (or use it properly)
1. the team has a general lack of knowledge and no testing auth for ldap or saml, so validating it is implemented correctly will be difficult.
1. supporting sso in env.yml seems counter to the point of env.yml (which makes things very hands-off and nice for automation, because it allows for a hands-free workflow). 

however, if we ever implement an `om login`, perhaps we can revisit this issue and talk about how we might implement this. For now, I'm going to close this issue.
