### ISSUE TITLE
docs for commands should alert viewers that they are auto-generated

### ISSUE THREAD

**Issue by jtarchie** [pivotal-cf/om#480]
`go run docsgenerator/update-docs.go` is how we keep the basic readmes up to date
We should document how to use this tool, and give an "automatically generated" message in the docs.

**Comment by kcboyle** [comment]
We actually do alert users that the docs are auto-generated, but it is cleverly hidden from the github interface. It is, however, visible in the generated readme files directly. Added documentation for how to use docsgenerator in a readme.

```
<!--- This file is autogenerated from the files in docsgenerator/templates/activcommand-name --->
&larr; [back to Commands](../README.md)
```
