### ISSUE TITLE
om curl --data  should accept a filename as input, similar to actual curl

### ISSUE THREAD

**Issue by drawsmcgraw** [pivotal-cf/om#481]
Hi there!

When I'm using `curl` (the *nix command, not the `om` subcommand), I can POST data from a file like so:

```
curl .... -d @file-with-json
```

But as of my understanding, `om curl .... --data` does not behave in the same way. I can _only_ pass in my data with a string. This breaks user expectations, in my opinion.

Adding the ability for `om curl --data` to send data from a file puts us in alignment with user expectations and would be really helpful for human operators.

We wouldn't even necessarily need to override the existing `--data` flag. We could just have a `--data-file` or some other distinct flag to avoid complicating the situation.

Thoughts? Any challenges with implementing this?

**Comment by jtarchie** [comment]
Why not `om curl --data "$(cat file-with-json)"`?

**Comment by drawsmcgraw** [comment]
@jtarchie would you believe I tried that approach with every other combination of quotes, escaped quotes, etc? And completely overlooked double quotes?

I just tried your recommendation and it worked perfectly. Apologies for the noise. Closing now.
