### ISSUE TITLE
explore: mapping config structs to API endpoints

### ISSUE THREAD

**Issue by jtarchie** [pivotal-cf/om#486]
The OpsMan API is _mainly_ RESTFUL.
The config files for a product and director are almost one-to-one mappings of the endpoints.

I'd like to explore building a package.
That given a specifically designed struct (that represents a YAML config file) can just perform the RESTFUL endpoint calls.
This would be bi-directional.
Meaning, the struct represents both something that can be set and hydrated (ie `configure-product` and `staged-config`).

We have a lot of repeated code of handling errors from the endpoint.
I think we could simplify a lot of this now that we do understand the patterns.

**Comment by kcboyle** [comment]
There's a great pattern in ruby that inspired this issue. Go does not have a lot of the convenience functions and support for this kind of pattern without significant design changes that will more-than-likely be far more trouble than the gain we get out of it.
