### ISSUE TITLE
On Windows om interpolate requires a double slash in the path

### ISSUE THREAD

**Issue by laidbackware** [pivotal-cf/om#491]
When using om for Windows in git bash, interpolate expects the path to start with an extra slash compared to the linux and native Windows behavior.

```
# This is the linux behaviour, but is broken in Git Bash
$  om interpolate -c ./terraform-output.yml --path "/availability_zones"
could not execute "interpolate": cannot parse path:
Expected to start with '/'

# Only way to make it work in Windows under Git Bash
$  om interpolate -c ./terraform-output.yml --path "//availability_zones"
- eu-west-1a
- eu-west-1b
- eu-west-1c

# In Git Bash all references below the parent are broken even with multiple slashes.
$  om interpolate -c ./terraform-output.yml --path "//availability_zones/0"
could not execute "interpolate": Expected to find a map key '' for path '/' (found map keys:

$  om interpolate -c ./terraform-output.yml --path "//availability_zones//0"
could not execute "interpolate": Expected to find a map key '' for path '/' (found map keys:

# Correct behavior from the Windows command prompt:
C:\git\aws-concourse (master -> origin)
λ  om interpolate -c ./terraform-output.yml --path "/availability_zones"
- eu-west-1a
- eu-west-1b
- eu-west-1c

C:\git\aws-concourse (master -> origin)
λ  om interpolate -c ./terraform-output.yml --path "/availability_zones/0"
eu-west-1a
```

**Comment by kcboyle** [comment]
Hi @laidbackware ! I will admit we aren't able to do testing on windows normally, and I'm sorry this has been an issue for y'all! (but I _am_ glad there's a (non-optimal) workaround). We based `om interpolate` off of `bosh interpolate`. Could you run a quick test for me to see if `bosh interpolate` works, or has the same error?

**Comment by laidbackware** [comment]
> Hi @laidbackware ! I will admit we aren't able to do testing on windows normally, and I'm sorry this has been an issue for y'all! (but I _am_ glad there's a (non-optimal) workaround). We based `om interpolate` off of `bosh interpolate`.
> 
> Could you run a quick test for me to see if `bosh interpolate` works, or has the same error? It's still something we'd have to fix in `om`, but would like to bubble up the issue if it exists in both places

We've found the same behaviour in bosh too. We're working with a customer who is a Windows shop, but ideally want the script to work in Linux proper hence the issue. Would you recommend raising it with the BOSH team?

**Comment by laidbackware** [comment]
On further research it looks like this is a 'feature' of running Git Bash on Windows, because the translation layer will always assume a string starting a single slash references a disk and substitute c:\

https://web.archive.org/web/20160309155620/http://oldwiki.mingw.org/index.php/switches%20with%20forward%20slashes

**Comment by kcboyle** [comment]
@laidbackware is there anything we can do on the `om` side to mitigate the double slash requirement, then?

Perhaps a solution here would be to, instead of erroring, put a forward slash in the path? I'm a little wary about that, because changing the input from a user without being transparent about it can introduce issues

**Comment by kcboyle** [comment]
It looks like this is a known issue for gitbash: https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md#known-issues

closing this issue!
