### ISSUE TITLE
delete availability zones if no longer listed in the `configure-director` config

### ISSUE THREAD

**Issue by jtarchie** [pivotal-cf/om#497]
`configure-director` will update or create new availability zones, but [does not appear to delete them ](https://github.com/pivotal-cf/om/blob/master/api/director_service.go#L98-L133)

a use case for deleting availability zones for ops manager - an availability zone (vsphere) was configured incorrectly and needed to be removed, and/or ops manager could not communicate with that AZ. There is no way to remove those AZs through `configure-director`

**Comment by jaristiz** [comment]
Hi, I've been following the conversation on this issue and found out that this is considered a nice-to-have feature, for that, I encourage you to create a PR with the changes, for now I'll be closing this issue until further information comes our way.
