### ISSUE TITLE
upload-stemcell requires absolute filepath when filename contains brackets

### ISSUE THREAD

**Issue by drawsmcgraw** [pivotal-cf/om#498]
When `om download-product` downloads a stemcell, the stemcell filename is prefixed with brackets for metadata (i.e. `[product-slug,product-version]product-filename.tgz`).

When `om upload-stemcell` is used on files with names like this, the upload fails with a message similar to the following:
``` 
could not execute "upload-stemcell": failed to upload stemcell: open tmp-download/light-bosh-stemcell-456.100-aws-xen-hvm-ubuntu-xenial-go_agent.tgz: no such file or directory
```

In the above example, the command run was:
```
om -k upload-stemcell --floating=true --stemcell "$DOWNLOAD_DIR"/*.tgz
```

And `DOWNLOAD_DIR` has the value `tmp-download`.

My expectation was that relative paths would be fine but it looks like it requires absolute paths.

Understanding that a fix to the behavior may be nontrivial, maybe the docs/help output could be amended to say as much regarding absolute/relative paths?

**Comment by kcboyle** [comment]
Hi @drawsmcgraw! Our team has other things that we are focusing on at the moment, and would prefer to just document that you have to use an absolute path.

If you would like to submit a PR so `upload-stemcell` can support relative paths, we are more than happy to review and accept it though. Let us know your thoughts.

**Comment by drawsmcgraw** [comment]
Thanks @kcboyle! Completely understand the priorities and I agree that the most reasonable path is to document the need. I'm not sure where the best place for that is (help output? official docs?) but I'd be happy to file a docs PR if you point me in the right direction.

**Comment by kcboyle** [comment]
Hi! 
We will be able to get around to the documentation (if you have other things your working on) but I see a good place for this just straight in the help for the command)
```bash
om upload-stemcell -h

This command will upload a stemcell to the target Ops Manager. Unless the force flag is used, if the stemcell already exists that upload will be skipped

Usage:
  om [options] upload-stemcell [<args>]

Flags:
  --config, -c    string             path to yml file for configuration (keys must match the following command line flags)
  --floating      string             assigns the stemcell to all compatible products  (default: true)
  --force, -f     bool               upload stemcell even if it already exists on the target Ops Manager
  --shasum        string             shasum of the provided product file to be used for validation
  --stemcell, -s  string (required)  path to stemcell
```

we could update `--stemcell` to have a description of "the absolute filepath to the stemcell" maybe. Where would you have found it the most helpful when debugging?

**Comment by drawsmcgraw** [comment]
I would have certainly found it in the help output. I would suggest making it a little more on-the-nose, though, because I'm extremely hard-headed. Something along the lines of :

```
--stemcell, -s  string (required)  path to stemcell (NOTE: use absolute path)
```

**Comment by kcboyle** [comment]
Sounds good to me! Happy to accept a PR if you are so inclined, or we will get to this eventually :)

**Comment by kcboyle** [comment]
actually, this literally took less time to do than we talked about it. Should be fixed now (on `main`)

**Comment by kcboyle** [comment]
@drawsmcgraw we were taking a look at this again, and are adding support for relative paths.

It should come out in the next release of `om`
