### ISSUE TITLE
Looking for a sample Ops Manager config file for AWS

### ISSUE THREAD

**Issue by ichandan16** [pivotal-cf/om#500]
Hi Team, Is there a sample ops manager config file (`configure-opsman`) available?

Thanks,
Chandan

**Comment by jtarchie** [comment]
Which config file are you referring to?

**Comment by ichandan16** [comment]
Hi @jtarchie I am looking for a config file for `configure-ops man `

**Comment by jtarchie** [comment]
Configuring OpsMan is not IAAS specific. An example of the config file is at the bottom of that page.
