### ISSUE TITLE
configure-product for collection containing secret changes item order

### ISSUE THREAD

**Issue by mrdavidlaing** [pivotal-cf/om#509]
# Overview

_This documents a known issue that manifests when using`om v6.1.3+` in a GitOps workflow; related to #207 and #505_

When using `om configure-product` to edit a collection item; the item is moved to the end of the collection array.  This only occurs is the collection item contains a credential as one of its properties.

`om bosh-diff` then shows that *all* the collection items will change; both the intended property change AND a change in order for all the other items in the collection.

# Details
The following example gives more concrete details:

Assume a deployment of OpsMgr v2.10 and TAS v2.10.3.  Configuration for TAS has been extracted to `cf.config.yml`; which contains the following deployed config for the `.properties.cloud_controller_encryption_keys` collection property:

```yaml
.properties.cloud_controller_encryption_keys:
    value:
    - encryption_key:
        secret: supersecretlabelforencryptionlabel1
      label: Label 01 (see Lastpass > CloudOps SF > cloud_controller_encryption_keys)
      primary: true
    - encryption_key:
        secret: evenmoresupersecretelabelforlabel02
      label: Label 02 (see Lastpass > CloudOps DUB > cloud_controller_encryption_keys)
      primary: false
```

This property results in the following deployed configuration for the Cloud Controller:

```
$ bosh ssh -d cf-909decb33c34d4321b9d control/0 --command='cat /var/vcap/jobs/cloud_controller_ng/config/cloud_controller_ng.yml' | grep -A4 database_encryption | sed 's/.*|//g'
 database_encryption:
   keys: {"Label 01 (see Lastpass > CloudOps SF > cloud_controller_encryption_keys)":"supersecretlabelforencryptionlabel1","Label 02 (see Lastpass > CloudOps DUB > cloud_controller_encryption_keys)":"evenmoresupersecretelabelforlabel02"}
   current_key_label: "Label 01 (see Lastpass > CloudOps SF > cloud_controller_encryption_keys)"
   pbkdf2_hmac_iterations: 2048
```

The CloudOps SF team want to update the label for the first key to reflect a re-org of their password management, so they make the following change to `cf.config.yml`:

```diff
     - encryption_key:
         secret: supersecretlabelforencryptionlabel1
-      label: Label 01 (see Lastpass > CloudOps SF > cloud_controller_encryption_keys)
+      label: Label 01 (see Lastpass > vividskyblue.example.org > cloud_controller_encryption_keys)
       primary: true
     - encryption_key:
         secret: evenmoresupersecretelabelforlabel02
```

Committing this change triggers a pipeline to update the configuration of the environment; uses a command similar to:

`./om-6.1.3 configure-product --config cf.config.yml && ./om-6.1.3 bosh-diff`.

This appears to be a much larger change than was intended:

```diff
## Product Manifest for cf

 instance_groups:
 - name: control
   jobs:
   - name: cloud_controller_ng
     properties:
       cc:
         database_encryption:
           keys:
+          - label: Label 02 (see Lastpass > CloudOps DUB > cloud_controller_encryption_keys)
+            encryption_key: "((/opsmgr/cf-909decb33c34d4321b9d/cloud_controller_encryption_keys/0/encryption_key.value))"
+            active: false
+          - label: Label 01 (see Lastpass > vividskyblue.example.org > cloud_controller_encryption_keys)
+            encryption_key: "((/opsmgr/cf-909decb33c34d4321b9d/cloud_controller_encryption_keys/1/encryption_key.value))"
+            active: true
-          - label: Label 01 (see Lastpass > CloudOps SF > cloud_controller_encryption_keys)
-            encryption_key: "((/opsmgr/cf-909decb33c34d4321b9d/cloud_controller_encryption_keys/0/encryption_key.value))"
-            active: true
-          - label: Label 02 (see Lastpass > CloudOps DUB > cloud_controller_encryption_keys)
-            encryption_key: "((/opsmgr/cf-909decb33c34d4321b9d/cloud_controller_encryption_keys/1/encryption_key.value))"
-            active: false
...[snip]...
```

Specifically; whilst `Label 01` is changing as intended; so is the order of all items.

This change of order will flow through to the deployed configuration for the Cloud Controller

```
$ bosh ssh -d cf-909decb33c34d4321b9d control/0 --command='cat /var/vcap/jobs/cloud_controller_ng/config/cloud_controller_ng.yml' | grep -A4 database_encryption | sed 's/.*|//g'
 database_encryption:
   keys: {"Label 02 (see Lastpass > CloudOps DUB > cloud_controller_encryption_keys)":"evenmoresupersecretelabelforlabel02","Label 01 (see Lastpass > vividskyblue.example.org > cloud_controller_encryption_keys)":"supersecretlabelforencryptionlabel1"}
   current_key_label: "Label 01 (see Lastpass > vividskyblue.example.org > cloud_controller_encryption_keys)"
   pbkdf2_hmac_iterations: 2048
```

Fortunately; whilst the order has changed; the values of the associated items and their credentials have not changed.

# Next steps:

We believe that this edge case will be encountered so infrequently that it is not worth addressing.  Comments and or PRs against this issue can reverse this decision.

**Comment by mrdavidlaing** [comment]
Inspecting the JSON sent to the OpsMgr API during `om configure-product` reveals that the order of the collection items isn't being changed by `om`:

```json
".properties.cloud_controller_encryption_keys": {
      "value": [
        {
          "encryption_key": {
            "secret": "supersecretlabelforencryptionlabel1"
          },
          "label": "Label 01 (see Lastpass > vividskyblue.example.org > cloud_controller_encryption_keys)",
          "primary": true
        },
        {
          "encryption_key": {
            "secret": "evenmoresupersecretelabelforlabel02"
          },
          "guid": "de6fdfd7-e288-431b-b5fe-a7fd9ed766a7",
          "label": "Label 02 (see Lastpass > CloudOps DUB > cloud_controller_encryption_keys)",
          "primary": false
        }
      ]
    },
```

Rather; the problem is that `om` is unable to identify the existing `guid` associated with the collection item since the collection doesn't have a logical key property.  

This causes OpsMgr to delete the existing `Label 01` item and create a new `Label 01` with a new GUID (at the end); resulting in the order of the items in the collection changing.

**Comment by kcboyle** [comment]
We're going to revert these changes for now. there are more edge cases we are discovering that are blocking folks. 6.3.1 will revert these changes. see #207 for more details
