### ISSUE TITLE
Retrieve UAA admin credential / admin client credential

### ISSUE THREAD

**Issue by vinceyang15** [pivotal-cf/om#51]
Hi,

Is it possible to retrieve UAA admin credentials and admin client credentials?

**Comment by davewalter** [comment]
Hi,

Once you have a deployed ERT, you could use `om curl` to retrieve a credential from the Ops Manager API using the `/api/v0/deployed/products/:product_guid/credentials/:credential_reference` GET endpoint, which returns a JSON object. See the docs on your Ops Manager at `/docs#credentials-fetching-a-credential-for-a-deployed-product` for details. As mentioned in the docs, you would need to know the product guid, which you can get from the `/api/v0/deployed/products` GET endpoint, and the credential reference.

Hope this helps,
Dave

**Comment by zachgersh** [comment]
@vinceyang15 - going to close as the answer above should be the right way to go about it.
