### ISSUE TITLE
Escape special character like +,| in password on om-cli

### ISSUE THREAD

**Issue by san4ever** [pivotal-cf/om#510]
for opsmanager password i have characters like (+,| )
How to escape these characters. Tried giving \ to ignore those but it didn't work
Please suggest on this

**Comment by jtarchie** [comment]
@san4ever, on what OS are you on here? There are different escaping rules for each.

In `bash` (for Linux) you can use `"` to surround the password.
For example, `om -u admin -p "secure password|"`.

**Comment by san4ever** [comment]
using a concourse pipeline

**Comment by kcboyle** [comment]
@san4ever did surrounding the password in `"` work? 

if not, can you tell us _exactly_ what you are running and where it fails?
Doing some preliminary tests:

I tried to change the Ops Manager basic auth login password to `password|` and Ops Manager returned an error, and would not let me do so

I changed the Ops Manager basic auth login password to `password+`
- run `om --username user --password "password+" --target domain.com staged-products` and was able to complete successfully. 

Can you tell us how to reproduce this problem?

**Comment by kcboyle** [comment]
@san4ever I'm going to close out this issue. If this is still a problem for you, please feel free to reopen, and give us some steps to reproduce so that we can better help you to troubleshoot this issue.
