### ISSUE TITLE
Equivalent of tile-config-generate display using om product-metadata

### ISSUE THREAD

**Issue by arungskumar** [pivotal-cf/om#513]
I am trying to display any given products configuration similar to `tile-config-generate display`, using `om product-metadata`.  Whenever I try the same, does not display the entire product config details,

`om product-metadata --product-path FILE
could not execute "product-metadata": you must specify product-name and/or product-version`

and as expected, with product-name or version, outputs respective value.

Could you please help me in getting this issue fixed.

**Comment by jtarchie** [comment]
There is no way to do this in `om`. The command `config-template` will output the YAML files equivalent to `tile-config-generate`. Are you able to use that?

**Comment by arungskumar** [comment]
Yes, using `om config-template` we are able to create equivalent YAML files. After this, we display the product properties using `tile-config-generate`. So, trying to remove dependency with this `tile-config-generate`.

**Comment by jtarchie** [comment]
Can you explain more what the value `display` provides? We always heard it was an extraneous step.

**Comment by arungskumar** [comment]
So, this tile-config-generator `display` option provides details of all the vars, files, parameter names to configure given product and we use it as a reference to configure the product. For event-alerts, display output would be something like below

`*****  Required Properties ******* (product.yml) 
+-------------------------------------------------------------+---------------------------------------------------+
|                            NAME                             |                     PARAMETER                     |
+-------------------------------------------------------------+---------------------------------------------------+
| .deploy-pcf-event-alerts.instance_count                     | deploy-pcf-event-alerts/instance_count            |
+-------------------------------------------------------------+---------------------------------------------------+
| .deploy-pcf-event-alerts.metrics_forwarder_enabled          | deploy-pcf-event-alerts/metrics_forwarder_enabled |
+-------------------------------------------------------------+---------------------------------------------------+
| .properties.mysql.internal.plan_name                        | mysql/internal/plan_name                          |
+-------------------------------------------------------------+---------------------------------------------------+
| .properties.smtp_selector.enabled.smtp_address              | smtp_selector/enabled/smtp_address                |
+-------------------------------------------------------------+---------------------------------------------------+
| .properties.smtp_selector.enabled.smtp_from                 | smtp_selector/enabled/smtp_from                   |
+-------------------------------------------------------------+---------------------------------------------------+
| .properties.smtp_selector.enabled.smtp_insecure_skip_verify | smtp_selector/enabled/smtp_insecure_skip_verify   |
+-------------------------------------------------------------+---------------------------------------------------+
| .properties.smtp_selector.enabled.smtp_port                 | smtp_selector/enabled/smtp_port                   |
+-------------------------------------------------------------+---------------------------------------------------+
| .properties.smtp_selector.enabled.smtp_tls_enabled          | smtp_selector/enabled/smtp_tls_enabled            |
+-------------------------------------------------------------+---------------------------------------------------+

*****  Default Property Values ******* (product-default-vars.yml) 
+---------------------------------------------------+-------+
|                     PARAMETER                     | VALUE |
+---------------------------------------------------+-------+
| deploy-pcf-event-alerts/instance_count            | 5     |
+---------------------------------------------------+-------+
| deploy-pcf-event-alerts/metrics_forwarder_enabled | true  |
+---------------------------------------------------+-------+
| smtp_selector/enabled/smtp_insecure_skip_verify   | false |
+---------------------------------------------------+-------+
| smtp_selector/enabled/smtp_tls_enabled            | true  |
+---------------------------------------------------+-------+

*****  Required Properties With No Default *******
+------------------------------------+
|             PARAMETER              |
+------------------------------------+
| network_name                       |
+------------------------------------+
| singleton_availability_zone        |
+------------------------------------+
| mysql/internal/plan_name           |
+------------------------------------+
| smtp_selector/enabled/smtp_address |
+------------------------------------+
| smtp_selector/enabled/smtp_from    |
+------------------------------------+
| smtp_selector/enabled/smtp_port    |
+------------------------------------+

*****  Resource Property Values ******* (resource-vars.yml) 
+----------------------------------------+-----------+
|               PARAMETER                |   VALUE   |
+----------------------------------------+-----------+
| deploy-pcf-event-alerts_instance_type  | automatic |
+----------------------------------------+-----------+
| destroy-pcf-event-alerts_instance_type | automatic |
+----------------------------------------+-----------+

*****  Errand Property Values ******* (errand-vars.yml) 
+--------------------------------------------+---------+
|                 PARAMETER                  |  VALUE  |
+--------------------------------------------+---------+
| deploy-pcf-event-alerts_post_deploy_state  | default |
+--------------------------------------------+---------+
| deploy-pcf-event-alerts_pre_delete_state   | default |
+--------------------------------------------+---------+
| destroy-pcf-event-alerts_post_deploy_state | default |
+--------------------------------------------+---------+
| destroy-pcf-event-alerts_pre_delete_state  | default |
+--------------------------------------------+---------+

*****  Features Operations Files ******* 
+-------------------------------------+------------------------------------+
|                FILE                 |             PARAMETERS             |
+-------------------------------------+------------------------------------+
| features/mysql-external.yml         | mysql/external/host                |
|                                     | mysql/external/port                |
|                                     | mysql/external/username            |
|                                     | mysql/external/password            |
|                                     | mysql/external/database            |
|                                     | mysql/external/use_tls             |
|                                     | mysql/external/skip_ssl_validation |
+-------------------------------------+------------------------------------+
| features/smtp_selector-disabled.yml |                                    |
+-------------------------------------+------------------------------------+

*****  Optional Operations Files ******* 
+---------------------------------------------------------+----------------------------------------------------+
|                          FILE                           |                     PARAMETERS                     |
+---------------------------------------------------------+----------------------------------------------------+
| optional/add-mysql-external-client_cert_credentials.yml | mysql/external/client_cert_credentials/certificate |
|                                                         | mysql/external/client_cert_credentials/privatekey  |
+---------------------------------------------------------+----------------------------------------------------+
| optional/add-mysql-external-server_ca.yml               | mysql/external/server_ca                           |
+---------------------------------------------------------+----------------------------------------------------+
| optional/add-smtp_selector-enabled-smtp_credentials.yml | smtp_selector/enabled/smtp_credentials_password    |
|                                                         | smtp_selector/enabled/smtp_credentials_identity    |
+---------------------------------------------------------+----------------------------------------------------+

*****  Resource Operations Files ******* 
+----------------------------------------------------------------+---------------------------------------------------+
|                              FILE                              |                    PARAMETERS                     |
+----------------------------------------------------------------+---------------------------------------------------+
| resource/deploy-pcf-event-alerts_additional_vm_extensions.yml  | deploy-pcf-event-alerts_additional_vm_extensions  |
+----------------------------------------------------------------+---------------------------------------------------+
| resource/deploy-pcf-event-alerts_elb_names.yml                 | deploy-pcf-event-alerts_elb_names                 |
+----------------------------------------------------------------+---------------------------------------------------+
| resource/deploy-pcf-event-alerts_internet_connected.yml        | deploy-pcf-event-alerts_internet_connected        |
+----------------------------------------------------------------+---------------------------------------------------+
| resource/deploy-pcf-event-alerts_nsx_security_groups.yml       | deploy-pcf-event-alerts_nsx_security_groups       |
+----------------------------------------------------------------+---------------------------------------------------+
| resource/destroy-pcf-event-alerts_additional_vm_extensions.yml | destroy-pcf-event-alerts_additional_vm_extensions |
+----------------------------------------------------------------+---------------------------------------------------+
| resource/destroy-pcf-event-alerts_elb_names.yml                | destroy-pcf-event-alerts_elb_names                |
+----------------------------------------------------------------+---------------------------------------------------+
| resource/destroy-pcf-event-alerts_internet_connected.yml       | destroy-pcf-event-alerts_internet_connected       |
+----------------------------------------------------------------+---------------------------------------------------+
| resource/destroy-pcf-event-alerts_nsx_security_groups.yml      | destroy-pcf-event-alerts_nsx_security_groups      |
+----------------------------------------------------------------+---------------------------------------------------+

*****  Network Operations Files ******* 
+--------------------------------+------------+
|              FILE              | PARAMETERS |
+--------------------------------+------------+
| network/2-az-configuration.yml | az2_name   |
+--------------------------------+------------+
| network/3-az-configuration.yml | az2_name   |
|                                | az3_name   |
+--------------------------------+------------+`

**Comment by kcboyle** [comment]
@arungskumar aren't all of the values displayed easily navigable in the folder (file names) or present in the generated vars files?

@calebwashburn could we ask you to weigh in on this conversation as well?

**Comment by calebwashburn** [comment]
The original intent of the `display` command was when we were running the `tile-config` tool in a pipeline where it was a bit harder to see all the files, etc as they were in a task container.  With the move to `om` we have recommended you run that tool at design time to understand all the `ops-files`, `vars`, etc that are available and use a text editor tool to search for properties, etc to better understand if you want to configure a property use this ops-file which then will require these new properties.  You can then do all this discovery prior to committing assets to source control to tighten the feedback loop on things.    So while it's not a direct replacement changing how you use these generated files/commands you can get to the same outcome (actually argue it's better as you find issues prior to commit -> run -> error).

**Comment by arungskumar** [comment]
Yes @kcboyle, we are able to navigate in the generated files. Thanks @calebwashburn for the detailed explanation on the options.
