### ISSUE TITLE
`upload-stemcell` is not respecting the prefixed stemcell files

### ISSUE THREAD

**Issue by jtarchie** [pivotal-cf/om#517]
```
om --env env/foundations/config/env.yml upload-stemcell --stemcell 'downloaded-stemcell/[stemcells-ubuntu-xenial,456.123]light-bosh-stemcell-456.123-google-kvm-ubuntu-xenial-go_agent.tgz' --floating=true
processing stemcell
2020/10/15 16:49:09 could not execute "upload-stemcell": failed to upload stemcell: open downloaded-stemcell/light-bosh-stemcell-456.123-google-kvm-ubuntu-xenial-go_agent.tgz: no such file or directory
```

It appears that the symlink being create in the `upload-stemcell` is not being honored (or created)!?

Possibly?
* version of golang
* ubuntu linux sys call

**Comment by kcboyle** [comment]
This is not a direct issue in `om`, but for platform automation. The task that ran this `om` command did not use the absolute path, which is known, and intentional functionality for `upload-stemcell`

**Comment by kcboyle** [comment]
closing this issue. Commenting on #498, as this expressed the root of the problem. We will be releasing a solution
