### ISSUE TITLE
bool flag `--stemcell-heavy' cannot have an argument

### ISSUE THREAD

**Issue by lerytke** [pivotal-cf/om#521]
starting with om version 7 

when downloading stemcells using a download-product.yml
pivnet-api-token: ((pivnet-refresh-token))
pivnet-file-glob: "cf*.pivotal"
pivnet-product-slug: elastic-runtime
product-version-regex: ^2\.10\..*$
stemcell-iaas: aws
stemcell-heavy: true

om download-product --config download-product.yml --output-directory ./ downloaded-stemcell --source pivnet
2020/11/20 08:37:33 bool flag `--stemcell-heavy' cannot have an argument

this worked fine with version 6.5.0

**Comment by lerytke** [comment]
it works when not using a file with settings like 

om download-product -s pivnet -o ./ -p elastic-runtime -r ^2\.10\..*$ --stemcell-heavy --stemcell-iaas=aws -f "cf*.pivotal" -t <redacted>
attempting to download the file product-files/elastic-runtime/cf-2.10.9-build.6.pivotal from source pivnet
cf-2.10.9-build.6.pivotal already exists, skip downloading
Downloading stemcell
attempting to download the file product-files/stemcells-ubuntu-xenial/bosh-stemcell-621.92-aws-xen-hvm-ubuntu-xenial-go_agent.tgz from source pivnet
 503.88 MiB / 503.88 MiB [=========================================] 100.00% 11s
calculating sha sum for bosh-stemcell-621.92-aws-xen-hvm-ubuntu-xenial-go_agent.tgz.partial
Writing a list of downloaded artifact to download-file.json
Writing a assign stemcell artifact to assign-stemcell.yml

**Comment by jtarchie** [comment]
Thanks for the report, working on getting a fix out shortly.

**Comment by jtarchie** [comment]
The fixed for this will be released in 7.0.2, shortly.

**Comment by jtarchie** [comment]
@lerytke can you please confirm it works for you? We've tested against, but would like you to confirm and close the issue.

**Comment by lerytke** [comment]
yes, it is fixed now thanks
