### ISSUE TITLE
nom alias for vm-lifecycle is broken

### ISSUE THREAD

**Issue by 0xRand0m** [pivotal-cf/om#527]
Hi there,
since only `vm-lifecycle` is present in [cmdConfigBypassList](https://github.com/pivotal-cf/om/blob/745890501c6d1523a6e8d7ab80cbcfd76ae4da97/cmd/loadConfigFile.go#L30) but not `nom`, the command line parser chokes on the parsed config file passed in via `--config`.
Simply adding `nom` to the list will resolve the issue.
Maybe there's a more elegant way to handle command aliases but I'm no gogrammer and there's only that single command alias as far as I can tell ;)

Edit: I was using the `create-vm` subcommand. Don't know about the others.

**Comment by jtarchie** [comment]
I don't know if there is an elegant way at the moment.
I'll add it to the bypass list at the moment.
We'll rethink this.
