### ISSUE TITLE
allow adding jobs to the bosh director for agents

### ISSUE THREAD

**Issue by jtarchie** [pivotal-cf/om#529]

**Comment by jtarchie** [comment]
This requires more investigation. Adding things to the bosh director config should be simpler. It appears that this may take a little effort at the moment. :-/

**Comment by xyloman** [comment]
+1 as we have use cases to apply antivirus and file integrity monitoring on the director for compliance reasons.

**Comment by jaristiz** [comment]
As no comments were made after the last post, I am going to close this one and reopen it if the conversation gains some traction.
