### ISSUE TITLE
leverage declarative approach of config files to API endpoints

### ISSUE THREAD

**Issue by jtarchie** [pivotal-cf/om#530]
The configure-* and staged-* are representations of the same data. One is a series of GETs and the other a series of POSTs/DELETEs, with some data transformation in there.

I'd like to explore a more declarative approach to this.
Right now, the overhead of adding a new endpoint relies on a lot of copy-pasta.
There are patterns for hydration from other languages, which we could take influence from.

This is just to capture the exploratory of this work.

**Comment by jtarchie** [comment]
This is an example. https://github.com/jtarchie/om-mini/blob/main/commands/staged_ops_manager.go

**Comment by jaristiz** [comment]
As no comments were made after the last post, I am going to close this one and reopen it if the conversation gains some traction.
