### ISSUE TITLE
When hitting auth API endpoints, check that auth has started

### ISSUE THREAD

**Issue by jtarchie** [pivotal-cf/om#535]
After have upgraded an OpsManager, the authentication was still starting, and return an error.

```
2021/01/08 16:41:21 request failed: unexpected response from /api/v0/settings/banner:
HTTP/1.1 503 Service Unavailable
5a
{"errors":{"base":["Authentication is starting up. Please try again in a few minutes."]}}
```

Should we retry internally?

**Comment by jaristiz** [comment]
Hi @jtarchie ,

This seems like a problem for which we may need more context, but we encourage you to start a PR with the changes.
If no answer I'll close this issue.
