### ISSUE TITLE
om vm-lifecycle export-opsman-config

### ISSUE THREAD

**Issue by pcf-user** [pivotal-cf/om#538]
om --version

7.2.0

om -k -t https://opsman.FQDN -c USER   -s PASSWORD  vm-lifecycle export-opsman-config --state-file=$PWD/1 --vsphere-url=https://VCENTER_URL --vsphere-username=DOMAIN\VCenter_USER --vsphere-password=VC_PASS

2021/02/08 11:32:55 could not parse url: parse "https://DOMAIN\VCenter_USER:VC_PASS@VCENTER_URL/sdk": net/url: invalid userinfo

Can you give examples how to pass vcenter variables?

**Comment by pcf-user** [comment]
could not parse url: parse https://VCENTER_URL invalid URL escape "%"

is what I get when I try to escape special characters in the Vcenter Password

**Comment by jaristiz** [comment]
This seems like a problem at the user end, as no more information or follow-up comments were made I am going to consider this matter closed.
