### ISSUE TITLE
`om download-product` output is not compatible with `om assign-multi-stemcell`

### ISSUE THREAD

**Issue by hoegaarden** [pivotal-cf/om#539]
What we'd like to see but currently does not work:

> As a user of om
> I want to use the config from `om download-product` for `om assign-mulit-stemcell`
> So that I don't have to transform the output from the former command to successfully run the later command

Observation:

The stemcell assignment config generated by `om download-product` is incompatible with `om assign-multi-stemcell`

- using the [download-product task] (internally using `om download-product`) generates a stemcell assignment config of the following form:  
  ```json
  {
    "product": "$product",
    "stemcell": "$scVersion"
  }
  ```
- this stemcell assignment config is not compatible with the [assign-multi-stemcell task], which internally runs `om assign-multi-stemcell --config $stemcellAssignmentConfig`; this task / om command requires the config in the following form:  
  ```json
  {
    "product": "$product",
    "stemcell": [
      "${scLine}:${scVersion}"
    ]
  }
  ```

Hotfix, we have implemented:
- we created a new custom task, which runs  
  ```bash
  jq '.stemcell = [ "ubuntu-trusty:\(.stemcell)" ]'
  ```
  against the stemcell assignment config that the [download-product task] generated for us
- we run this custom task after the [download-product task] and before the [assign-multi-stemcell task]
- obviously, this is now hardcoding the stemcell line to `ubuntu-trusty`, only supports one stemcell, and of course breaks if the format of the stemcell assignment config would change -- in other words: this is literally just a hotfix to unblock us but no sustainable solution to the problem

Potential fix for `om`:
- `om download-product` should generate the stemcell assignment in the "new" format
- `om assign-stemcell` should
  - either be removed
  - or accept the "new" format, validate it and transform it to the "old" format internally and print a useful error message when that is not possible, e.g. because:
    - the config holds multiple stemcells and it is not clear which one to assign
    - the targeted opsman does not even support the `/api/v0/stemcell_assignments` API anymore
      - in that case, it should maybe just use the new API anway, maybe print a warning to tell the user they should switch to `assign-multi-stemcell`

Versions at play:
- opsman `2.9.12-build.198`
- platform automation automation toolkit `5.0.13`
- om `39fd21c57e46588e76bb07826a2d8809e29382e9-2021-01-12T08:23:20-07:00` (from the container image from platform automation toolkit)

Other notes:
- We download the product from an internal s3 (comaptible) storage service, and not directly from pivnet
- The stemcell assignment is compatible with the [assign-stemcell task] which runs `om assign-stemcell`, however we cannot use that task, because opsman 2.9.x has removed the `/api/v0/stemcell_assignments` API.

[download-product task]: https://docs.pivotal.io/platform-automation/v5.0/tasks.html#download-product
[assign-multi-stemcell task]: https://docs.pivotal.io/platform-automation/v5.0/tasks.html#assign-multi-stemcell
[assign-stemcell task]: https://docs.pivotal.io/platform-automation/v5.0/tasks.html#assign-stemcell

**Comment by hoegaarden** [comment]
cc: @kurtburak @bzhtux

**Comment by kurtburak** [comment]
We are waiting a bug fix for that issue.
