### ISSUE TITLE
UAA token returning as invalid during simultaneous authentication attempts

### ISSUE THREAD

**Issue by crhntr** [pivotal-cf/om#548]
When running many `om curls` occasionally ops manager returns a 401 error response. After some digging, it looks like an issue regarding multiple authentication attempts at the same time to UAA for the same client.

To reproduce this issue, run 2 while loops with a command like this `om -k -e env.yml -t <target> curl -s -p "/api/${SOME_AUTH_ENDPOINT}"`. In the ops manager logs, you should see something like: `When decoding UAA token, received: CF::UAA::InvalidToken - error response`.

**Comment by jaristiz** [comment]
Closing as the change was already committed to the main branch.
