### ISSUE TITLE
Upgrade Ops Manager OVA in vCenter

### ISSUE THREAD

**Issue by coryjett** [pivotal-cf/om#57]
It would be nice if this tool could either deploy an OVA to vCenter or (ideally) handle the entire migration from one version to the next (i.e. Ops Manager 1.8.x to Ops Manager 1.9.x) including:

- downloading the installation settings
- downloading the existing stemcells
- shutting down the existing appliance 
- uploading the ova
- uploading the installation settings.
- uploading the stemcells

**Comment by zachgersh** [comment]
Hey @coryjett,

Thanks for the issue. Some of the bits and pieces of this are outside of the scope of what we want `om` to be able to do (its really just a tool for interacting with an already provisioned ops manager).

It totally can export / import an installation, I assume that is what you mean by "settings". It also can upload stemcells.

Downloading stemcells, you have to bring the stemcells yourself as `om` is unconcerned as to whether you have grabbed your stemcell from `pivnet` or `bosh.io`.

We'd want terraform to fill in the gap you mentioned.  We use terraform to provision our ops managers but haven't actually gotten around to making the provider work in the ways that we would like.

**Comment by coryjett** [comment]
@zachgersh Thanks for the reply.  We'll keep an eye on terraform and see if that helps us fill the gap.

**Comment by zachgersh** [comment]
@coryjett no problem! We are here to help, I am going to close for now.
