### ISSUE TITLE
OM cli fails if --vsphere-password contains a slash

### ISSUE THREAD

**Issue by ryanmichaelsmith** [pivotal-cf/om#577]
If vSphere password contains a slash, OM cli fails to parse the URL that it generates. I've not found a workaround other than changing the password.

```
$ om -t https://opsman.domain.com -u admin -p om_password --skip-ssl-validation vm-lifecycle export-opsman-config --config-file=pae_config/opsman.yml --state-file=pae_config/state.yml --vsphere-username="Pivotal_vSphere_SVC" --vsphere-password="test/password" --vsphere-url=https://vsphere.domain.com
2022/01/07 15:18:47 could not parse url: parse "https://Pivotal_vSphere_SVC:test/password@vsphere.domain.com/sdk": invalid port ":test" after host
```

**Comment by jaristiz** [comment]
This seems related to the way `OM` builds the request for vSphere, further investigation may be needed to device an issue but for now, the workaround would be to change the password to not use `/` or other special characters.

**Comment by jaristiz** [comment]
I've created #578 with preliminary changes to support this kind of special character on vSphere, waiting for someone to review.

**Comment by sneal** [comment]
I wonder if the vSphere username shouldn't also be escaped
