### ISSUE TITLE
om nom export-config invalid memory address or pointer - Issue filed a 3rd time

### ISSUE THREAD

**Issue by viva0007** [pivotal-cf/om#588]
@dtimm @crhntr @pvaramballypivot :  Not sure how you guys are testing this and/or confirming this issue is fixed.

It is not fixed yet.

Filing an issue for a simple issue for a 3rd time. Please do not close the issue until it is fully tested.

Links to original issue 

https://github.com/pivotal-cf/om/issues/587
https://github.com/pivotal-cf/om/issues/585

**Comment by viva0007** [comment]
Hi Guys - Has there been any update?

**Comment by Spimtav** [comment]
Hello @viva0007 , i'm so so sorry for the delay!  i do have good news for you though - i was able to replicate the problem, create a build that fixes it, and release it publicly!  Please try [the new v7.8.0 release](https://github.com/pivotal-cf/om/releases/tag/7.8.0) and let me know if it works for you, too, and i'll keep this ticket open until i get confirmation.  Hope that this helps and sorry again for all the trouble!

**Comment by viva0007** [comment]
Thank you. Works fine. Please close the issue.
