### ISSUE TITLE
Update configure-ldap-authentication command to have an option to set ldap_max_search_depth

### ISSUE THREAD

**Issue by mstaplestanzutam** [pivotal-cf/om#601]
### Is your feature request related to a problem? Please describe.

ldap_max_search_depth is required as part of TAS 3.0, and while OpsMan will be updated to provide this with a value of 1 if this is not set, it would be nice to be able to set this value via OM so it can be included in automation. 

### Describe the solution you'd like

Inclusion of the ability to change ldap_max_search_depth in OM. 

### Describe alternatives you've considered

Operations Manager will be updated to ensure a value of 1 is added if their is no value set, but we have some use cases where being able to set this for automation purposes would be nice, especially if a value needs to be set.

**Comment by rhall-pivotal** [comment]
Merged https://github.com/pivotal-cf/om/pull/649
