### ISSUE TITLE
vmlifecycle upgrade-opsman command can't handle new filenames from pivnet

### ISSUE THREAD

**Issue by vChrisR** [pivotal-cf/om#604]
### Describe the bug

Since OpsMan 3.0.5 the filename of the downloaded OVA files look like this: ops-manager-vsphere-3.0.20+LTS-T.ova. This does not match the regex in https://github.com/pivotal-cf/om/blob/main/vmlifecycle/extractopsmansemver/do.go.
Which means that the upgrade-opsman command will always try to ugprade even if the verions acutally do match.

It works fine if you manually rename the file to include the build number but this is undesirable since download are mostly automated.

### Reproduction steps

1. run the opsman vmlifecylce upgrade-opsman command for an opsman version 3.0.5 or higher
2. Opsman will be ugpraded
3. Run the same command again, upgrade should not happen but it does since the versions don't match

### Expected behavior

When downloading the files from pivnet using the om command (e.g. from a pipeline) and the running the om vmlifecycle upgrade-opsman command the upgrade should only happen once. The second time the command is run with the same file the upgrade should not run.

**Comment by coffee-squirrel** [comment]
We've also recently noticed this.

For example: `ops-manager-vsphere-3.0.21+LTS-T.ova` downloaded from PivNet will result in `3.0.21`, whereas `3.0.21-build.1098` from Ops Manager API endpoint `/api/v0/info` results in `3.0.21-build.1098`.

**Comment by staylor14** [comment]
Resolved in [7.10.1](https://github.com/pivotal-cf/om/releases/tag/7.10.1)
