### ISSUE TITLE
Latest version of om doesn't have `deployed-products` cmd

### ISSUE THREAD

**Issue by degaurab** [pivotal-cf/om#64]
Hi OM team,
Can you please update ReadMe to reflect all supported commands.

Thanks

**Comment by zachgersh** [comment]
hey @degaurab the readme on the main page is autogenerated based on what is currently on master (not released).

You can do one of two things here:

- build master and you get all of the latest commands exactly as stated in the readme
- read the release notes for each github release which will point to exact features that are available

We can add a note to the readme that notes that the features on master may not necessarily be in released version as of yet.
