### ISSUE TITLE
configure-bosh can't take in an empty config

### ISSUE THREAD

**Issue by adi-mishra** [pivotal-cf/om#65]
`om -k -t <target> -u <user> -p <password> configure-bosh  --iaas-configuration '{}'`

Fails with error Missing template errors/400

**Comment by zachgersh** [comment]
@adi-mishra what would you have liked to have seen happen in this specific case?

**Comment by zachgersh** [comment]
poke @adi-mishra and cc @pdelagrave

**Comment by adi-mishra** [comment]
@zachgersh I apologize for late reply (switched pairs and didn't login to github UI). I would like for OM to not configure anything while not raising an error, as nothing was specified in the JSON.

**Comment by zachgersh** [comment]
No problem! If you leave the flag off it has the desired outcome you want.
Does that not work for you?

**Comment by adi-mishra** [comment]
@zachgersh Yes, in our codebase we did accommodate for it. But it was weird seeing OM fail when provided with although an empty but valid json config.

**Comment by zachgersh** [comment]
@adi-mishra - yeah, empty is not a valid configuration for ` --iaas-configuration` hence the failure. We won't accept empty but I might consider making it fail with a better error. Would that work?

**Comment by adi-mishra** [comment]
@zachgersh Yeah better error message would be more helpful. Thanks.

**Comment by joshzarrabi** [comment]
This commit fixes this: https://github.com/pivotal-cf/om/commit/7b24241e74649ea05b7e6fabb6fc415343d252a8
