### ISSUE TITLE
OM tool does not work with SAML integrated Ops Manager 

### ISSUE THREAD

**Issue by anoumana** [pivotal-cf/om#66]
Right now OM tool takes user name, password, need to be able to use it with uaac client name/secret.
        om-alpine -t https://$OPSMAN_HOST -k -u "$OPSMAN_USER" -p "$OPSMAN_PASSWORD" upload-stemcell --stemcell $file

**Comment by zachgersh** [comment]
hey @anoumana - thanks for reporting this issue! We didn't try this with SAML as of yet. What sort of workflow would you be looking for? Would you want to pass a SAML token to OM? Can you ask UAA for a set of client credentials based on your SAML token (we do support this flow already).

**Comment by anoumana** [comment]
@zachgersh yes i am ok with uaa client credentials. I will try with that, looks like the scope and authorities are these. I can give that a shot and see if this will work. Thanks.
scope (list):  opsman.admin
authorized grant types (list):  client_credentials
authorities (list):  opsman.admin

**Comment by zachgersh** [comment]
@anoumana no problem - please re-open if you find another issue!
