### ISSUE TITLE
OM Tool should support JSON file for input to -p and -pn during configure-product

### ISSUE THREAD

**Issue by DonBower** [pivotal-cf/om#67]
When issueing the configure-product command, you should be able to specify a JSON file, and not just the command-line string.  for example:
./om -k -t https://my-ops-man.net -u admin -p supersecretpassword configure-product -n p-mysql -p /tmp/p-mysql-properties.json -pn /tmp/p-mysql-networks.json

**Comment by FaKeller** [comment]
I would love to be able to opt-in to use JSON files wherever there is JSON input required. An implementation enabling this could follow the [default curl behavior](https://curl.haxx.se/docs/manpage.html#-d) for the `@` symbol in passed data.

**Comment by zachgersh** [comment]
@DonBower - this should be pretty easy to do.

@FaKeller - Giving the `@` symbol special meaning would be a fun dev challenge but I certainly don't want to use it when a normal flag will do. Appreciate the suggestion though!

**Comment by FaKeller** [comment]
I might be a little biased as I have been using `om curl` a lot, but naming the command "curl" and not supporting the `@` syntax was unexpected. Also, curl supports stdin: `cat data.json | curl -d @-`. While stdin support does not make much sense in case multiple JSON arguments need to be supplied (e.g. for `om configure-product`) it might make sense to think about how to consistently add file/stdin support to the `om curl` command. Anyways, I'd love to see files supported either with or without the `@`! :-)

**Comment by FaKeller** [comment]
@DonBower by the way in the meantime you can use something along the lines of:

```bash
om ... configure-product -n p-mysql -p "$(cat properties.json)" -pn "$(cat network.json)"
```

**Comment by DonBower** [comment]
What works for me is:
P_PROPERTIES=$(cat $PROPERTIES_JSON)
om ... configure-product -n p-mysql -p "$(P_PROPERTIES)"
where $PROPERTIES_JSON is the json file name.
So this is an acceptable substitute.
Thanks for the suggestion @FaKeller !

**Comment by rizwanreza** [comment]
Thanks @FaKeller and @DonBower, closing the issue.

@FaKeller We will consider looking into supporting proper curl behavior natively in `om curl` command.
