### ISSUE TITLE
Bad SSH Key in --iaas-configuration on AWS Doesn't Show Error

### ISSUE THREAD

**Issue by cholick** [pivotal-cf/om#68]
Using om `0.22.0` against OpsManager `1.10.4` on AWS, inputting a bad ssh key via the UI shows an error message.

Using `--iaas-configuration`, on the other hand, with a bad key does not return any error message and `om` returns exit code 0.

**Comment by zachgersh** [comment]
hey @cholick - I believe when using the API you bypass a lot of the "checkers" that would be in place in terms of form validation. We'd have to reimplement all of this in `om` and I don't think that is a path we want to go down. Might be worth asking Ops Manager if they'd like to do validation on there API?

I could see us just validating the format of SSH keys and SSL Certs, would that be a decent compromise?

**Comment by cholick** [comment]
Validating format would go a long way: it would have caught our issue.

**Comment by craigbookwalter** [comment]
this bit me too on openstack in https://github.com/pivotal-cf/om/issues/46

**Comment by zachgersh** [comment]
Great. Formatting feels like a decent compromise.

**Comment by krishicks** [comment]
This fails to configure even when it's a valid SSH key. In my case it was an ed25519 SSH key. It also failed silently, which made it quite difficult to diagnose.

I don't think validating format should be done; rather the key should be loaded in some way to see that it is valid. An ed25519 key is just as valid as an rsa key.

**Comment by ryanmoran** [comment]
This is absolutely an OpsManager bug, and should be reported to them as such.

**Comment by rizwanreza** [comment]
I've notified the OpsManager team about this since this requires an API level validation. Om aims to be a lightweight CLI to the OpsManager API and validating input extensively is out of scope. OpsManager should be able to fix this soon.

**Comment by rizwanreza** [comment]
OpsManager team believes that this has been fixed in OpsManager 1.11. Would you be able to give it a try against that version?
