### ISSUE TITLE
--ignore-warnings flag not defined for apply-changes

### ISSUE THREAD

**Issue by clbeeson** [pivotal-cf/om#72]
Adding the --ignore-warnings flag to the apply-changes command results in; "flag provided but not defined: -ignore-warnings", this flag should flow through to the Operations manager invocation.

**Comment by zachgersh** [comment]
Thanks for posting an issue @clbeeson - This flag is defined:

https://github.com/pivotal-cf/om/blob/master/commands/apply_changes.go#L18

Was wondering if you were on an old version?
![screen shot 2017-05-15 at 9 59 52 am](https://cloud.githubusercontent.com/assets/689411/26069322/4c607278-3955-11e7-90b7-a549c8ca0019.png)

**Comment by clbeeson** [comment]
The issue was not with om, it was actually in the pivotal-cf pipelines, the parm was not passed and is now being passed incorrectly
