### ISSUE TITLE
curl command should have verbose flag

### ISSUE THREAD

**Issue by stupakov** [pivotal-cf/om#73]
When using `om curl`, it would be very helpful to have a flag that triggers the `curl` command to be issued with the `-v` (verbose) flag.

Allowing the curl request and response to be viewed can help with troubleshooting when the ops manager API responds in an unexpected way.

**Comment by DonBower** [comment]
I vote for this...

**Comment by utako** [comment]
Hey @stupakov,

We've just finished [this story](https://www.pivotaltracker.com/n/projects/975916/stories/153271673), which implements a `--trace` global flag for all commands. Does this address your needs? It should be in the next `om` release. :)

Thanks,
@kenchenpcf and @utako, PCF Releng Team

**Comment by utako** [comment]
Hello @stupakov,

I'm going to go ahead and close this issue, as I believe we've resolved this issue. Please go ahead and reopen this or open another issue if you feel otherwise.

Thanks,
@utako, PCF Releng Team
