### ISSUE TITLE
"waiting for response" time should be configurable

### ISSUE THREAD

**Issue by krishicks** [pivotal-cf/om#75]
When uploading a large tile like ERT our Concourse job logs get flooded with these messages:

> 33s elapsed, waiting for response from Ops Manager...
> 34s elapsed, waiting for response from Ops Manager...
> 35s elapsed, waiting for response from Ops Manager...
> 36s elapsed, waiting for response from Ops Manager...
> 37s elapsed, waiting for response from Ops Manager...
> 38s elapsed, waiting for response from Ops Manager...
> 39s elapsed, waiting for response from Ops Manager...
> 40s elapsed, waiting for response from Ops Manager...
> 41s elapsed, waiting for response from Ops Manager...
> 42s elapsed, waiting for response from Ops Manager...
> 43s elapsed, waiting for response from Ops Manager...
> 44s elapsed, waiting for response from Ops Manager...
> 45s elapsed, waiting for response from Ops Manager...

Given ERT can take 10 minutes or more to be processed by Ops Mgr, we end up with 600+ lines in our log that don't need to be there. This causes the page to take an unnecessarily long time to load and isn't helpful.

It would be much nicer if we could configure the update interval, or if it at least defaulted to something more sane, like 10 seconds (as Terraform does).

**Comment by madamkiwi** [comment]
Thanks for the suggestion.  We like the idea and will create a story to prioritize this feature.

**Comment by olle-brkt** [comment]
+1

What's the status on this? Could not view the story

**Comment by krishicks** [comment]
The accepted label means it should be in there somewhere, though I haven’t looked for it.

**Comment by ryanmoran** [comment]
Looks like @madamkiwi didn't include the [new story](https://www.pivotaltracker.com/story/show/147645505) she wrote up. I added some more details and then prioritized it in the backlog. I think someone should have time to look at it in the next week or so.

**Comment by olle-brkt** [comment]
Sounds great, thanks!

**Comment by utako** [comment]
As the story above has been released, I'll go ahead and close this issue. Please feel free to reopen this if it hasn't been resolved.

Thanks,
@utako, PCF Releng Team
