### ISSUE TITLE
configure-bosh on openstack properties

### ISSUE THREAD

**Issue by JasonMorgan** [pivotal-cf/om#76]
Hello,  I don't see a way to get the valid field names for configure-bosh on openstack.  The names in the example document don line up with the return from `/api/v0/staged/director/properties`.  Here is the return from a v1.10.7 opsman instance running on openstack:
```
{
  "iaas_configuration": {
    "identity_endpoint": null,
    "username": null,
    "password": null,
    "tenant": null,
    "security_group": null,
    "key_pair_name": null,
    "ssh_private_key": null,
    "region": null,
    "ignore_server_availability_zone": false,
    "disable_dhcp": false
  },
  "director_configuration": {
    "ntp_servers_string": "",
    "metrics_ip": null,
    "resurrector_enabled": false,
    "max_threads": null,
    "database_type": "internal",
    "blobstore_type": "local"
  },
  "security_configuration": {
    "trusted_certificates": null,
    "generate_vm_passwords": true
  }
}
```

Also when I try and load the iaas settings in the cli says the config was updated successfully but I don't see the staged changes in either the UI or via the api call above.

**Comment by JasonMorgan** [comment]
Also I'm using cli version 0.23.0

**Comment by krishicks** [comment]
@JasonMorgan If you look at the code, it's all there in the struct tags: https://github.com/pivotal-cf/om/blob/master/commands/bosh_form_models.go#L50

**Comment by JasonMorgan** [comment]
Cool, let me see if I can get that working, thank you!

**Comment by JasonMorgan** [comment]
That solves the arguments issue. Thank you!
