### ISSUE TITLE
[Feature request] Allow responses to be JSON formatted

### ISSUE THREAD

**Issue by sahilm** [pivotal-cf/om#77]
/cc @henderjm @jamiemonserrate 

Hello,
Thanks for building om. We primarily use om in an automated fashion on the services-pipeline team. We would like om to provide the ability to format responses in a machine parseable format, such as JSON.

Currently we have to parse om responses using a mixture of `grep/cut/awk` etc. For example the response of:

```bash
om --target "https://example.com/" available-products
```
is 
```
+------+---------+
| NAME | VERSION |
+------+---------+
| cf   | 1.11.0  |
+------+---------+
```
or fallback to using `om curl`.

We would like a flag, such as `--format json` to control the output format. The above response could look like:
```json
[
  {
    "name": "cf",
    "version": "1.11.0"
  }
]
```

Let us know what you think. Thanks.

**Comment by zachgersh** [comment]
Hey @sahilm - I believe the intention here was that if you wanted the output to be json formatted you would instead just use `om curl`. I get that this has the unfortunate side-effect of having to remember the endpoint you'd like to hit but it does mean that we have one less flag to implement in all of the commands that are table formatted.

Does `om curl` not suit your needs?

**Comment by sahilm** [comment]
We are now using `om curl`. It's nice that `om` has an escape hatch. The issue with relying on `om curl` is that we end up tightly coupling ourselves to the OpsManager API. `om` commands provide us with a nice abstraction and keep us nicely de-coupled :).

I understand your concern about implementing the flag. Would you be open to a PR perhaps?

**Comment by madamkiwi** [comment]
@sahilm This sounds like a useful flag. A PR would be great however, before working on this we'd like to check with the team about supporting this feature.

**Comment by sahilm** [comment]
@madamkiwi Hey. Thanks for getting back. Any ideas on when I would know if it's okay to start work on a PR?
