### ISSUE TITLE
Feature Request: add 'deploy-products' flag to apply-changes command

### ISSUE THREAD

**Issue by dave-malone** [pivotal-cf/om#84]
Would be great to be able to pass in valid values for the `deploy_products` value when triggering an install. Valid values appear to be 'all' or 'none' according to the API docs: http://opsman-dev-api-docs.cfapps.io/#triggering-an-install-process

**Comment by davewalter** [comment]
Hi @dave-malone,

I can definitely see a use-case for this once Ops Manager supports only deploying a subset of the staged product changes, but I'm curious as to what benefit you see in it's current state? I would assume that `all` is the default, and `none` doesn't seem to be very useful.

Regards,
Dave

**Comment by dave-malone** [comment]
@davewalter `none` is needed as part of the new backup and restore instructions for deploying only the director:

https://docs.pivotal.io/pivotalcf/1-11/customizing/deploy-ops-man-director.html

Since this option isn't part of apply changes, we've reverted to using `om curl` with the payload, but it doesn't provide the same experience as `om apply-changes` where the output is streamed back through the cli.

**Comment by davewalter** [comment]
Makes sense. `none` isn't really none at that point. We can definitely look at adding that.

**Comment by peterellisjones** [comment]
@davewalter can confirm none is very useful. 

We have a pipeline where we have two "apply changes" 
- deploying the bosh director
- deploying the tiles

These need to be separate because there we're using IPSec so need to configure the director with IPSec after deploying it and before deploying any tiles.

**Comment by kkallday** [comment]
@dave-malone I just merged a PR that @peterellisjones made (#95). It will allow you to pass `--skip-deploy-products` to achieve the behavior you described above. After we cut a new release I will close this issue. Feel free to build `om` from source if you want to begin using the feature today.
