### ISSUE TITLE
export-installation returning unexpected response

### ISSUE THREAD

**Issue by bhudlemeyer** [pivotal-cf/om#85]
export-installation with opsman 1.11.3.0 is returning unexpected response 

    om-linux --target https://ops-man.net --skip-ssl-validation --username user --password 'PW' --request-timeout 6000 export-installation --output-file /tmp/build/0f36ad4e/pcf-pipelines/tasks/export-opsmgr-settings/opsmgr-settings/installation.zip
    exporting installation
    30m1s elapsed, waiting for response from Ops Manager...
    could not execute "export-installation": failed to export installation: request failed: unexpected response

    real    30m1.270s
    user    0m39.648s
    sys     1m44.332s

Can export from opsman gui successfully without issue.

**Comment by bhudlemeyer** [comment]
Closing for not but should probably be noted OPS man appears to have a 30 minute time out for api calls. I went in and modified the tempest-web configuration in this file:

    /home/tempest-web/tempest/web/config/thin.production.yml 
    from its default setting of 30min (1800 sec) to 
    socket: /tmp/tempest-web.sock
    rackup: config.ru
    threaded: true
    timeout: 60000 (just to ensure we didnt hit anything)

Restarted ops man and the export succeded.

**Comment by acrmp** [comment]
Hi Brandon,

Thanks for sharing your workaround for this issue.

Can you give us some more detail about the size of the generated installation file and the approximate length of time it eventually took for your export to succeed?

Thanks,

@acrmp && @kkallday

**Comment by bhudlemeyer** [comment]
using 1.11.3.0 file size was around 10.6GB and took roughly 33 to 35min. So right out side the timeout window basically.

**Comment by bhudlemeyer** [comment]
As a note I have the following tiles deployed in my test system
- ERT 1.11.1
- Redis 1.7.5
- RabbitMQ 1.7.21
- Metrics 1.3.7
- MySQL for PCF 1.8.10
- JMX Bridge 1.8.22

**Comment by kkallday** [comment]
Unfortunately, since this constraint is on the Ops Manager server side there's nothing we can do from the perspective of `om`. We have given this feedback to the Ops Manager team and they are going to consider bumping the timeout. Thanks for letting us know about this!

Kevin & @joshzarrabi
