### ISSUE TITLE
om release not working on osx

### ISSUE THREAD

**Issue by xchapter7x** [pivotal-cf/om#86]
om release: 0.23.0
osx version: 10.12.5 (16F73)
ops manager: 1.11.3.0
when making calls using the om cli, the calls just hang. 
I've compiled locally using commit: 383848e17fc25e128c6657c9190c84bae287bc69 (current HEAD on master). This works fine, calls to ops manager complete successfully.

Not sure what the issue with the release binary is.

**Comment by kkallday** [comment]
Hi @xchapter7x,

We've attempted to reproduce the issue on our machine which is running the same OSX version, om downloaded from https://github.com/pivotal-cf/om/releases/tag/0.23.0, and targeting the same ops manager however we did not run into the same issue.

```
$ ~/Downloads/om-darwin -t <target> -u <user> -p <password> -k curl -p "/api/v0/available_products"
Status: 200 OK
Cache-Control: max-age=0, private, must-revalidate
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Thu, 06 Jul 2017 21:34:49 GMT
Etag: W/"d751713988987e9331980363e24189ce"
Server: nginx/1.4.6 (Ubuntu)
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: 4f730367-212b-4fe7-8c95-dee83fa91815
X-Runtime: 0.124931
X-Xss-Protection: 1; mode=block
[]
```

Can you confirm that you downloaded the om darwin binary?

Thanks,

@kkallday & @joshzarrabi

**Comment by xchapter7x** [comment]
just looked back in my history:
```
$ wget https://github.com/pivotal-cf/om/releases/download/0.23.0/om-darwin
```
the version and help commands worked, just not any actual calls to ops man using the downloaded binary. 

i just re-wget'd it and all is good. really strange, probably error on my part somewhere.
anyways, ill close this out for now.
Thanks.

**Comment by joshzarrabi** [comment]
@xchapter7x Okay cool, thanks for submitting the issue and let us know if you see any other problems.

**Comment by ryanmoran** [comment]
Thanks for looking into this @joshzarrabi and @kkallday!
