### ISSUE TITLE
Configuring AWS Services

### ISSUE THREAD

**Issue by jgeorge300** [pivotal-cf/om#91]
Can the OM tool configure products that have service plans? Should I be able to add, update or remove plans?

I'm trying to configure the Service Broker for AWS with OM. I'm trying to add a plan and update another. OM or Ops Manager  returns an error stating a required field cannot be blank. The field is being set. Removing the field does not change the error.

I've tried curl and the configure-properties parameters.

Error:
`{"errors":{".properties.rds_aurora_plans":["Record 1: Create Db Instance Backup Retention Period can't be blank","Record 2: Create Db Instance Backup Retention Period can't be blank"]}}`

Properties:
`{
    ".properties.rds_aurora_plans": {
      "value": [
        {
          "guid": {
            "value": "f29dd4d9-f708-4861-8d59-2096e72ba6e2"
          },
          "name": {
            "value": "basic"
          },
          "description": {
            "value": "For small projects and during development. 2 vCPU, 15GB"
          },
          "free": {
            "value": false
          },
          "bullets": {
            "value": "Two processors\r\nSmall instance\r\nNo backups\r\n"
          },
          "CreateDBInstance_Engine": {
            "value": "aurora"
          },
          "CreateDBInstance_EngineVersion": {
            "value": "5.6.10a"
          },
          "CreateDBInstance_CopyTagsToSnapshot": {
            "value": true
          },
          "CreateDBInstance_DBInstanceClass": {
            "value": "db.r3.large"
          },
          "CreateDBInstance_BackupRetentionPeriod": {
            "value": 1
          },
          "CreateDBInstance_StorageEncrypted": {
            "value": false
          },
          "CreateUserPrivileges_Grants": {
            "value": "CREATE, SELECT, INSERT, UPDATE, DELETE, EXECUTE, DROP, LOCK TABLES, ALTER, INDEX"
          },
          "CreateUserPrivileges_EnforceSSL": {
            "value": false
          }
        },
        {
          "guid": {
            "value": "9cb19fad-4dcb-4b71-a2d7-c6546b0b1460"
          },
          "name": {
            "value": "om"
          },
          "description": {
            "value": "OM"
          },
          "free": {
            "value": false
          },
          "bullets": {
            "value": "Two processors\r\nSmall instance\r\nNo backups\r\n"
          },
          "CreateDBInstance_Engine": {
            "value": "aurora"
          },
          "CreateDBInstance_EngineVersion": {
            "value": "5.6.10a"
          },
          "CreateDBInstance_CopyTagsToSnapshot": {
            "value": true
          },
          "CreateDBInstance_DBInstanceClass": {
            "value": "db.r3.large"
          },
          "CreateDBInstance_BackupRetentionPeriod": {
            "value": 1
          },
          "CreateDBInstance_StorageEncrypted": {
            "value": false
          },
          "CreateUserPrivileges_Grants": {
            "value": "CREATE, SELECT, INSERT, UPDATE, DELETE, EXECUTE, DROP, LOCK TABLES, ALTER, INDEX"
          },
          "CreateUserPrivileges_EnforceSSL": {
            "value": false
          }
        }
      ]
    }
}
`

**Comment by kkallday** [comment]
Hi @jgeorge300,

It looks like you're getting an error because a required field was not provided however, I see in your properties you did provide the `CreateDBInstance_BackupRetentionPeriod` to both records. Can you give me the version of the AWS service broker tile you are using?

**Comment by jgeorge300** [comment]
We have 1.3.0 installed.

**Comment by kkallday** [comment]
Hey @jgeorge300,

After doing some debugging with @ryanmoran, it looks like the payload you sent is slightly off. Since the property you are updating is a `collection` the syntax is a bit different. Instead of nesting the value in another object with `value` you just make the value a key of the property. For instance, the following payload with `configure-product` should work:

**NOTE:** the property `CreateUserPrivileges_Grants` is named `grans` on `1.4.0`
```
{
   ".properties.rds_aurora_plans" : {
      "value" : [
         {
            "CreateDBInstance_CopyTagsToSnapshot" : true,
            "CreateDBInstance_StorageEncrypted" : false,
            "CreateDBInstance_Engine" : "aurora",
            "bullets" : "Two processors\r\nSmall instance\r\nNo backups\r\n",
            "CreateDBInstance_DBInstanceClass" : "db.r3.large",
            "Grants" : "CREATE, SELECT, INSERT, UPDATE, DELETE, EXECUTE, DROP, LOCK TABLES, ALTER, INDEX",
            "CreateDBInstance_EngineVersion" : "5.6.10a",
            "name" : "basic",
            "free" : false,
            "guid" : "f29dd4d9-f708-4861-8d59-2096e72ba6e2",
            "CreateDBInstance_BackupRetentionPeriod" : 1,
            "description" : "For small projects and during development. 2 vCPU, 15GB",
            "CreateUserPrivileges_EnforceSSL" : false
         }
      ]
   }
}
```
