### ISSUE TITLE
Ubuntu/Debian package available

### ISSUE THREAD

**Issue by drnic** [pivotal-cf/om#96]
For anyone who wants to install `om` to Ubuntu/Debian via `apt-get install` I've added an `om` package to [our APT repo](https://apt.starkandwayne.com), and new versions will be automatically rebuilt with each new github release.

```
wget -q -O - https://raw.githubusercontent.com/starkandwayne/homebrew-cf/master/public.key | apt-key add -
echo "deb http://apt.starkandwayne.com stable main" | tee /etc/apt/sources.list.d/starkandwayne.list
apt-get update

apt-get install om
```

Thanks for `om`, its much nicer to use in our CI than our old lengthy shell + curl scripts!

**Comment by joshzarrabi** [comment]
Thanks so much! We will add this to our readme.
