### ISSUE TITLE
Feature requestion: accept EULA and download tiles from PivNet

### ISSUE THREAD

**Issue by drnic** [pivotal-cf/om#97]
Om can upload a product tile to opsmgr, but it cannot download the tile from PivNet in the first place. And since using PivNet website requires manually clicking the EULA popup to get the download URL, it makes it very hard to get the explicit URL so I can go to a bastion/jumpbox and `wget` the tile, before using `om` to upload it.

Which means I'm stuck on my laptop behind slow local internet conditions.

Could Om be extended to support downloading PivNet products? Or is there another CLI for interacting with PivNet? I'm aware for `pivnet-resource` for concourse; but I was trying to interact with pivnet/opsmgr outside of CI.

**Comment by zachgersh** [comment]
Wouldn't you be able to use the pivnet-cli to download the items off of
pivnet?

**Comment by ryanmoran** [comment]
https://github.com/pivotal-cf/pivnet-cli

**Comment by drnic** [comment]
Thanks @ryanmoran
