### ISSUE TITLE
Curl operation returns error code 0 for Status: 400 BAD REQUEST

### ISSUE THREAD

**Issue by DonBower** [pivotal-cf/om#98]
Running this command in a Concourse pipeline, we received a `Status: 400 Bad Request`, however, the om-linux command returned error-code 0.
Along with #73, could we also return non-zero error-code when `Status: 200....` is not received?

```
./tool-om/om-linux --target "https://tagsasopsmgr01.r1-core.r1.aig.net" --skip-ssl-validation --username "admin" --password "<password>" curl --path /api/v0/installations --request POST --data '{"enabled_errands":{"cf-29886296b6c1722bdab4":{"post_deploy_errands":["smoke-tests","push-apps-manager","notifications","notifications-ui","push-pivotal-account","autoscaling","autoscaling-register-broker"]}}}'
Status: 400 Bad Request
Connection: keep-alive
Content-Length: 0
Content-Type: text/html; charset=utf-8
Date: Thu, 03 Aug 2017 17:20:33 GMT
Server: nginx/1.4.6 (Ubuntu)
Strict-Transport-Security: max-age=31536000
X-Request-Id: a68d70d3-bfe5-445a-8c7b-9bf87c2f0970
X-Runtime: 0.001771

Exit code for curl POST is: 0
```

**Comment by joshzarrabi** [comment]
You're correct. It should exit with a non-zero code in that case. We will look into it. I edited your password out of the comment, so you might want to rotate credentials. @DonBower

**Comment by kkallday** [comment]
Hi @DonBower,

`om curl` will now exit with 1 when the command fails (https://github.com/pivotal-cf/om/commit/f5508425c00c6f8afa35d49aa0035efd33c2798f). This will be available in the next release of `om`. Feel free to build from source if you'd like this behavior right now.

Thanks for reporting this. 🚗

**Comment by DonBower** [comment]
Thanks, @kkallday, for fixing it!
