### ISSUE TITLE
Feature Request: Apply-Changes should have flag to run errands

### ISSUE THREAD

**Issue by DonBower** [pivotal-cf/om#99]
When running the apply-changes command, it would be nice to be able to specify which errands to run on-the-fly, similar to [Triggering-an-install-process](https://opsman-dev-api-docs.cfapps.io/#triggering-an-install-process) allows.
We could form the  json string similar to below, and the tool would substitute the product-name for the product-guid:

```
{
  "enabled_errands": {
    "<product-name, i.e. cf>": {
      "post_deploy_errands": [
        "smoke-tests",
        "push-apps-manager",
        "notifications",
        "notifications-ui",
        "push-pivotal-account",
        "autoscaling",
        "autoscaling-register-broker"
      ]
    }
  }
}
```

**Comment by ryanmoran** [comment]
Hi @DonBower, can I ask for a clarification for how this is different that your earlier request in #92?

**Comment by DonBower** [comment]
Hey @ryanmoran!
Great question!
My answer is... uh,... er,... ok, I just forgot I put it in, and for whatever reason I did not see it..

Let me clarify #92 with how it might be implemented with the comments I made in this one, and we can close this one out.

**Comment by kenchenpcf** [comment]
This issue is duplicated here: https://github.com/pivotal-cf/om/issues/92
